### ISSUE TITLE
overflow: scroll in div within ParallaxLayer

### ISSUE THREAD

**Issue by evliu** [pmndrs/react-spring#100]
Hi,

I tried looking for answers after trying to figure it out myself, but is it possible to have it possible to scroll the perpendicular direction of a `div` component that has overflow content? For example, I have a `Parallax` component with horizontal scrolling containing `ParallaxLayer`s. I want to be able to scroll the content on a particular `ParallaxLayer` but can't figure out how. Any help would be awesome!

Thanks!

**Comment by drcmda** [comment]
Sure, parallax layers are just divs

```jsx
<Parallax.Layer style={{ overflowX: 'auto'}} onScroll={e => e.stopPropagation()}>
  <div style={{ position: 'absolute', top: 0, width: '200%' }}>
    super long text ...
```

You could leave out the stopPropagation thing but then you would scroll both your inner region and the parallax container.
