### ISSUE TITLE
[9.0.0-rc.3] Event props in useSpring not containing full list of values

### ISSUE THREAD

**Issue by tim-soft** [pmndrs/react-spring#1008]
## 🐛 Bug Report

Following up on https://github.com/react-spring/react-spring/issues/997 

In previous releases, `f` from `onChange` would be an object containing all animated values at that instance

```jsx
const [props, set] = useSprings(pages.length, i => ({
    x: i * window.innerWidth,
    scale: 1,
    onChange: f => console.log(f),
}))
```

i.e. `f` in this case would normally be 
```
{
    x: 1234,
    scale: 1.2
}
```

In v9.0.0-rc.3, f is equal to whatever value has changed in that frame
```
// Scale changes 1.0 -> 1.2
f = 1.2
// x changes 1234 -> 1235
f = 1235
```

 I'm not sure if this change was intentional or not but I think the old behavior is much more desirable/useful

**Comment by aleclarson** [comment]
Fixed by https://github.com/react-spring/react-spring/commit/25da5024e659af9462705018c4fc80c61c2302fc, will be included in `9.0.0-rc.4` when released.

More tests are definitely needed if something like this is slipping through. 🙃
