### ISSUE TITLE
Custom inertial spring used to work on canary.808.17, but not in rc3

### ISSUE THREAD

**Issue by HQ92** [pmndrs/react-spring#1010]
## 🐛 Bug Report

I previously implemented a rubberbanding drag slider with react-use-gesture and react-spring that used to work quite well based upon dbusmut's initial code for something similar. This used to work with the new decay and initial velocity functions introduced in earlier versions of 9 quite well. It has now stopped working after updating to rc3. It seems to be something to do with triggering a state update at the same time as updating the spring value which seems to affect the onchange prop on the spring from executing as expected.

The repro should display the issue, toggling the state update before flinging the drag handle should highlight the difference in the way react-spring reacts.

## To Reproduce

Try updating state at the end of a drag event from react-use-gesture, whilst updating a spring with decay enabled with an initial velocity.

## Expected behavior

The code used to work before rc3, it should limit the animation of the drag handle to its confines whilst allowing rubberbanding whilst being dragged.

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-rc3-updating-onchange-within-custom-hook-yy8f7?file=/src/index.js

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.8.6

**Comment by HQ92** [comment]
Hiya,

I was just wondering if there was any sort of timescale for the next rc version as a few of my projects are just on hold waiting for it. Do you reckon it would be better for me to just roll back to a previous version in the meantime just to get the sites working or are we close to a fix?

Thanks again and appreciate all the work put into this library 🥇

**Comment by joshuaellis** [comment]
closing in favour of #1026 and lack of activity

**Comment by HQ92** [comment]
Hi @joshuaellis 

I've had another investigation of this today and the issue still happens though in a slightly different way now:

https://codesandbox.io/s/react-spring-rc3-updating-onchange-within-custom-hook-forked-kyq3d?file=/src/index.js

The spring still overextends its bounds but then immediately springs back to it's furthest extension point rather than animating back as I would expect it to.

**Comment by HQ92** [comment]
Hi @joshuaellis ,

I've managed to fix the sandbox with the latest version of react-spring so it all looks good from my end! 

https://codesandbox.io/s/react-spring-912-inertial-spring-kyq3d?file=/src/index.js

Thanks for the help and updates and hope we get to see more features coming on such a great library 📦

**Comment by joshuaellis** [comment]
This has been released on `9.2.0-beta.0` if you could try it that would be great ⭐

**Comment by HQ92** [comment]
This works perfectly for me - https://codesandbox.io/s/inertial-spring-react-spring-v920-beta0-kyq3d, it's not doing the jumping to the end value, ignoring the decay animation, at the end anymore. So 10/10 from me 😋

**Comment by joshuaellis** [comment]
💃🏻
