### ISSUE TITLE
[useTrail] Delay property is returning other prop names instead of the keys

### ISSUE THREAD

**Issue by Kauyumari** [pmndrs/react-spring#1053]
## 🐛 Bug Report

Using the useTrail hook, I'm trying to add a delay for each item rendered by the trail. The problem is that when I set a delay with the function api it returns the names<[strings]> of the other animated values configured in the hook.  

## To Reproduce

![code](https://user-images.githubusercontent.com/47075744/84406727-8c617a80-abcf-11ea-8d41-42dbede2c438.png)

## Expected behavior

It should start the animation depending on the delay by key

## Environment

- `react-spring` v8.0.27
- `react` v16.12.0

**Comment by aleclarson** [comment]
Please try with v9: #985

**Comment by alexandereneroth** [comment]
Can reproduce in `v9.0.0-v3`
https://codesandbox.io/s/goofy-cdn-tfu1e?file=/src/index.js

Is there any way to modify the delay between items with `useTrial`?

**Comment by joshuaellis** [comment]
Hey @Kauyumari & @alexandereneroth,

The keys are spring keys and this is shared across the library so I don't think this should change.

However, `useTrail` uses `useSprings` under the hood. Your spring props are passed to the `useSprings`. `useSprings` prop argument can be a function:

```ts
(index: number, ctrl: Controller): Props
```

So if you do something like this:

```js
const [trail] = useTrail(items.length, (i) => ({
    config: { mass: 5, tension: 2000, friction: 200 },
    delay: () => {
      // key will be opacity, x, and height. Not 1,2,3,4
      return 1000 * (i + 1)
    },
    opacity: open ? 1 : 0,
    x: open ? 0 : 20,
    height: open ? 110 : 0,
    from: { opacity: 0, x: 20, height: 0 },
  }))
```

It should then work as intended? Here's @alexandereneroth's sandbox modified to show this – https://codesandbox.io/s/recursing-jang-6rj0g?file=/src/index.js:240-581

Let me know thoughts?
