### ISSUE TITLE
Broken Interpolation.get() with function refs on animated elements

### ISSUE THREAD

**Issue by dlindenkreuz** [pmndrs/react-spring#1055]
## 🐛 Bug Report

When using a function ref on an `animated` element, `interpolatedSpringValue.get()` is broken and will return stale values. This also breaks initial value integration in react-use-gesture.

This is a pretty weird edge case, as it happens only when (1) a function ref is used on the `animated` element that consumes the SpringValue **and** (2) when the SpringValue results from an interpolation (even the identity fn `fooSpringValue.to(x => x)` breaks it).

Temporary workarounds are: Either replace the function ref with a mutable ref object (-> `useRef()`), remove the ref entirely, or do not use any interpolation at all.

Possibly related: https://github.com/react-spring/react-spring/issues/1037

## To Reproduce

Please see the Codesandbox reproductions below. The examples show a draggable element with react-use-gesture that snaps back to its initial position when released. The current animated value is provided as an initial value to react-use-gesture, as described in the [react-use-gesture docs](https://use-gesture.netlify.app/docs/options#initial).

## Expected behavior

Should work like in v8.0.27.

## Link to repro

- react-spring@8.0.27 (works fine, some small API adjustments were made for v8 compatibility): https://codesandbox.io/s/festive-haslett-yptcb?file=/src/App.js
- **react-spring@9 (does not work)**: https://codesandbox.io/s/laughing-liskov-uhyib?file=/src/App.js

## Environment

- `react-spring` v9.x
- `react` v16.13.x

**Comment by joshuaellis** [comment]
Hi @dlindenkreuz, sorry it's taken so long to get round to this.

I'm just looking at this now, i've updated the sandbox to our latest version and I can't see a bug - https://codesandbox.io/s/frosty-thompson-jod9i?file=/src/App.js

Would you be able to check that and see if I've misunderstood? If the issue looks fixed then lets close the issue 👍🏼

**Comment by dlindenkreuz** [comment]
@joshuaellis Looking at your updated sandbox, this issue looks like it's fixed. Thanks for getting back to this after such a long time, and thanks to the team / community for fixing in the meanwhile 😅🎉
