### ISSUE TITLE
react-spring v9.0.0-rc-3: Example notification hub - Notification re appear notification after stopped and deleted 

### ISSUE THREAD

**Issue by gndplayground** [pmndrs/react-spring#1079]
## 🐛 Bug Report
First of all, I use v9.0.0-rc3.
I checked your example notification hub and implement it in my project. I realized that when we stop() and remove the notification, the notification still in the DOM. 

If we click on create a new notification, the stopped and deleted notification still appears and begins animated again where it stopped (resume the animation) along with the new notification. As I understand the stopped notification is not in the items list state so It's should not appear again.

I created the code sandbox so we can try with it. My code in the project didn't use ref like your code, use setState normal still got the same error. So I think it's not caused by ref in `Main onClick`
Also with video and screenshot.

## To Reproduce

![Screen Shot 2020-07-13 at 10 54 53 AM](https://user-images.githubusercontent.com/17973301/87269809-7a3d6980-c4f8-11ea-8076-8676fdb3eb49.png)

![Screen-Recording-2020-07-13-at-10 47 23-AM](https://user-images.githubusercontent.com/17973301/87269824-875a5880-c4f8-11ea-8fde-1717780e8ccb.gif)

## Expected behaviour

The stopped notification is not in the items list state so It's should not appear again.

## Code sandbox

https://codesandbox.io/s/react-spring-notification-hub-v9-rc-bug-51w7l?file=/src/App.js:2329-2345

## Environment

- `react-spring` v9.0.0-rc3

**Comment by gndplayground** [comment]
Maybe we could prevent this by not render the item when it's not in the `items` state.

```
 const listToast = transitions((style, item, state) => {
    if (!items.find((i) => i.key === item.key)) {
      return;
    }
  // return the Message normal
```

I used this to fix the problem in my implementation.

**Comment by toypiano** [comment]
It seems that the [example](https://codesandbox.io/s/issue-948-puurn) by @aleclarson works until the last canary (9.0.0-canary.808.17.55c5691).

The described behaviour is introduced from rc.1

**Comment by joshuaellis** [comment]
@dbismut I think this will be fixed?

**Comment by dbismut** [comment]
Should be fixed yes! It's now working properly and even better than in v8 according to my very basic stress tests.

**Comment by joshuaellis** [comment]
resolve by #1395
