### ISSUE TITLE
<Transition/> works in v8 but not v9: "Functions are not valid as a React child."

### ISSUE THREAD

**Issue by marshallds** [pmndrs/react-spring#1100]
## 🐛 Bug Report

I am trying to implement the [single component reveal example](https://www.react-spring.io/docs/props/transition) which works fine in v8. In v9 however, nothing renders and I get `Warning: Functions are not valid as a React child.`. I've reviewed the [v9 changes documentation](https://aleclarson.github.io/react-spring/v9/breaking-changes) but the only thing I saw was a note that the implementation was unified under the hood. It seems the interface for the `children` of the Transition component has changed but I can't find any indication of what it would be now. 

## To Reproduce

Follow the [documentation](https://www.react-spring.io/docs/props/transition) in v9

## Expected behavior

<Transition/> to hide/show inner animiated.div

## Link to repro

https://codesandbox.io/s/transition-in-beta-xbt1m?file=/src/index.js

## Environment

- `react-spring` v9.0.0-rc3 (But none of the beta's seem to work either)
- `react` v16.8.x

**Comment by aleclarson** [comment]
Sorry about the confusion! You can find more details in #809

> Also, the `Transition` component has changed. Its `children` prop now takes different arguments:
> 
> ```tsx
> <Transition
>   items={items}
>   from={{ opacity: 0 }}
>   enter={{ opacity: 1 }}
>   leave={{ opacity: 0 }}>
>   {(values, item) => (
>     <animated.div style={values}>{item}</animated.div>
>   )}
> </Transition>
> ```

**Comment by aleclarson** [comment]
Keeping this open so I remember to update the "Breaking Changes" section 👍

**Comment by kamikazebr** [comment]
> Keeping this open so I remember to update the "Breaking Changes" section 👍

Where is the Breaking Changes Section with that update? I cannot find. I want like to know how migrate the Transitions components
