### ISSUE TITLE
[v9.0.0-rc.3] TypeScript types not compatible with latest @types/react (16.9.44)

### ISSUE THREAD

**Issue by bengry** [pmndrs/react-spring#1102]
## 🐛 Bug Report
A new version of `@types/react` recently came out which depends on `csstype@3.0.2`, which in turn has better type definitions for CSS properties.
The latest `react-spring@v9.0.0-rc.3` is incompatible with these types when trying to use the `style` prop on animated components, throwing this example error (I used the `opacity` property, but the same holds true for most other properties):
```
  Types of property 'opacity' are incompatible.
    Type 'SpringValue<number>' is not assignable to type '"initial" | "inherit" | "-moz-initial" | "revert" | "unset" | FluidValue<Globals, any> | undefined'.
      Type 'SpringValue<number>' is not assignable to type 'FluidValue<Globals, any>'.
        The types returned by 'get()' are incompatible between these types.
          Type 'number' is not assignable to type 'Globals'.ts(2322)
```

## To Reproduce
Try to use the `useTransition` hook with it's returned callback, and render an `<animated.div />` with the styles given by the callback (see repro link).

## Expected behavior
There should not be a compile-time error for the `style` prop.

## Link to repro (highly encouraged)

https://codesandbox.io/s/elegant-mclaren-39xuy?file=/src/App.tsx

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.13.1

**Comment by phosphene47** [comment]
This change recently happened in `@types/react@16.9.44` ([source](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46435#issuecomment-667349908)). I solved this by downgrading to `@types/react@16.9.43` for now.

**Comment by Lumen27** [comment]
I'm on `@types/react@16.9.43` and still having this issue

**Comment by tbntdima** [comment]
Experiencing the same, what can be a temporary workaround until it's fixed?

**Comment by mechanicMo** [comment]
having this issue as well. @iam4x can you (or anyone else) go into more detail on the work around please?

these are the bits of code I think are relevant

`type AccordionContextValue = {
    accordionStyles: {
        maxHeight: SpringValue<string>;
        opacity: SpringValue<number>;
        transform: SpringValue<string>;
    };
    clickHandler: () => void;
    titleRef: React.MutableRefObject<null>;
};

const [accordionStyles, setAccordionStyles] = useSpring(() => ({
        maxHeight: '0vh',
        opacity: 0,
        transform: 'scale(0)',
    }));

setAccordionStyles({
            maxHeight: open ? '100vh' : '0vh',
            opacity: open ? 1 : 0,
            transform: open ? 'scale(1)' : 'scale(0)',
        });

<a.div style={accordionStyles} {...props}>
            {children}
        </a.div>`

**Comment by GitSquared** [comment]
> you stick with @types/react ^16.9.43

Does not seem to work here.

<details>
<summary>Example error, with useSpring and style={props}</summary>

<pre>
components/button.tsx:287:6 - error TS2322: Type '{ x: SpringValue
<number>; y: SpringValue<number>; scale3d: SpringValue<number[]>;
borderRadius: SpringValue<string>; opacity: SpringValue<...>; }' i
s not assignable to type '{ alignContent?: "initial" | "end" | "ba
seline" | "inherit" | "start" | "center" | "-moz-initial" | "rever
t" | "unset" | "normal" | "space-around" | "space-between" | "spac
e-evenly" | ... 4 more ... | undefined; ... 786 more ...; matrix3d
?: readonly [...] | ... 1 more ... | undefined; }'.
  Types of property 'opacity' are incompatible.
    Type 'SpringValue<number>' is not assignable to type '"initial
" | "inherit" | "-moz-initial" | "revert" | "unset" | FluidValue<G
lobals, any> | undefined'.
      Type 'SpringValue<number>' is not assignable to type 'FluidV
alue<Globals, any>'.
        The types returned by 'get()' are incompatible between the
se types.
          Type 'number' is not assignable to type 'Globals'.

287                             style={cursorSpringProps}
                                ~~~~~

  node_modules/@types/react/index.d.ts:1766:9
    1766         style?: CSSProperties;
                 ~~~~~
    The expected type comes from property 'style' which is declare
d here on type 'IntrinsicAttributes & AnimatedProps<{ onChange?: (
(event: FormEvent<HTMLDivElement>) => void) | undefined; children?
: ReactNode; ... 253 more ...; ref?: RefObject<...> | ... 2 more .
.. | undefined; }> & { ...; }'
</pre>

</details>

**Comment by aleclarson** [comment]
Fixed by fc286ea3b429d84cf20805c7ac7da4000cb00e8d (will be part of v9-rc.4)

**Comment by ElForastero** [comment]
Did someone try to pin the @types/react version?
Seems like resolutions with "/" in their names don't work with yarn.

```
    "resolutions": {
        "**/@types/react": "16.9.43"
    },
```

Would be nice to release these changes because it's impossible right now to work with RC3 without messing the codebase with `any` types.

**Comment by MeloncholyShiro** [comment]
How to fix this stuff of 9.0.0-rc-3?

**Comment by mark2685** [comment]
When will v9-rc.4 be released, @aleclarson?

**Comment by Daavidaviid** [comment]
Still having this issue

**Comment by JakeElder** [comment]
As @tbntdima says, a temporary fix until `rc.4` pr `9.0.0` is released, changing

```typescript
const { opacity } = useSpring({ opacity: 1 })
<animated.div style={{ opacity }}>{stuff}</animated.div>
```

to

```typescript
const { opacity } = useSpring({ opacity: 1 })
<animated.div style={{ opacity: opacity as any }}>{stuff}</animated.div>
```

suppresses the error.

Thanks to the dev team for this package, really great work

**Comment by devatrox** [comment]
I have 9.1.2 installed and still the same issue. The workaround is ok but not optimal.

**Comment by Okami92** [comment]
@devatrox same. Will it be finally fixed?

**Comment by joshuaellis** [comment]
Commenting on a closed issue won't revive it, if you believe you have a bug, please open a new issue and follow the template accordingly.
