### ISSUE TITLE
Using multiple values in `useTrail` fails to animate

### ISSUE THREAD

**Issue by tomdohnal** [pmndrs/react-spring#1118]
## 🐛 Bug Report

I want to animate a list of items using `opacity` and `transform: translate(...)`. However, it only animates `opacity` correctly. As for `transform: translate(...)`, it only animates the first item. It applies for other values, too. (I tried animating `opacity` and `color` and an anallogical glitch occurs.)

The very same code works just fine in v8 (just change the dependency version in the attach CodeSandbox to see it in action).

## To Reproduce

See the Link to repro section

## Expected behavior

Both values should ve animated smoothly.

## Link to repro (highly encouraged)

https://codesandbox.io/s/quizzical-pare-p6cxz

Click the "animate" button to trigger the animation

## Environment

- `react-spring` v9.0.0.-rc3
- `react` v16.12.0

**Comment by BiscuitNick** [comment]
It looks like a timing issue with the toggle variable updating after setting the new Trail values. Adding the new toggle variable before the Trail values are updated seems to work. Then set the updated toggle value.  

https://codesandbox.io/s/romantic-microservice-4gjhe?file=/src/App.js

**Comment by CodyJasonBennett** [comment]
I'm able to recreate this issue on v9.0.0-rc3, and this is fixed for v9.1.0.

[Sandbox](https://codesandbox.io/s/react-spring1118-eb18z) (broken for rc3 but works on v9.1.0, see below)

![v9](https://user-images.githubusercontent.com/23324155/111912635-8b038f00-8a38-11eb-8b88-1bbdd55b7b2d.gif)
