### ISSUE TITLE
Default props can't be overridden by inline props

### ISSUE THREAD

**Issue by tomdohnal** [pmndrs/react-spring#1123]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

## To Reproduce
1) Press the toggle button in the demo. The square animates OK.
2) Press it again -> it animates "immediately". This is expected as we set `default: { immediate: true }` in the `setStyle(...)` call.
3) Press it yet again -> it animates "immediately". This is NOT expected as we set `immediate: false` in the `setStyle(...)` call. It works as expected if we use `default: { immediate: false }` and override the "default" props. However, I think the default props should be overridden by setting specific props in the function calls.

See https://codesandbox.io/s/quirky-goodall-6z3og?file=/src/App.js

## Expected behavior

The default props should be overridden by "inline" props.

## Link to repro (highly encouraged)

https://codesandbox.io/s/quirky-goodall-6z3og?file=/src/App.js

## Environment

- `react-spring` v9.0.0.-rc3
- `react` v16.12

**Comment by lilpolymath** [comment]
Hi @tomdohnal the issue is because there are no props with the name default. 

This works fine.
```js
if (toggle) {
  setStyle({
  transform: "translateX(0px)",
  immediate: true
  });
} 
else {
  setStyle({
  transform: "translateX(200px)",
  immediate: false
  });
}
```

**Comment by tomdohnal** [comment]
I'm using the v9 (9.0.0.-rc3) version of the library which introduces the concept of `default` props.
https://aleclarson.github.io/react-spring/v9/#Default-props

**Comment by lilpolymath** [comment]
Ohh alright, my bad. I forgot you mentioned the environment you were running on.

But won't toggling the state of the default prop defeat the purpose of setting it as default?

**Comment by tomdohnal** [comment]
Yeah, you probably wouldn't use it like that in a real-life scenario :) 
However, the demo shows that if you set the `default` props within an imperative `setStyle` call and then try to override these `default` props in another `setStyle` call, it does NOT override them
