### ISSUE TITLE
useTransition in next.js pages transition

### ISSUE THREAD

**Issue by JoaoTeixeira20** [pmndrs/react-spring#1147]
Referring to this issue [(#325)](https://github.com/react-spring/react-spring/issues/325)

I wanted to know if  it's possible to do page transitions with useTransition on next.js, since i'm most used to hooks and react spring now supports it, @CosmaTrix placed a codesandbox that is no longer available and i wanted a little help because i don't even figure out how to do it since react spring transitions needs lists of content and the next.js router isn't the same as the react-router-dom i use on cra.

Fiddled on useRouter from next/router trying to figure out if there was something there to aid me and router.push.

If someone can help me and @CosmaTrix if you can repost the codesandbox i would appreciate it.

**Comment by JoaoTeixeira20** [comment]
My issue is solved here [(#699)](https://github.com/pmndrs/react-spring/issues/699)

**Comment by talentlessguy** [comment]
Should this be closed if it's solved?
