### ISSUE TITLE
Using `useTransition` to translate on X from 100% not entering properly

### ISSUE THREAD

**Issue by selrond** [pmndrs/react-spring#1153]
## 🐛 Bug Report

Off-canvas enter transition (using `useTransition`) translating along X from 100% not working:

## To Reproduce

Use this config: 

```js
    from: {
      transform: "translateX(100%)"
    },
    enter: {
      transform: "translateX(0%)"
    },
    leave: {
      transform: "translateX(100%)"
    }
```

## Expected behavior

It should work the same way as it does when going from the left

```js
    from: {
      transform: "translateX(-100%)"
    },
    enter: {
      transform: "translateX(0%)"
    },
    leave: {
      transform: "translateX(-100%)"
    }
```

(A clear and concise description of what you expected to happen.)

## Link to repro (highly encouraged)

[CodeSandbox](https://codesandbox.io/s/react-spring-dialogs-mqukl?file=/src/Dialog.tsx "react-spring dialogs - CodeSandbox")

## Environment

- `react-spring` v8.0.27
- `react` v16.13.1

**Comment by selrond** [comment]
Anything I can do to move this forward?

**Comment by ChrisBrownie55** [comment]
Is there any word on when this issue would be fixed? The workaround in the other issue (haven't tried it yet) seems quite fragile and not so great for building an animated modal library.

**Comment by selrond** [comment]
@ChrisBrownie55 which workaround are you referring to?

**Comment by ChrisBrownie55** [comment]
https://github.com/pmndrs/react-spring/issues/483#issuecomment-460051853

This one. But it doesn't work for me. I'm also working with `translateY` at `100%` so I assume the issue is still the same as `translateX`

**Comment by joshuaellis** [comment]
@selrond the only way to move this forward to is to look at v8 and try and fix the bug, no one is maintaining v8.

**Comment by selrond** [comment]
@joshuaellis can you confirm it works in v9?

**Comment by joshuaellis** [comment]
Sorry @selrond no I can't, It'd be helpful if you could give v9rc3 a go & see if the issue persists, if it does, come back and let us know and we can move this to our v9 board for you
