### ISSUE TITLE
Tree-shaking in v9

### ISSUE THREAD

**Issue by aleclarson** [pmndrs/react-spring#1158]
How does tree-shaking works in `v9`? It looks like I got the entire `@react-spring` in bundle no mater what I use. Is this expected behavior or did I miss something?

_Originally posted by @jerry84 in https://github.com/pmndrs/react-spring/issues/985#issuecomment-697275104_

OK, from my understanding `@react-spring/core` includes all the features that is possible to tree-shake before, for example `color-interpolations`. It doesn't look like it is possible anymore.

_Originally posted by @jerry84 in https://github.com/pmndrs/react-spring/issues/985#issuecomment-697288923_

**Comment by aleclarson** [comment]
I plan on adding a Webpack-based tree-shaking demo to the `v9` branch sometime soon. If anyone wants to contribute on that front, go right ahead. Then we can figure out if there's anything that needs to be fixed.

**Comment by jerry84** [comment]
> I plan on adding a Webpack-based tree-shaking demo to the `v9` branch sometime soon. If anyone wants to contribute on that front, go right ahead. Then we can figure out if there's anything that needs to be fixed.

Thanks for the response, my assumption is at least correct 😄

**Comment by jacob-alford** [comment]
What's the status of this issue?  I just upgraded to v9.0.0-rc.3, and now I'm getting this error with our Jest tests: 
`TypeError: (0 , _reactSpring.useSpring) is not a function`

We're using Create React App, with Typescript.  Any file that imports anything from react-spring, i.e. 
`import { useSring } from 'react-spring'` is effected.

**Comment by frenic** [comment]
@joshuaellis Why was this closed and marked with `wontfix`?

**Comment by joshuaellis** [comment]
@frenic because right now this isn't the priority of development, there are a fair few bugs and unification of the API to solve before that as well as updating the documentation.

However, if you're interested in working on this, then i'm happy to reopen and support you however I can? Would you like too?

**Comment by TheTrio** [comment]
I'm working on an application where this is all we use from React Spring

```jsx
const [y, setY] = useState(i * 75);
useSpring({
  y: i * 75,
  onChange(change) {
    setY(change.value.y);
  },
});
```

Do you have any idea how to make it so the entire bundle isn't included? I know it might not be feasible for you all to implement tree shaking but I assume there's a different way to do this eliminating the need for React Spring altogether.

Ideas?

**Comment by itayganor** [comment]
@joshuaellis A year later, will this ever get on the roadmap?

**Comment by joshuaellis** [comment]
Hi @itayganor, any particular reason you're asking? 😄 

Unfortunately, `react-spring` isn't well contributed too – if you look at the history it's largely myself. I'm currently working on a new docs site right now for the project whilst fixing "critical" bugs. So, my capacity is rather tapped out. It could get on the roadmap and it would be great to do that, more importantly if there was a repo / env pre-setup to explore this that would aid me getting to it sooner.

**Comment by itayganor** [comment]
@joshuaellis I see. It's a great opportunity to thank you for your contributions for this magical library.

As for why I'm asking, it's because I just upgraded my app from v8 to v9 and I noticed an increased bundle size :\
