### ISSUE TITLE
Updating duration in useSpring config part way through animation causes object to move "backward"

### ISSUE THREAD

**Issue by tbntdima** [pmndrs/react-spring#1163]
When I update the duration via `useState`, animation flickers back, not to initial value though.

I think you will understand from codesandbox example. Try to click the button, once the animation is 50% done.

[codesandbox example](https://codesandbox.io/s/elegant-hellman-uu7tp?file=/src/App.js)

**Comment by aleclarson** [comment]
Thanks for reporting! I'll try to fix it before the next release.

**Comment by tbntdima** [comment]
@aleclarson thanks for the reply, do you know if there is some workaround this, I really need this feature for my current project?

**Comment by aleclarson** [comment]
Here ya go
```ts
  const { x } = useSpring({
    from: {  x: 0  },
  });

  React.useEffect(() => {
    x.start(500, {
      config: { duration: customDuration }  
    })
  }, [x, customDuration])
```

**Comment by tbntdima** [comment]
@aleclarson this doesn't seem to be working 🤔 
And I'm not sure I understand what's happening here :D Do I not need to specify `to: { x: 500}` anymore?
Does this `x.start(500...` mean that after I click the button, there won't be any flickers?

**Comment by aleclarson** [comment]
That error appears because of hot reloading. It's fixed for the next release.

Your sandbox (with the workaround) is working for me, no jumping. 😅 

It's using the `SpringValue` API, which lets you pass the `to` prop as the first argument, but you could pass `{ to: 500, config }` instead if you find that more readable.

**Comment by tbntdima** [comment]
@aleclarson you are a lifesaver, thank you!

**Comment by tbntdima** [comment]
@aleclarson I've spotted another bug. When I switch the browser tab and then go back, the animation goes backward.

**Comment by tbntdima** [comment]
@aleclarson I found out that the new duration is set for different ranges.

Example:
initial 0, goal 100 - duration 5s

on button click
initial (let's say) 40, goal 100 - duration 5s

The second one will be faster than you would think because the range is 60 (100 - 40). 

From my point of view, the speed shouldn't change 🤔 

I could calculate the proper duration value thought by applying proportions, but the main issue here is for `loop`, when the loop starts again, duration is already different.

**Comment by aleclarson** [comment]
Can you open another issue for that question? Thanks 😁

**Comment by tbntdima** [comment]
@aleclarson I've just found out a hacky solution I guess xD

```js
  const { translate } = useSpring({
    from: { translate: 0 },
  })

  useEffect(() => {
    /** We need this useEffect for seamless transitions when changing speed */
    const startAnimation = async (): Promise<void> => {
      await translate.start(1, {
        config: {
          duration:
            slowOnHover && isHovering
              ? (1 - translate.get()) * duration * 7
              : (1 - translate.get()) * duration,
        },
        loop: {
          reset: true,
          config: { duration },
        },
      })
    }
    console.log('effect', translate.get())

    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    startAnimation()
  })
```
I didn't know that we can pass `config` into the `loop` property.

And this one helps to calculate proper `duration`: ```js 1 - translate.get()```

**Comment by joshuaellis** [comment]
@tbntdima what are you expecting to happen here?

I've forked the example so I can see the two runners side by side (one has its duration changed): https://codesandbox.io/s/modern-bush-cubzn?file=/src/App.js

As I can see spring doesn't reset to the default `transform` value, the distance is probably a percentage of time spent so it moves back a little bit to make the distances the same for the percentage of time already passed.

Are you expecting the object to stay in the same position and slow down because that would be almost like it has an easing function (in this case ease-out).

Or are you expecting the entire spring to reset? If so, do you think that makes sense to do so? 🤔

**Comment by tbntdima** [comment]
@joshuaellis I guess the issue was fixed already (haven't tested yet). 
Before when I was changing `duration`, I was expecting animation to either slow down or speed up from the current position, but instead, animation was starting over from the beginning.

**Comment by joshuaellis** [comment]
Okay, it'd be great if you could check out the link I posted above to see if that's whats expected and we could talk further.

**Comment by tbntdima** [comment]
@joshuaellis just checked the link. It seems that the issue is still there. When I click on the button, the first box flickers back a bit, instead of slowing down.

**Comment by joshuaellis** [comment]
Okay, so let's say that the box moves over 2000secs, at 1000secs (50%) you change the total duration to 4000 secs makes its current place, 1000seconds to be 25% complete. 

What you're expecting the box to stay where it is in terms of percentage of competition (in this case 50%) and take double the time to finish the last 50% in double the time?

**Comment by tbntdima** [comment]
@joshuaellis yep, sounds right for me. Not sure if its intuitive for other people, but thats what I would expect on duration change. wdyt?

**Comment by joshuaellis** [comment]
I think it would make for a more pleasing animation (no moving backwards) and probably makes more sense in terms of physics.....

@creativiii, @CodyJasonBennett what do you think?

**Comment by creativiii** [comment]
That's how I'd expect that to work!

**Comment by tbntdima** [comment]
Thanks @joshuaellis 🙂
