### ISSUE TITLE
useTransition not updating with dependancies, requires extra re-render [@react-spring/web@9.0.0-rc.3]

### ISSUE THREAD

**Issue by mayteio** [pmndrs/react-spring#1164]
## 🐛 Bug Report

I'm using the new `useTransition` to update a stack of cards (using the `children[]`) as the items. When pushing & shifting items from the array of cards though, useTransition seems to be one step behind - it won't add a card until another is pushed to the stack. Same issue with removing it.

As mentioned, it takes an extra render for the transitions to update - this is demonstrated by following the card titles in the console being added/removed and seeing what actually shows up when rendering.

If there's an immediate work around I can use too, that'd be awesome - tried to setState again to cause the extra re-render but it's not working.

## To Reproduce

[Check out this codesandbox](https://codesandbox.io/s/infallible-solomon-9cx4o?file=/src/App.tsx). Open the console and click add / shift cards to add and remove cards from the stack.

## Expected behavior

`useTransition` should fire each time the dependency array changes, updating the style props.

## Link to repro (highly encouraged)

[Check out this codesandbox demonstrating this](https://codesandbox.io/s/infallible-solomon-9cx4o?file=/src/App.tsx)

## Environment

- `react-spring` v9.0.0-rc.3 (rc4 not published yet)
- `react` v16.12.x`

**Comment by aleclarson** [comment]
The `to`, `x`, and `y` props are invalid. You want the `enter` prop.

**Comment by mayteio** [comment]
Thanks mate, that was it. I love this package, I became a patreon to support the good work!

Cheers
