### ISSUE TITLE
Now working with webpack + react reload

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/react-spring#1168]
If i change module css or template, or something, useSpring stop working.

    "webpack": "^4.44.2",
    "webpack-dev-server": "^3.11.0"
    "react-refresh": "^0.8.3",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.4.2",

```ts
import React from 'react'
import { useSpring, animated, interpolate } from 'react-spring'
import { useDrag } from 'react-use-gesture'


const Chat = () => {
  const [{ x, y }, setProps] = useSpring(() => ({ x: 0, y: 0 }))

  const bind = useDrag(({ down, movement: [mx, my] }) => {
    setProps({ x: down ? mx : 0, y: down ? my : 0 })
  })

  return <animated.div {...bind()}
    style={{
      transform: interpolate([x, y], (x, y) => `translate(${x}px, ${y}px)`)
    }}
  />
}

export default Chat
```

**Comment by mattrossman** [comment]
I am having this same issue using Create React App. This is a massive pain when working in CodeSandbox and locally, where everything else hot reloads on file changes but `useSpring` is always broken.

Here is a simple sandbox showing the issue:
https://codesandbox.io/s/g3b3t?file=/src/App.js

Make a simple change to the scene, e.g. change the background `<color />` from `'black'` to `'white'`. The scene will update the color, but the spring is frozen until you click to refresh the preview.

This happens in both v8 and v9.

**Comment by MaxmaxmaximusAWS** [comment]
I think the problem is in the imperative nature of spring-js

**Comment by mattrossman** [comment]
Supposedly it's fixed in https://github.com/pmndrs/react-spring/commit/4b8cd966d593c20f9e4dff2bac5d24d7a8c92413

But I use `@react-spring/three` which is currently broken on local builds, so I can't test this.
