### ISSUE TITLE
[BUG] onEnd handler with imperative style not working:

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [pmndrs/react-spring#1170]
"react-spring": "^8.0.27",

```ts
  const [{ x, y }, setProps] = useSpring(() => ({
    x: 0,
    y: 0,
    onEnd: () => {
      console.log('end')
    },
  }))
```

![image](https://user-images.githubusercontent.com/69426460/95052776-31acdb00-06f8-11eb-8357-d22b86cbf244.png)

**Comment by aleclarson** [comment]
No such thing as `onEnd`. You want `onRest`.
