### ISSUE TITLE
animated(View) ignores style coming from StyleSheet.create() in web

### ISSUE THREAD

**Issue by rodrigojcmello** [pmndrs/react-spring#1174]
## 🐛 Bug Report

A style coming from StyleSheet.create() and useSpring works fine on the same component in React Native (iOS and Android), but animated(View) ignores styles from StyleSheet.create() in web.

## To Reproduce

```typescript
import React, { FC } from 'react';
import { animated, useSpring } from 'react-spring';
import { StyleSheet, View } from 'react-native';

interface ButtonProps {
  height: number;
  width: number;
  borderRadius: number;
}

const AnimatedView = animated(View);

const Skeleton: FC<ButtonProps> = ({ width, height, borderRadius }) => {
  const props = useSpring({
    to: {
      left: width,
    },
    from: {
      left: width * -1,
    },
    config: {
      duration: 1200,
    },
    loop: true,
  });

  const motionProps = {
    ...props, // always works
    ...style.block, // works just in iOS/Android, this style is ignored in web
    backgroundColor: 'blue', // always works
  };

  return (
    <View
      style={{
        width,
        height,
        backgroundColor: '#f0eef0',
        borderRadius,
        overflow: 'hidden',
      }}
    >
      <AnimatedView style={motionProps}>
        <View style={{ width, height }} />
      </AnimatedView>
    </View>
  );
};

const style = StyleSheet.create({
  block: {
    backgroundColor: 'red',
  },
});

export default Skeleton;
```

## Expected behavior

Styles from StyleSheet.create() works appropriately in web

## Link to repro (highly encouraged)

https://github.com/rodrigojcmello/element-ui/blob/master/src/components/Skeleton/index.tsx

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.13.1 (or `react-native` v0.63.3)

**Comment by aleclarson** [comment]
From [the docs](https://github.com/necolas/react-native-web/blob/78174d7b487bb37d2f15c21e38a5beb2ad196da4/packages/docs/src/apis/StyleSheet/StyleSheet.stories.mdx#createstyles) of `react-native-web`

> The returned object replaces style objects with IDs.

Have you tried this?

```tsx
<AnimatedView style={[ props, style.block, {backgroundColor: 'blue'} ]}>
```

Closing as invalid, since not react-spring's fault.

**Comment by rodrigojcmello** [comment]
@aleclarson 

This doesn't work on Android/iOS or even on the web. In a normal \<View\> it should work, but in AnimatedView did not.

That would not because of the spring-react? :(

<img width="414" alt="Captura de Tela 2020-10-11 às 13 11 15" src="https://user-images.githubusercontent.com/5174526/95683768-b3eb4280-0bc3-11eb-91f7-684ffc653690.png">
<img width="1059" alt="Captura de Tela 2020-10-11 às 13 11 30" src="https://user-images.githubusercontent.com/5174526/95683776-bd74aa80-0bc3-11eb-90b0-5964ffadf50d.png">

**Comment by aleclarson** [comment]
That error indicates you might be passing an animated value to a non-animated component somewhere.

If you upload a simple repro to GitHub, I'll take a look.

**Comment by rodrigojcmello** [comment]
https://github.com/rodrigojcmello/element-ui-react-spring

**Comment by aleclarson** [comment]
https://github.com/rodrigojcmello/element-ui-react-spring/blob/dbe0d8817e83d8d602a59174f67380b096ba8cb7/src/components/Skeleton/index.tsx#L2

Your component should be importing `react-spring/native` or `@react-spring/native`.

**Comment by rodrigojcmello** [comment]
Got it, it worked. I noticed that both Animated.View (react-native) and animated(View) (react-spring) transform what the style coming from StyleSheet.create() into an inline style (in web), which in my view would not be the ideal solution, I will try to see the root cause and suggest a correction.

@aleclarson Thank you very much for your time. 👍
