### ISSUE TITLE
[9.0.0-rc.3] Render messes up the spring

### ISSUE THREAD

**Issue by dbismut** [pmndrs/react-spring#1178]
## 🐛 Bug Report

In the repro below, using 9.0.0-rc2 shows the correct behavior:

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/5003380/96372868-5463d880-1169-11eb-8a5a-535b78954e2e.gif)

Using 9.0.0-rc3 shows a glitch and a jump in the spring value:

![ezgif com-optimize](https://user-images.githubusercontent.com/5003380/96372812-064ed500-1169-11eb-8571-933f23068063.gif)

This is probably generated by the re-render triggered in the lines highlighted in the repo link below.

## Link to repro

https://codesandbox.io/s/admiring-lovelace-7me50?file=/src/index.js:362-374

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.14.0

**Comment by aleclarson** [comment]
Just checked. This is already fixed in `v9` branch 👍
