### ISSUE TITLE
Portals are mounted twice when used with useTransition

### ISSUE THREAD

**Issue by alexpuertasr** [pmndrs/react-spring#1179]
## 🐛 Bug Report

I use useTransition for a modal animation. The problem is that the component is mount twice so is calling my hook two times, this hook is taking the information from an api and for that reason I see the information blinking.

## To Reproduce

- Click on the modal button
- You will see how the content is re-render because the component is mounted two times

## Expected behavior

Only mounts once

## Link to repro (highly encouraged)

https://codesandbox.io/s/issue-with-react-spring-v8-7sptt (Issue in the version 8)
https://codesandbox.io/s/issue-with-react-spring-v9-byfb4 (Issue in the version 9)

## Environment

- `react-spring` v9.x.x
- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by aleclarson** [comment]
Portals must be wrapped with a normal element when wrapped with `useTransition`.

```diff
      {transitions(
        (values, item) =>
          item &&
+         <div>{
          ReactDOM.createPortal(
            <Window style={values}>{children}</Window>,
            document && document.body
          )
+         }</div>
       )}
```

Related to this line:
https://github.com/pmndrs/react-spring/blob/29206643f08500f929655c254410626ab1482db2/packages/core/src/hooks/useTransition.tsx#L308-L320

PR welcome, to clone portals correctly so the wrapper `div` isn't needed.

**Comment by Rohanhacker** [comment]
I am working on this one @joshuaellis

**Comment by CodyJasonBennett** [comment]
@Rohanhacker, did you find anything, or will the outlined fix suffice?

**Comment by joshuaellis** [comment]
i dunno, I'm just not sure if I would do the `ReactDOM.createPortal` like that? if you encapsulate the transition in the `createPortal` function the issue is resolved: https://codesandbox.io/s/issue-with-react-spring-v9-forked-tspdt?file=/src/Modal.jsx

**Comment by joshuaellis** [comment]
Also everything we do renders twice, I think it's just the way ReactDOM.createPortal works with mounting / unmounting and diffing... I'm inclined to leave this one 🤔

**Comment by eden-lane** [comment]
Still an issue for me in 9.4.1.
Wrapping in divs helped
