### ISSUE TITLE
TypeError: errList[Symbol.iterator] is not a function at fesErrorMonitor

### ISSUE THREAD

**Issue by KidRonee** [pmndrs/react-spring#1181]
I'm getting the error above when I'm trying to run my program. It is written in p5.js. 
Thanks in advance!

`
let symbol;
let symbolSize = 60;

function setup() {
  createCanvas(
  window.innerWidth,
  window.innerHeight
  );
  background(0);
  symbol = new Symbol(width / 2, height / 2);
  symbol.setTorandomSymbol();
}

function draw() {
  symbol.render();
}

function Symbol(x, y) {
  this.x = x;
  this.y = y;
  this.value;

  this.setTorandomSymbol = function() {
    this.value = String.fromCharCode(0x30A0 + Math.round(Math.random(0,96))
    );
  }

  this.render = function () {
    fill(0, 255, 50);
    text(this.value, this.x, this.y);
  }

}

`

**Comment by SynthEater** [comment]
did you find an answer?
