### ISSUE TITLE
Issue when installing yarn dependences for contributing

### ISSUE THREAD

**Issue by JimRhead** [pmndrs/react-spring#1182]
## 🐛 Bug Report

Hit on an issue when trying to follow the contribution guide dependencies fail to install. 

## To Reproduce

Follow the contributing guide to step three (git clone, install yarn, install dependencies).
Error shows ` Module '"../node_modules/@react-spring/core/src"' has no exported member 'FrameLoop'.`

## Expected behavior

Dependencies installed and project able to run.

**Comment by aleclarson** [comment]
The `./targets/three` package hasn't been updated to use the newest frameloop yet.

If you don't need `@react-spring/three`, you can comment out the related code in `targets/three/index.ts` and everything should build fine.

**Comment by JimRhead** [comment]
Ok cool. That looks to have fixed it. Maybe on a similar note, when I run the tests it seems to be missing another dependency.

```
import MutationObserver from '@sheerun/mutationobserver-shim';
       ~~~~~~~~~~~~~~~~
packages/core/test/setup.ts:5:9: error: No matching export for import "__raf"
```

**Comment by aleclarson** [comment]
The `yarn.lock` was outdated. Try doing `git pull` and run `yarn` again. 👍
