### ISSUE TITLE
`useTransition` does not return proper style after fast refresh triggered

### ISSUE THREAD

**Issue by lPaths** [pmndrs/react-spring#1188]
## 🐛 Bug Report

`useTransition` does not return proper style props after fast refresh(react-script v4) triggered.
I've created an issue on [react-refresh-webpack-plugin](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/243) and this issue is not come from their lib

[react-fast-refresh](https://reactnative.dev/docs/fast-refresh#fast-refresh-and-hooks)   

## To Reproduce

Here's the react spring config
```js
const transitions = useTransition(history.location, ({ pathname }) => pathname, {
    from: { opacity: 0, transform: 'translate3d(40px, 0, 0)' },
    enter: { opacity: 1, transform: 'translate3d(0, 0, 0)' },
    leave: { opacity: 0, transform: 'translate3d(-40px, 0, 0)' },
  })
```
And here's the render

```js
<Suspense fallback={<></>}>
  {transitions.map(({ key, props }) => (
    <Switch key={key} location={history.location}>
      {routes.map(({ Component, ...rest }, index) => (
        <Route
          key={index}
          {...rest}
          render={(routeProps) => (
            <animated.div style={{ ...props, width: '100%' }}>
              <Component {...routeProps} />
            </animated.div>
          )}
        />
      ))}
    </Switch>
  ))}
</Suspense>
```

After fast refresh triggered, the element animation reset to `from` state and did not move to `enter` state

## Expected behavior

After fast refresh triggered, the element should re-animate or retain current transition state at least 

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/reproduce-react-spring-issue-zj9p6?file=/src/App.js)

## Environment

- `react-spring` v8.0.27
- `react` v17.0.1

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
