### ISSUE TITLE
TypeScript complains about passing SpringValue to Vector3 props

### ISSUE THREAD

**Issue by lennerd** [pmndrs/react-spring#1205]
## 🐛 Bug Report

Responding to https://github.com/pmndrs/react-spring/issues/892#issuecomment-732447996

When using react-spring with react-three-fiber in version 9.0.0-rc3, Typescript will complain about invalid types when using `SpringValues`. As a quick fix it's possible to use `(prop as any) as T` (as seen in the codesandbox example below with `color`).

The animation is working as expected.

![image](https://user-images.githubusercontent.com/1609692/100019990-56abf900-2ddf-11eb-878f-c5bb7b3b026a.png)

## Expected behavior

Augmented components from `react-spring/three` accept both `SpringValue<T>` and `T` (`T` being Vector3 for example).

## Link to repro (highly encouraged)

https://codesandbox.io/s/recursing-bohr-xri52?file=/src/index.tsx

## Environment

- `react-spring` v9.0.0-rc3
- `react` v17.0.0

**Comment by aleclarson** [comment]
Definitely a bug. :+1:

The type of `props.scale` *should* be this..
```ts
Vector3 | FluidValue<[x: number, y: number, z: number]> | undefined
```
..since `THREE.Vector3` objects are not yet supported by `useSpring`.

**Comment by lennerd** [comment]
Okay, good to know. So, if `useSpring` is not supporting `Vector3` from `react-three-fiber` … why does the animation work as expected?

**Comment by aleclarson** [comment]
You're using an array, not a `THREE.Vector3` object.

**Comment by MaxTwentythree** [comment]
It's the same with position, btw

![image](https://user-images.githubusercontent.com/6469780/102979239-1a66d800-4506-11eb-8480-812d989b0397.png)

**Comment by joshuaellis** [comment]
You can typecast this unless you want to submit a PR to fix this.

**Comment by pooya121** [comment]
any update on this? it is a bit strange to typecast it every time

**Comment by joshuaellis** [comment]
> You can typecast this unless you want to submit a PR to fix this.

@pooya121 see my above comment ⭐
