### ISSUE TITLE
Add option to only run animation once

### ISSUE THREAD

**Issue by tomdohnal** [pmndrs/react-spring#1206]
## 🚀 Feature Proposal

I'd like to have the option to specify a prop to the animation hooks which would make sure that animation is only run once. 

## Motivation

This is useful, for example, for landing page animations where elements appear as you scroll but you don't want them to disappear after you scroll past them and then appear again if you scroll up.

It's possible to achieve this functionality using the `useEffect` hook now. (See https://codesandbox.io/s/epic-jackson-iykq2?file=/src/App.js)

Nevertheless, being able to pass a simple prop to the `useSpring` or another hook would greatly simplify it.

## Example

```javascript
const animatedStyle = useSpring({ opacity: isInView ? 1 : 0, runOnlyOnce: true })
```

**Comment by JoseNavy** [comment]
Hello! Can I give this a shot? I'm new to OS and would like to help

**Comment by aleclarson** [comment]
To support this, it would need to (1) have more people requesting it be added, and (2) be much harder to implement otherwise. If you're doing one-time animations in many places, wrap it in a custom hook and use that.

```js
export function useSpringOnce(props) {
  const fired = useRef(false)
  return useSpring({
    ...props,
    cancel: fired.current || props.cancel,
    onStart() {
      fired.current = true
      props.onStart?.()
    }
  })
}
```

**Comment by aleclarson** [comment]
To support this, it would need to (1) have more people requesting it be added, and (2) be much harder to implement otherwise. If you're doing one-time animations in many places, wrap it in a custom hook and use that.

```js
export function useSpringOnce(props) {
  const fired = React.useRef(false);
  function onStart() {
    fired.current = true;
    if (props.onStart) {
      props.onStart();
    }
  }
  const [values, set] = useSpring({ ...props, onStart }, []);
  React.useEffect(() => {
    if (!fired.current) {
      set({ ...props, onStart });
    }
  });
  return values;
}
```

**Comment by JoseNavy** [comment]
Should this not be a PR then?

**Comment by tomdohnal** [comment]
I agree with @aleclarson 
It could be included in the new docs as a recipe
