### ISSUE TITLE
useSpring(version 9):  opacity is not assignable? 

### ISSUE THREAD

**Issue by RexToCode** [pmndrs/react-spring#1215]
I upgraded to react-spring version 9, and still testing out the changes comparing to version 8 which was already implemented into my project...btw, i am using typescript for an react web-app.
There are two questions i would like to get some guidelines.  

First: opapcity
in version 8, no problem....but in version 9, after putting opacity in place (not just in useSpring, but also in useTransition...maybe other api too but haven't gone that far yet), it causes error telling me that opacity is not assignable.  Without opacity, it's fine.  I have put in below simple sample and see if there's any trick i didn't know, or mistakes made so that i couldn't apply opacity in there....
P.S.  actually...even backgroundColor, width....causes the same issue as opacity....in both with / without async 
```
const App = () => {
  const [toggle, setToggle] = useState(false)
 
  const slideSpring = useSpring({
    to: {opacity:  toggle? 0 : 1,  transform: toggle? "translate(-100%, -0%)" :  "translate(0%, 0%)"},
    config: config.wobbly
  })

  return (
    <div className="App">

      <div className="btns-holder">
        <input type="button" className="btn" value="Toggle" onClick={() => setToggle(!toggle)} />
      </div>

      <div className="contents-holder">
        <animated.div className="slide" style={slideSpring}>Slide Test</animated.div>
      </div>
    </div>
  );
};

export default App;
```

Second: async
In above sample, i haven't put props in async, it works.  But somehow, i found that it requires for async for the props in certain circumstances....
If i apply async into above sample: 
```
    to: async(next) => {
      await next ({transform: num === 1? "translate3d(100%, 100%, 0%)" : "translate3d(0%, 0%, 0%)"})
    }
```
It works too...but may i know what the appropriate / required situation for apply async are?  Or it's just simply for the use in the cases of creating "delayed animation"?

**Comment by RexToCode** [comment]
I have been trying some different ways, but none of them can get the opacity accepted to the spring..... my current priority is to get opacity and z-index into the spring.

**Comment by mrgoonie** [comment]
Can you try this:

```
  const [props, setProps, stop] = useSpring(() => ({
    to: { opacity: 0 },
  }));

  useEffect(() => {
    setProps({ opacity: toggle ? 1 : 0 });
  }, [toggle]);

  return (
    <animated.div className="slide"
      style={{ 
        opacity: props.opacity
      }}
    >Slide Test</animated.div>
  );

```

**Comment by RexToCode** [comment]
Thanks for your advice.  But I already tried the same way you suggested before, it can't go through....
I am wondering if this's a type issue for opacity (zIndex too) because it seems to me that properties that take string value is ok (eg, transform: "translate(-100%, -0%)")
here's the error message:
```
Type '{ opacity: SpringValue<number>; }' is not assignable to type '{ alignContent?: "initial" | "end" | "baseline" | "inherit" | "start" | "center" | "-moz-initial" | "revert" | "unset" | "normal" | "space-around" | "space-between" | "space-evenly" | ... 4 more ... | undefined; ... 794 more ...; matrix3d?: readonly [...] | ... 1 more ... | undefined; }'.
  Types of property 'opacity' are incompatible.
    Type 'SpringValue<number>' is not assignable to type '"initial" | "inherit" | "-moz-initial" | "revert" | "unset" | FluidValue<Globals, any> | undefined'.
      Type 'SpringValue<number>' is not assignable to type 'FluidValue<Globals, any>'.
        The types returned by 'get()' are incompatible between these types.
          Type 'number' is not assignable to type 'Globals'.  TS2322
```
Quite lost on this issue....

**Comment by RexToCode** [comment]
nevermind...found the solution that i missed from another post...it requires to downgrade the @types/react for this issue until next react-spring version is out...
