### ISSUE TITLE
useTransition: leave animation is broken

### ISSUE THREAD

**Issue by ipanic** [pmndrs/react-spring#1228]
## 🐛 Bug Report
See an example:
https://codesandbox.io/s/practical-wind-nx193?file=/src/index.js

`leave.transform` style is not animated. Removing `translate` part fix the issue.

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v16.14.0

**Comment by tomdohnal** [comment]
Change the `translate(0, 0)` to `translate(0%, 0)` on line 12 in your CodeSandbox and you'll be good to go :)
