### ISSUE TITLE
SpringValue doesn't animate between array values

### ISSUE THREAD

**Issue by mattrossman** [pmndrs/react-spring#1238]
## 🐛 Bug Report

SpringValue will animate between plain numbers (or at least, it fires `onChange` on them), but not arrays of numbers.

## To Reproduce

```js
const springArray = new SpringValue({
  from: [0],
  to: [1],
  onChange: (x) => console.log(x),
})
```

## Expected behavior

The log should show an array animating between `[0]` and `[1]`, but nothing is logged. [The docs explicitly state](https://aleclarson.github.io/react-spring/v9/#new-SpringValueprops) that arrays of numbers are valid animatable types.

By comparison, this works as expected:

```js
const springArray = new SpringValue({
  from: 0,
  to: 1,
  onChange: (x) => console.log(x),
})
```

## Link to repro (highly encouraged)

https://codesandbox.io/s/spring-value-array-bug-ev5gv?file=/src/index.js

## Environment

- `@react-spring/core` v9.0.0-rc.3
- `react` v17.0.1

**Comment by joshuaellis** [comment]
fix is ready in #1330
