### ISSUE TITLE
Cannot read property 'interpolate' of undefined in development mode in NextJS

### ISSUE THREAD

**Issue by EmilMalanczak** [pmndrs/react-spring#1249]
Hello
I'm using NextJS for SSR.

## 🐛 Bug Report

I want to animate through useSpring hook to scale up a macbook device.
In development everything works okay until I save up local changes. After reload of localhost I get this error:

![issue](https://user-images.githubusercontent.com/53233583/103456399-20bf3600-4cf6-11eb-950c-da83a80b1c48.png)

After every single change I have to manually refresh localhost page and then there is no error 

Code of animation:

![code](https://user-images.githubusercontent.com/53233583/103456469-fde15180-4cf6-11eb-92af-bb5d92194ad6.png)

I've found a workaround but it's not satisfying solution. 

![workaround](https://user-images.githubusercontent.com/53233583/103456495-4436b080-4cf7-11eb-9326-f42e959fba1e.png)

## To Reproduce

Any NextJS project with react-spring

## Expected behavior

Simply no error, it disturbs development time :/ 
Couldn't find similar issue.

## Environment

- `react-spring` v8.0.27
- `react` v17.0.1
- `next` v10.0.4

**Comment by aleclarson** [comment]
Your `matrix` variable is undefined. How is it declared?

**Comment by EmilMalanczak** [comment]
![image](https://user-images.githubusercontent.com/53233583/106924372-4d100d00-670f-11eb-8202-b348e9650f1b.png)

Like this at top of the component

**Comment by a-type** [comment]
I see this too. It appears to happen with React Fast Refresh. The problem only began after upgrading CRA.

The spring values from `useSpring` (I'm also using the functional version) become undefined after a fast refresh and are not restored until you reload the page.

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
