### ISSUE TITLE
In v9, updating state will break onChange callback

### ISSUE THREAD

**Issue by juuyan** [pmndrs/react-spring#1251]
## 🐛 Bug Report

In v9, updating state will break onChange callback.

## Link to repro

https://codesandbox.io/s/happy-morning-8gl3x?file=/src/index.js

## To Reproduce
1. scroll to the bottom. ( the btn would become white )
2. click the btn.
3. You will observe that the scroll animation stops once the btn background changes.
4. Change the react-spring version to v8.x. ( and change onChange -> onFrame )
5. Do 1 & 2 again.
6. You will observe that the scroll animation works properly.

## Expected behavior

Scroll should works properly.

## Environment

- `react-spring` v9

**Comment by joshuaellis** [comment]
Hey @juuyan!

Thanks for the report, I don't think this is a bug, it's just the `onChange` api has changed: see [here](https://react-spring.io/common/props#events).

Events excluding `onDelayEnd` and `onProps` all have the same arguments passed to them:
```
(result: AnimationResult, spring: Controller | SpringValue, item?: Item) => void
```

So instead what you want to do is `spring.get().y` which then works as intended! See your forked sandbox i've made – https://codesandbox.io/s/runtime-glitter-51ryj?file=/src/index.js
