### ISSUE TITLE
react-spring guide link on docs

### ISSUE THREAD

**Issue by bradwoods** [pmndrs/react-spring#1252]
I've made / maintain a [list of minimal code examples](https://bradwoods.io/guides/react-spring) of each react-spring concept that I know of. It was [suggested](https://github.com/pmndrs/react-spring/discussions/967#discussioncomment-271559) to put a link to this somewhere on the docs. Would people want that / where would be the best place?

**Comment by joshuaellis** [comment]
Probably better to post this in react-spring.io, but this sounds really great, so don't misunderstand me closing this issue as shooting you down 👌🏼

**Comment by bradwoods** [comment]
Hey mate, no offense taken. You raise a good point.
