### ISSUE TITLE
How to complete an animation instantly using setSpring?

### ISSUE THREAD

**Issue by Linksku** [pmndrs/react-spring#1280]
## 🤓 Question

I'm using the `useSpring` hook. Is it possible to instantly set a value using `setSpring` instead of animating it?

I'm using springs to set the relative position of elements to drag/drop them. When an element is dropped, I reorder the elements in the DOM. With relative positions, the elements would jump. I want to instantly change the spring values so the element stays at the same position.

**Comment by aleclarson** [comment]
Try `immediate: true`

**Comment by Linksku** [comment]
`immediate: true` doesn't work for me.

I tried:

      setSpring({
        top: 0,
        immediate: true,
      });

and

      setSpring({
        to: {
          top: 0,
        },
        immediate: true,
      });

**Comment by aleclarson** [comment]
What version are you using?

**Comment by Linksku** [comment]
`9.0.0-rc.3`

Should've mentioned it earlier.

**Comment by aleclarson** [comment]
Please make a sandbox that reproduces the issue, you can fork [this](https://codesandbox.io/s/react-spring-v9-template-8ebn2) if you want.
