### ISSUE TITLE
Wrapping components with animated - Property 'as' is missing in type.

### ISSUE THREAD

**Issue by einaralex** [pmndrs/react-spring#1283]
## 🐛 Bug Report

When wrapping a component in `animate`. Typescript reports an error .
```
Property 'as' is missing in type ........ but required in type 'AnimatedProps'
```

## To Reproduce

Using the animation example from `reach-ui`, wrap the reach DialogOverlay and DialogContent with animation.
See the codesandbox.

## Expected behavior

The 'as' property should be optional.

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-type-errorr-9lqo6

## Environment

- `react-spring` v9.0.0-rc.3
- `react` v17.0.1

**Comment by einaralex** [comment]
This can be bypassed by using `<animated.div>` around the components, instead of wrapping them.

**Comment by philwilliammee** [comment]
How did you find a fix to this issue?

**Comment by joshuaellis** [comment]
See https://github.com/pmndrs/react-spring/issues/1283#issuecomment-778811616
