### ISSUE TITLE
When will v9 stable be released? (maintenance)

### ISSUE THREAD

**Issue by pixelass** [pmndrs/react-spring#1287]
## 🤓 Question

 I've been using react-spring since the start and was very happy with it over the years. Thank you for providing this amazing library.

It's been close to a year since the last release. Looking through the commits we can see that several fixes have been added. **Can you estimate when a new version (maybe even stable) can be released from the current state?**

We're facing several issues with types and see quite some type-fixes since May 2020 which makes us wonder if v9-rc.3 would make any difference to us. 
We fully understand if this gets delayed but we're also unsure if we should stick to v8, try v9 or switch to another library. Our code contains quite some workarounds, patches and type-castings to make react-spring work properly (things constantly break and require quite some attention).

Is there anything we can do to support you?

BTW. We're still using v8 since  v9-rc.3 would not satisfy our expectations for an upgrade

**Comment by danielbalog** [comment]
Having lurked on this page since the beginning of the last year, I too have wondered if with all the fixes that have happened since rc3 if it is not enough for at least an rc4 already. 

Some type fixes and the production “side-effect false” bug come to mind.

**Comment by drcmda** [comment]
I agree, that one is especially annoying. @aleclarson could we move forward?

**Comment by martinhj** [comment]
Would appreciate it!

**Comment by bstro** [comment]
for whatever its worth, it would be helpful to have some signal to know whether #1078 will be addressed in the near-term, our team needs to make a decision whether to continue using react-spring or identify alternatives.

**Comment by tim-soft** [comment]
Given all the fixes/changes since the last release, I think an official rc-4 build would be greatly appreciated. I'm still on v9-beta.34 in various projects due to unreleased fixes.

I also want to make it known that I truly enjoy react-spring and appreciate all the hard work and js wizardry involved

**Comment by drcmda** [comment]
ok, we decided to move forward and will publish v9 release as it is. it's been in rc stage long enough and the current situation that it cant be used in production is no good. the workaround is not feasible in my opinion. we'll figure this out.

**Comment by dagstuan** [comment]
Is `9.0.0-rc.3` considered `latest` now? There is still issues with `rc.3` not being compatible with the latest `@types/react` (#1102).

**Comment by Daavidaviid** [comment]
Any update for the typescript issue with react types ?

**Comment by Yzrsah** [comment]
It seems targets/three `apply` was deprecated. How are you intended to extend the catalog in v9?

**Comment by joshuaellis** [comment]
Hi all, like @drcmda said, we want to push forward with a stable release you can see #1330 as that intention. We've hopefully fixed the prod issue with #1150. 

Any issues people want fixing should be first offering to fix them 😉 right now there's a lot going on, and we're stretched to the max. However, if you do need support fixing a bug, you can always ask for it ⭐
