### ISSUE TITLE
SpringValue<number[]> is not assignable to Vector3

### ISSUE THREAD

**Issue by Aslemammad** [pmndrs/react-spring#1302]
## 🐛 Bug Report

I was playing with r3f and react-spring and had a little problem (which can be solved with the `as` keyword)

```ts
  const props = useSpring({
    scale: active ? [1.5, 1.5, 1.5] : [1, 1, 1],
    color: hovered ? 'hotpink' : 'gray',
  });
  // in the return
  <mesh // or animated.mesh
      scale={props.scale} // here's the type error
  >
  // it says: Type 'SpringValue<number[]>' is not assignable to type 'Vector3'.
```
If you can guide me some about the source code, I think I may solve it and send a PR.

**Comment by joshuaellis** [comment]
There's no guide, i'd advise you to get in and get dirty 💪🏼

**Comment by Aslemammad** [comment]
Let's go for it, I'll fix it.

**Comment by CodyJasonBennett** [comment]
So, from what I understand, this is exactly a TS issue? SpringValue appears to be array-like in testing, so it should work when that's fixed.

It's just a question of treating the spring as a Vector without undermining type-safety.

**Comment by joshuaellis** [comment]
I suppose the `animated` part should be changing the types to accept `SpringValue<any>`, so where the `mesh`'s `scale` type is `Vector3` it should actually be `Vector3 | SpringValue<[number, number, number]>`.

**Comment by joshuaellis** [comment]
I think the solution to this looking `Animated` & `AnimatedArray` probably to Typecast it, how would `react-spring` know this was meant to be a `Vector3`? Else we could look at amending the `@types/three`. You could always interpolate:

```js
  const props = useSpring({
    scale: active ? [1.5, 1.5, 1.5] : [1, 1, 1],
    color: hovered ? 'hotpink' : 'gray',
  });
  <animated.mesh
      scale={props.scale.to(vals => myVector3.set(...vals))} // here's the type error
  >
```

**Comment by juanpasolano** [comment]
Just wanted to add this workaround to the conversation
I had to avoid this issue by using a single number in the spring and passing it separately. 
```javascript
  const props = useSpring({
    scale: active ? 1.5 : 1,
    color: hovered ? 'hotpink' : 'gray',
  });
  <animated.mesh
      scale-x={props.scale}
      scale-y={props.scale}
      scale-z={props.scale}
  >
```

**Comment by foufrix** [comment]
A more straightforward fix would be to comment on the code with `@ts-ignore:`you can precise on the comment that you know what you are doing for the next people

```typescript
 // @ts-ignore: Spring type is Vector3 Type
    const { position } = useSpring({
      position: clicked ? [16, 1, 16] : [0, 1, 0],
      onChange: ({ value }) => {
        vector3.set(value.position[0], value.position[1], value.position[3]);
      },
    });
    <animated.mesh position={position} ref={Pawn} onClick={handleClick} speed={0.1}>
      <coneGeometry args={[0.5, 1, 20]} />
      <meshStandardMaterial color="blue" />
    </animated.mesh>
```
