### ISSUE TITLE
Adjust the speed of one property

### ISSUE THREAD

**Issue by xblurx** [pmndrs/react-spring#1308]
Hi everybody, have a good day!

I am animating `transform` and `opacity` with `useSpring`. 
Can I adjust the speed of `opacity` property somehow, to make it transition faster than transform? 
Thank you very much, awesome library by the way!

**Comment by tomdohnal** [comment]
One possible solution that comes to my mind is to create two separate springs for each `transform` and `opacity` animation likes this:
```javascript
const transformAnimationProps = useSpring(/* configuration for `transform` */)
const opacityAnimationProps = useSpring(/* configuration for `opacity` */)

return <animated.div style={{ ...transformAnimationProps, ...opacityAnimationProps  }} />
```

**Comment by xblurx** [comment]
> One possible solution that comes to my mind is to create two separate springs for each `transform` and `opacity` animation likes this:
> 
> ```js
> const transformAnimationProps = useSpring(/* configuration for `transform` */)
> const opacityAnimationProps = useSpring(/* configuration for `opacity` */)
> 
> return <animated.div style={{ ...transformAnimationProps, ...opacityAnimationProps  }} />
> ```

yeah, thought about it too, thank you!
