### ISSUE TITLE
react-spring 10?

### ISSUE THREAD

**Issue by phaistonian** [pmndrs/react-spring#1314]
## 🤓 Question

I noticed some deprecation warnings mentioning v10.

Since 9 is still in RC state, is there a v10 underworks?

**Comment by drcmda** [comment]
no, this might be an accident. we will wrap up v9 soon, but i have no idea where these come from - will take a look.

**Comment by drcmda** [comment]
@phaistonian could you make a screenshot pls?

**Comment by phaistonian** [comment]
Will do — once this warning pops up again.

**Comment by phaistonian** [comment]
![image](https://user-images.githubusercontent.com/796530/111491819-d837e600-8744-11eb-8365-3bc20a066b68.png)

**Comment by joshuaellis** [comment]
Looks like this should probably say v9 @drcmda?

**Comment by drcmda** [comment]
oh, thank goodness, a typo

**Comment by joshuaellis** [comment]
fixed via – pmndrs/react-spring@57221435
