### ISSUE TITLE
react-spring + styled-components = Unknown Prop Warning

### ISSUE THREAD

**Issue by gormonn** [pmndrs/react-spring#1317]
## 🐛 Bug Report

When using react-spring with styled-components, props are passed to the HTML element.
And we get an [Unknown Prop Warning](https://reactjs.org/warnings/unknown-prop.html)

## To Reproduce
Just use `styled-components` with `react-spring`, like that:
```
const Main = styled(animated.div)`
  position: absolute;
  width: 100%;
  height: 100%;
  color: white;
  background-color: ${(props) => (props.bg ? 'green' : 'red')};
`
```
Then, if you pass prop `bg` into `Main`, you will have an error, like that:
```
Warning: Received `false` for a non-boolean attribute `bg`.

If you want to write it to the DOM, pass a string instead: bg="false" or bg={value.toString()}.

If you used to conditionally omit it with bg={condition && value}, pass bg={condition ? value : undefined} instead.
    in div (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in StyledComponent (created by Styled(Component))
    in Styled(Component) (at src/index.js:22)
    in App (at src/index.js:28)
```
DOM Element looks like:
```
<div id="root">
  <div theme="[object Object]" class="sc-htpNat lbLdTY">Click for change Theme</div>
  <div class="sc-bxivhb hsmRNu">Click for change Bg</div>
</div>
```

## Expected behavior

props should not be passed directly to the element.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/messagehub-forked-7936j?file=/src/index.js)

## Environment

- `react-spring` v8.x.x 
- `react-spring` 9.0.0-rc.3 too
- `react` 17.0.1
- `styled-components` 5.2.1

**Comment by tomdohnal** [comment]
This doesn't seem to be related to React Spring. Nonetheless, this is what you're probably looking for https://styled-components.com/docs/api#transient-props
(See the [CodeSandbox](https://codesandbox.io/s/messagehub-forked-p9o3p?file=/src/index.js))

**Comment by joshuaellis** [comment]
closing because as its not related to react-spring

**Comment by tomdohnal** [comment]
@joshuaellis That was my initial thought as well but if you use `styled.div` instead of `styled(animated.div)` the error disappears. 
So there actually *might* be something going on with React Spring which causes the error

**Comment by joshuaellis** [comment]
PRs are welcome otherwise it might be a while before this bug is fixed, we're pretty stretched right now.

**Comment by gormonn** [comment]
When styled-components wraps a component, it must regulate which props to pass next.

@tomdohnal thanks for the tip.
(More info) [https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c]

So this is not a react-spring issue.
