### ISSUE TITLE
Call for maintainers 📱🔥

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/react-spring#1319]
react-spring is *possibly* the most starred library in the pmndrs org. We're still trying to push v9 as a stable release.

## However, we're looking for passionate developers who regularly use the library and love it to come help maintain it.

* issues triaging
* PR reviewing
* Supporting & answering questions
* Test
* Advancing the library with the support of the community.

If you are interested, message [me](https://www.twitter.com/_josh_ellis_) or @drcmda on Twitter or Discord, or just pop in the react-spring channel and let us know so we can begin the conversation.

https://discord.gg/poimandres

**we're not expecting anyone to do this on their own, it's a huge task, everyone will support you however they can**

## What can you do if you've got some spare time and want to help a little bit?

* fix a bug! @ me and I'll assign it to you
* fix the sandboxes in demo
* add sandboxes from the `react-spring.io` site.

**Comment by CodyJasonBennett** [comment]
I'm down to help where needed.

Is there anything that needs work, specifically, like react-native, or would you prefer to go over that one-on-one?

**Comment by Aslemammad** [comment]
I'm here for that; let me take a look at the issues.

**Comment by doehyunbaek** [comment]
Hi. I'm interested but what kind / level of competence do you need? I'm willing to bring my time / passion but may not lack the skills :(. What do you expect from maintainers?

**Comment by joshuaellis** [comment]
> Hi. I'm interested but what kind / level of competence do you need? I'm willing to bring my time / passion but may not lack the skills :(. What do you expect from maintainers?

I think right now, we’re looking for anyone to pick out v9 bugs and work on them. There’s a project board set up with them all, feel free to get stuck in. When you’ve picked one, please @ me and I will assign that ticket to you.

**Comment by doehyunbaek** [comment]
> When you’ve picked one, please @ me and I will assign that ticket to you.

You mean pick a card in Needs Investigation, Todo column? I'll look into them on the weekend and if I find something I can contribute I will update you on that.

**Comment by joshuaellis** [comment]
Yes @doehyunbaek exactly that ⭐

**Comment by kirittanna** [comment]
>I think right now, we’re looking for anyone to pick out v9 bugs and work on them.

@joshuaellis sounds good, I'm in 👍🏽
