### ISSUE TITLE
v9: Tests won't finish

### ISSUE THREAD

**Issue by danielberndt** [pmndrs/react-spring#1353]
## 🐛 Bug Report

I wanted to try my luck and see whether I'd be able to fix [an issue](https://github.com/pmndrs/react-spring/issues/1149) in this repo but couldn't get the environment to run.

More specifically when running `yarn test` the tests won't finish.

when running `yarn test --testPathPattern useTransition`

this is the output:

```
yarn test --testPathPattern useTransition
yarn run v1.22.10
$ jest --testPathPattern useTransition
  console.error
    This browser does not have a MessageChannel implementation, so enqueuing tasks via await act(async () => ...) will fail. Please file an issue at https://github.com/facebook/react/issues if you encounter this warning.

      at enqueueTask (src/hooks/packages/core/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:43:15)
      at Object.then (src/hooks/packages/core/node_modules/@testing-library/react/dist/@testing-library/react.esm.js:51:7)

  console.error
    Warning: An update to null inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
        in Unknown

      at printWarning (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (src/hooks/packages/core/node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at src/hooks/packages/shared/src/hooks/useForceUpdate.ts:11:7
      at payload.onResolve (src/hooks/packages/core/src/hooks/useTransition.tsx:257:11)
      at src/hooks/packages/core/src/Controller.ts:407:30


 RUNS  packages/core/src/hooks/useTransition.test.tsx
```
##

To reproduce:

- checkout v9 branch
- yarn install
- yarn test --testPathPattern useTransition

## Environment

- `react-spring` [today's fork of v9](https://github.com/danielberndt/react-spring/tree/v9)
- `macOS` 0.15.7
- `node` v14.15.4
- `yarn` 1.22.10

**Comment by joshuaellis** [comment]
Thanks! we're actually aware this is a potential issue right now and are working hard to get It fixed. I recently added (albeit very quickly) a vite sandbox for running code that aliases the srccode of web. If you still wanna work on the issue that might be the way to go for now 🙏🏼

**Comment by Aslemammad** [comment]
Can I work on it?

**Comment by joshuaellis** [comment]
@Aslemammad, I'd liaison with brandon_mn on discord if you can, he was looking into tests too. But I don't have a preference who delivers a fix.

**Comment by Aslemammad** [comment]
> @Aslemammad, I'd liaison with brandon_mn on discord if you can, he was looking into tests too. But I don't have a preference who delivers a fix.

Ok, check it, if he can't, I'd work on it.

**Comment by skylineproject** [comment]
Sounds good, I've taken a look at this a few different ways, but I can't seem to replicate this on my machine (macOS 11.2.3 / Node v14.15.4 and v15.11.0 / Yarn 1.22.10) and it's succeeding: 

```
$ yarn test --testPathPattern useTransition
yarn run v1.22.10
$ jest --testPathPattern useTransition
 PASS  packages/core/src/hooks/useTransition.test.tsx
  useTransition
    ✓ unmounts after leave (23ms)
    when "leave" is an array
      ✓ unmounts after leave (6ms)
    when "leave" is a function
      ✓ unmounts after leave (6ms)
    when "enter" is a function
      ✓ still has its "onRest" prop called (4ms)
    when "leave" is a no-op update
      ✓ still unmounts the transition (5ms)

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        1.171s
Ran all test suites matching /useTransition/i.
✨  Done in 1.89s.
```

@Aslemammad If you can replicate this, definitely go for it -- I'm curious as to the cause but don't have a lot to go on here.

**Comment by Aslemammad** [comment]
Ok, I'll go for it.

**Comment by joshuaellis** [comment]
@skylineproject, I've found removing this from the `jest.config` gets everything running: 

```js
   moduleNameMapper: {
      '^react$': '<rootDir>/../../node_modules/react',
    },
```

But all my tests break, which confuses me more how you've got them passing. Are you able to push what you've got going to a branch somewhere so I can check it out?
