### ISSUE TITLE
v9: useTransition TypeError: Cannot destructure property 'reset' of 'props' as it is null.

### ISSUE THREAD

**Issue by ingro** [pmndrs/react-spring#1360]
## 🐛 Bug Report

I update my app with the new release and found this error, the transition was working fine on v8.x

## To Reproduce

Simply open the codesandox linked below, the error is thrown as soon as the component with `useTransition` hook is rendering

## Expected behavior

The transition was working in v8.x and looking in the changelogs for v9 I didn't found a reason that it shouldn't with the last version, maybe I'm missing something?

## Link to repro (highly encouraged)

https://codesandbox.io/s/dreamy-darkness-30c34

## Environment

- `react-spring` v9.x.x
- `react` v17.x

**Comment by joshuaellis** [comment]
RE. docs, are you sure about that? – https://aleclarson.github.io/react-spring/v9/breaking-changes/#The-useTransition-hook

RE your problem, here's a fixed version: https://codesandbox.io/s/autumn-resonance-5h5v2?file=/src/App.tsx

**Comment by ingro** [comment]
@joshuaellis sorry about that, I was referring to the official (or so I thought) site: https://www.react-spring.io/log

Thanks for your fast reply!

**Comment by joshuaellis** [comment]
> @joshuaellis sorry about that, I was referring to the official (or so I thought) site: https://www.react-spring.io/log
> 
> Thanks for your fast reply!

No worries! Glad to be of help 🌟
