### ISSUE TITLE
How to use `useChain` in v9.0.0

### ISSUE THREAD

**Issue by JakeElder** [pmndrs/react-spring#1363]
The [existing example from the docs](https://codesandbox.io/embed/2v716k56pr) no longer works.

I've tried a few variants ie using the `[_, ref]` returned from `useSpring(() => {})` in the updated api like this

```typescript
  const [s1, s1Ref] = useSpring(() => ({
    from: { opacity: 0 },
    to: { opacity: 1 },
  }));

  const [s2, s2Ref] = useSpring(() => ({
    from: { opacity: 0 },
    to: { opacity: 1 },
  }));

  useChain([s1Ref, s2Ref]);
```

This gives a type error, `Type 'SpringRef<{ opacity: number; }>' is not assignable to type 'SpringRef<Lookup<any>>'` and doesn't seem to work.

Is there an updated example or a recommended new way to chain animations?

I love `react-spring`, thank you for the work

**Comment by joshuaellis** [comment]
Can you please provide a repo of the issue you are experiencing, I'm also going to move this to a discussion because it is a question.
