### ISSUE TITLE
@react-spring/types is missing license information

### ISSUE THREAD

**Issue by vbfox** [pmndrs/react-spring#1366]
## 🐛 Bug Report

The `@react-spring/types` package doesn't have any license information specified.

## To Reproduce

Go to https://www.npmjs.com/package/@react-spring/types and check the license field.

## Expected behavior

I think the license should be specified as `MIT` like the rest of the project.

## Environment

- `react-spring` v9.0.0

**Comment by joshuaellis** [comment]
This has been added and when we release our next version it will be released at the same time. Thanks for the report.

**Comment by vovakulikov** [comment]
Hey @joshuaellis sorry to bother you with that, but do you have a date for the next release?

**Comment by joshuaellis** [comment]
> Hey @joshuaellis sorry to bother you with that, but do you have a date for the next release?

not to hand, why?
