### ISSUE TITLE
Type 'SpringRef<{ rotate: number; }>' has no call signatures.

### ISSUE THREAD

**Issue by mohammadjavad948** [pmndrs/react-spring#1369]
## 🐛 Bug Report

i want to use "useSprings" hook and when i call the set function it throws an error
this is my code

`const [springs, set] = useSprings(2, (index: number) => {
            return {rotate: index === 1 ? 0 : 180, config: config.wobbly}
 })`

and i when i call set() it throws error and say 
This expression is not callable.   Type 'SpringRef<{ rotate: number; }>' has no call signatures.

## Link to repro

[link to repo](https://github.com/mohammadjavad948/movie-sucker/blob/javad/web/src/components/Navigation.tsx)

line 9 to 35

## Environment

- `react-spring` v9.0.0
- `react` v17.0.2

**Comment by joshuaellis** [comment]
```js
const [springs, api] = useSprings(2, (index: number) => { return {rotate: index === 1 ? 0 : 180, config: config.wobbly} })

api.current[0].set()

```

**Comment by mohammadjavad948** [comment]
thanks
