### ISSUE TITLE
Parameters missing from useTransition’s onRest

### ISSUE THREAD

**Issue by jdmg94** [pmndrs/react-spring#1372]
## 🐛 Bug Report

For examples like the notification center you can find on react-spring.io the onRest callback is used to cleanup after an animation, on v8 an issue was reported where the behavior of this callback was different on useTrail (see #1131 ) this PR was rejected with the reasoning that it was fixed in v9 (months before the release of v9)  up until RC3, this was true, however the API has changed and there is no documentation that reflects the new API changes, on RC the callback for onRest for the useTransition hook had 2 passed arguments, but on the latest stable v9 the onRest callback  only passes 1 argument. Because of this examples like notification center which rely on this callback for cleanup are no longer possible.

## To Reproduce

- go to this sandbox: https://codesandbox.io/s/ecstatic-bardeen-crw15
- open the console for codesandbox
- go to codesandbox’s dependencies
- switch react-spring from v9 to v9RC1

## Expected behavior

the onRest callback is passed 2 arguments

## Link to repro (highly encouraged)

codesandbox demo: 
https://codesandbox.io/s/ecstatic-bardeen-crw15

## Environment

- `react-spring` v9 (worked on v9RC)
- `react` v17.0.2

**Comment by jdmg94** [comment]
A clearer example can be seen on the MessageHub fork presented on #1041  just switched from RC3 to v9 and watch it break: https://codesandbox.io/s/messagehub-150hm?file=/src/index.js

**Comment by joshuaellis** [comment]
> A clearer example can be seen on the MessageHub fork presented on #1041 just switched from RC3 to v9 and watch it break: https://codesandbox.io/s/messagehub-150hm?file=/src/index.js

Are you saying this is a duplicate issue?

**Comment by jdmg94** [comment]
@joshuaellis  no they’re different issues, but he forked the Messagehub to v9 which is what I was talking about in the issue description, I was pointing it out cause I didn’t re-implemented it myself but mentioned it on the description
