### ISSUE TITLE
react-spring@9.0.0 install fails with npm 7

### ISSUE THREAD

**Issue by n1ru4l** [pmndrs/react-spring#1373]
## 🐛 Bug Report

The package `@react-spring/three` has a peer dependency upon the unpublished package `@react-three/fiber`.

## To Reproduce

```
PS C:\Users\lauri\Projects\dungeon-revealer> npm install -D -E @react-spring/three @react-spring/web
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: @react-three/fiber@undefined
npm WARN node_modules/@react-three/fiber
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @react-three/fiber@">=6.0" from @react-spring/three@9.0.0
npm WARN node_modules/@react-spring/three
npm WARN   dev @react-spring/three@"*" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @react-three/fiber@>=6.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lauri\AppData\Local\npm-cache\_logs\2021-03-27T13_44_47_683Z-debug.log 

```

## Expected behavior

The packages should not depend upon an unpublished package

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v9.0.0

**Comment by joshuaellis** [comment]
Look at using @react-spring/three-v5, unless you want to use the `alpha` (although tbh it's pretty stable, imo it could be a `beta`)

@react-three/fiber@6 is being released soon we didn't want to have to publish another major version for that. Odd choice maybe, sorry for the confusion.

**Comment by n1ru4l** [comment]
```
    "@react-spring/three": "npm:@react-spring/three-v5@9.0.0",
    "@react-spring/web": "9.0.0",
```

@joshuaellis  This worked, but still, I cannot install em via `npm install react-spring`. All the examples list imports from react-spring so I am not sure how to proceed,

E.g. `useSpring` exported from `@react-spring/web` seems to have a different API than react-spring?

**Comment by joshuaellis** [comment]
> E.g. useSpring exported from @react-spring/web seems to have a different API than react-spring?

Can you share an example of this please?

**Comment by n1ru4l** [comment]
```tsx
import { animated, useSpring, to } from "@react-spring/web";

const [toolbarPosition, setToolbarPosition] = useSpring(() => ({
    position: [12, window.innerHeight - 50 - 12] as [number, number],
    snapped: true,
  }));
````

setToolbarPosition was a function `react-scripts@9.0.0-rc.3`

but in `@react-spring/web` is a an object that as a set method?

**Comment by joshuaellis** [comment]
When you destructure an array it has no name, the defacto name we used for the function was set. However it could have been anything. We’ve since changed that so the second is an object with value current where the APIs are attached. See the demos in the repo for the example.

**Comment by n1ru4l** [comment]
OKay, so the docs on the website are simply not updated, because they all imply the second array item is still the set function.

**Comment by joshuaellis** [comment]
I think I updated the link in this repo to the v9 docs, but I haven’t had time to sit and figure out the doc site, if you want to look at that for us that would be amazing. 

The v9 docs have been written I just don’t understand the build system (yet).
