### ISSUE TITLE
Using react-spring with react classes

### ISSUE THREAD

**Issue by ynhhoJ** [pmndrs/react-spring#1374]
## 🐛 Bug Report

It seems, after update to **v9** react class animations doesn't work. Or maybe i do something wrong.
In the sandboxie link, are 2 indeticall files, for using with **V9** and **V8**.

## To Reproduce

```ts
import React from "react";
import { Spring } from "react-spring";

export default class ReactSpring extends React.Component {
  render() {
    return (
      <div className="App">
        <Spring from={{ opacity: 0 }} to={{ opacity: 1 }}>
          {(props) => <div style={props}>hello from V9</div>}
        </Spring>
      </div>
    );
  }
}

```

## Expected behavior

Animation ``from`` / ``to`` should work also in V9.

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-wlrxo

## Environment

- `react-spring` v9.0.0
- `react` v17.0.2

**Comment by saviomuc** [comment]
@ynhhoJ This is not related to react classes but probably related to the new returned values from the render prop API.
I forked your repo and replaced `div` with `animated.div`. It now works https://codesandbox.io/s/react-spring-forked-q56im?file=/src/SpringV9.js

I created an issue which is related to that here: https://github.com/pmndrs/react-spring/issues/1405

**Comment by joshuaellis** [comment]
closing in favour of #1405
