### ISSUE TITLE
TypeScript: "style" is not assignable to type 'CSSProperties'.

### ISSUE THREAD

**Issue by ynhhoJ** [pmndrs/react-spring#1375]
## 🐛 Bug Report

Any CSS properties in ``from`` / ``to`` is not recognized by TypeScript as CSS style.

![image](https://user-images.githubusercontent.com/22500212/112725512-56ed0a00-8f21-11eb-9182-c38198f16473.png)

## To Reproduce

```ts
import React from 'react';
import { Spring, config } from 'react-spring';

export default class ReactSpring extends React.Component {
  render() {
    return (
      <Spring
        from={{ opacity: 0 }}
        to={{ opacity: 1 }}
        config={config.slow}
      >
        {(properties) => <div style={{ properties }}>hello</div>}
/*
TS2322: Type '{ properties: { opacity: SpringValue<number>; }; }' is not assignable to type 'CSSProperties'. 
Object literal may only specify known properties, and 'properties' does not exist in type 'CSSProperties'. 

index.d.ts(1760, 9): The expected type comes from property 'style' which is declared here on type 'DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>'
*/
      </Spring>
    );
  }
}
```

## Expected behavior
Fix type checking.

## Environment

- `react-spring` v9.0.0
- `react` v17.0.2

**Comment by pauldijou** [comment]
Shouldn't you pass the `properties` object directly to `style` instead of creating a new object with a `properties` property?

```typescript
{(properties) => <div style={ properties }>hello</div>}
```

Also, I think those are `SpringValue` and not normal CSS properties, you probably need an `animated` tag to handle them (you can import `animated` from the react-spring package).

```typescript
{(properties) => <animated.div style={ properties }>hello</div>}
```

**Comment by joshuaellis** [comment]
@pauldijou is correct, you should be wrapping the component you're passing the prop to either in `Animated` as a function or like `animated.div`.
