### ISSUE TITLE
Maximum call stack size exceeded when using timestamps in useChain

### ISSUE THREAD

**Issue by halykon** [pmndrs/react-spring#1388]
## 🐛 Bug Report

Providing timestamps as second argument in the useChain hook throws an "RangeError: Maximum callstack size exceeded" error. It's working fine without timestamps though.

## To Reproduce

1. Declare 2 refs and 2 animations using useSpring
2. call useChain and provide timestamp array as second Argument
3. see error

## Expected behavior

Animations should work with the provided timings.

## Link to repro (highly encouraged)

[Codesandbox](https://codesandbox.io/s/purple-dew-rbyy0?file=/src/App.tsx)

## Environment

- `react-spring` v9.0.0
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Related to #1367, i'm already fixing it as part of #1386.
