### ISSUE TITLE
@react-spring/three causes jank towards end of animation

### ISSUE THREAD

**Issue by neefrehman** [pmndrs/react-spring#1389]
## 🐛 Bug Report

i've just upgraded a project to use v9 and am having some janky animations with the /three package. towards the end of a spring it looks like there are multiple frames skipped. 

## To Reproduce

add a spring animation to an object in a scene

## Expected behavior

a buttery smooth animation (a la v8)

## Link to repro (highly encouraged)

https://codesandbox.io/s/epic-dhawan-js81p?file=/src/index.js

I've also include v8 in there for comparison, showing the animation running smoothly as expected.

## Environment

- `@react-spring/three` v9
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Hey @neefrehman, I actually thing you found a bug in `react-three-fiber` I couldn't tell you what it was or when it was fixed, however I can tell you that updating to the latest version has seemed to resolve it for me: https://codesandbox.io/s/elated-euclid-3v0bz if you're still having issues however, we can reopen and discuss 👍🏼

**Comment by neefrehman** [comment]
@joshuaellis I've just tried running the updated sandbox as well as updating the dependency in mine, but am seeing the same jank towards the end of the animation. Not sure where our difference could be, I've tried on multiple browsers 🤔

**Comment by joshuaellis** [comment]
You're right! damn, my eyes must have been playing tricks on me 🙃

**Comment by joshuaellis** [comment]
NOTE: this doesn't seem to happen when using a `duration` so possibly something with our `spring` calculations

**Comment by joshuaellis** [comment]
Hey @neefrehman, I've been wondering if the `precision` prop helps this bug – https://codesandbox.io/s/happy-sea-y18m1?file=/src/index.js

For context, we use precision to define how close to the value do we get before we consider it "the value", this is only really used in `spring` animations (not with duration).

To me, I can't see the jank, and this could be something we document as a suggestion to people as I don't think we really wanna change a default because it would be considered a breaking change. 

Interested to hear what you think though.

**Comment by neefrehman** [comment]
@joshuaellis to me that works also! I had absolutely no idea about that property. Does that mean that the default for it was changed in v9?

Agree that changing it again could be considered a breaking change, but I would also consider the current behaviour to be broken. So perhaps documenting the suggestion as you say, and then waiting until the next major to add the fix alongside could be a good idea? From how quiet this issue has been it doesn't seem to be a high priority thing to fix, so i guess there's no rush :)

**Comment by joshuaellis** [comment]
>@joshuaellis to me that works also! I had absolutely no idea about that property. Does that mean that the default for it was changed in v9?

that's great to hear.

I'll have to investigate further but supposedly the default has not changed, but the code is a bit different, so whether or not that's true i'm not sure...

Anyway, i've updated the documentation to reflect the information on precision and added a guide section for `r3f`. If you have any tips, feel free to contribute 😄
