### ISSUE TITLE
Ref's not work or work not corrected (v9.0)

### ISSUE THREAD

**Issue by Luchanso** [pmndrs/react-spring#1392]
## 🐛 Bug Report

Ref not passed or passed not correctly in useSpring hook

## To Reproduce

Put ref in useSpring and ref not updated after putting, and animation starting like without ref

## Expected behavior

Ref updated after passing in useSpring, and animation not started

## Link to reproduction
[CodeSandbox demo](https://codesandbox.io/s/ecstatic-moore-hffmd?file=/src/App.js) 

## Environment

- `react-spring` v9.0.0
- `react` v16.13.1, 17.0.2
- the same problem in react-native v40.0.1

**Comment by joshuaellis** [comment]
You should be using `useSpringRef` Instead of React’s `useRef` 😄 just pass the whole ref, not `.current`

**Comment by Luchanso** [comment]
Hah, thanks, I don't found this in documentation, maybe you have actual API reference?

**Comment by joshuaellis** [comment]
We're working on moving all the old examples up to v9 (whilst fixing a few bugs) you can see the progress here: #1386. But because of a bug in `useChain`, I can't post that example here (it would break). However, here's a snippet.

```js
  const springApi = useSpringRef()
  const { size, ...rest } = useSpring({
    ref: springApi,
    config: config.stiff,
    from: { size: '20%', background: 'hotpink' },
    to: {
      size: '20%',
      background: 'hotpink',
    },
  })
```
