### ISSUE TITLE
📖 DOCUMENTATION 📖

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/react-spring#1398]
We're aware the documentation is outdated.

You can track and contribute to the updates here https://github.com/pmndrs/react-spring.io/pull/49. Any help will be hugely appreciated.

In the meatime I advise you look at this https://aleclarson.github.io/react-spring/v9/ as its pretty comprehensive.

I will be closing any issues about documentation and referring to this issue in the meantime to reduce the amount of times I repeat myself.

**Comment by melloc01** [comment]
This example is not working in v9

https://aleclarson.github.io/react-spring/v9/#Dependency-arrays

![image](https://user-images.githubusercontent.com/4994258/113777370-5d3d6c00-9701-11eb-8be2-664041f5a354.png)

Correct usage would be `animate.start()`?

**Comment by joshuaellis** [comment]
yep!

**Comment by sanzhardanybayev** [comment]
Hope it gets updated soon. Love this library

**Comment by sanbornhilland** [comment]
I'm not completely clear but it seems to me that the new render props API breaks the `innerText` [example](https://www.react-spring.io/docs/props/spring) because the render props callback no longer provides a raw value. Is there a way to accomplish the same thing in v9?
