### ISSUE TITLE
Render prop API in V9 does not work as described in documentation

### ISSUE THREAD

**Issue by saviomuc** [pmndrs/react-spring#1405]
## 🐛 Bug Report

Render props previously (`v8.0.27`) would return a `number` primitive. As of v9 a `SpringValue` object is returned. To work with this value the component receiving the `SpringValue` object needs to be wrapped in an `animated` factory / HOC. This is unfortunately not documented. And I could also not find information in the v9 guide.

```javascript
//v8
<Spring from={{ value: 0 }} to={{ value: 1 }}>
        {({ value }) => (
          <MyComponent value={value}  />
        )}
</Spring>


//v9
const AnimatedMyComponent = animated(MyComponent);

<Spring from={{ value: 0 }} to={{ value: 1 }}>
        {({ value }) => (
          <AnimatedMyComponent value={value}  />
        )}
</Spring>
```

## Suggestion
Add this case to the `v9` documentation.

## Link to repro

- V8: https://codesandbox.io/s/react-spring-render-props-v8027-evzlu
- V9: https://codesandbox.io/s/react-spring-render-props-v900-v8uhg

## Environment
- `react-spring` v9.0.0

**Comment by joshuaellis** [comment]
Thanks @saviomuc, I'm working on updating the docs over in `react-spring.io`, i'll make sure I add this to it.

**Comment by joshuaellis** [comment]
I believe this has been added to `react-spring.io`
