### ISSUE TITLE
Decay animation jumps at the last frame

### ISSUE THREAD

**Issue by sahil87** [pmndrs/react-spring#1437]
## 🐛 Bug Report

When a decay animation ends, in the last frame the value resets to "to". The decay animation isn't supposed to use "to" though.
Reference: https://github.com/pmndrs/react-spring/issues/887#issuecomment-823856024
Probably happens because of [this](https://github.com/pmndrs/react-spring/blob/f2170a39111debbca52d0cf233e2f7c43a851b77/packages/core/src/SpringValue.ts#L340) (no decay animation check).

## To Reproduce

[This](https://codesandbox.io/s/decay-v901-jump-cvwgi) is a sandbox that replicates the issue.
![simplescreenrecorder-2021-04-21_14 15 22](https://user-images.githubusercontent.com/9037064/115524889-36a83500-a2ac-11eb-96c9-62f8758d0cb7.gif)

## Expected behavior

No jump at the end of the decay animation

## Link to repro (highly encouraged)

https://codesandbox.io/s/decay-v901-jump-cvwgi

## Environment

- `react-spring` v9.0.1

**Comment by joshuaellis** [comment]
I'm looking at this in conjunction with #1026

**Comment by sahil87** [comment]
Looking forward to the fix. 
"decay" animation fills up a large void of the animations generally needed apart from physics-based spring animation.

**Comment by joshuaellis** [comment]
This has been released on `9.2.0-beta.0` if you could try it that would be great ⭐

**Comment by sahil87** [comment]
Yes, this fixes it. Thank you! 😄
