### ISSUE TITLE
AnimatedFoo = animated(Foo) doesn't work -- or how to animate a Component?

### ISSUE THREAD

**Issue by nonopolarity** [pmndrs/react-spring#1438]
## 🤓 Question

In Basics:

https://react-spring.io/basics

```js
const AnimatedDonut = animated(Donut)
```
because I think `<animated.div>` can work, but `<animated.Donut>` doesn't work.

So I tried:

https://codesandbox.io/s/weathered-breeze-ghdse

```jsx

const AnimatedFoo = animated(Foo);
// ....

return <AnimatedFoo style={props}>I will fade in</AnimatedFoo>;
```
but it doesn't animated.  Is it supposed to be the way it works?

**Comment by joshuaellis** [comment]
you're using Animated as a HOC, but you're not passing the props to the root element. So no, it won't animate. It can't without the props.
