### ISSUE TITLE
TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by pk936** [pmndrs/react-spring#1447]
I am using React native with React Spring in android simulator. I got the error TypeError: Attempted to assign to readonly property. on line **AnimatedView style={transform}**

```
import React, { useState } from 'react';
import {
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { Spring, animated, useSpring } from '@react-spring/native'

const AnimatedView = animated(View)

const App = () => {
  const { transform } = useSpring({
    opacity: 0,
    transform: `perspective(600px) rotateX(${180}deg)`,
    config: { mass: 5, tension: 500, friction: 80 },
  });

  return (
    <>
      <AnimatedView style={transform}>
        <Text>Hi</Text>
      </AnimatedView>
    </>
  )
};

```

**Comment by joshuaellis** [comment]
Doesn't `react-native` styling of components have the same format as regular react, for example it would be:
```js
const App = () => {
  const { transform } = useSpring({
    opacity: 0,
    transform: `perspective(600px) rotateX(${180}deg)`,
    config: { mass: 5, tension: 500, friction: 80 },
  });

  return (
    <>
      <AnimatedView style={{ transform }}>
        <Text>Hi</Text>
      </AnimatedView>
    </>
  )
};
```

**Comment by pk936** [comment]
ok.. I think this removed the error. But after this, it says TypeError: obj.forEach is not a function. (In 'obj.forEach(fn)', 'obj.forEach' is undefined). 

Do I need to wrap **AnimateView** inside a View or vice-versa ?

**Comment by joshuaellis** [comment]
Can you post a screenshot of the error? To answer your question, no i dont think you should have to do that.

**Comment by pk936** [comment]
![screenshot-2021-04-22_22 27 03 604](https://user-images.githubusercontent.com/28622041/115754523-e61efd80-a3b9-11eb-937d-a84ee3c5553e.png)

**Comment by pk936** [comment]
![screenshot-2021-04-22_22 27 03 604](https://user-images.githubusercontent.com/28622041/115754712-1cf51380-a3ba-11eb-98e1-5d81e5ea507a.png)

**Comment by pk936** [comment]
When I removed **style** property from **AnimateView**, the obj.forEach error is gone.

```
<AnimatedView>
        <Text>Hi</Text>
      </AnimatedView>
```

**Comment by joshuaellis** [comment]
From your error screenshot it doesn't look like a `spring` error. I'm going to need a repo to debug this, are you able to share one?

**Comment by pk936** [comment]
Here is my code:


[https://codesandbox.io/s/react-spring-with-ract-native-tsegl](https://codesandbox.io/s/react-spring-with-ract-native-tsegl)

**Comment by joshuaellis** [comment]
So I did some research, transforms arent handled the same way in `react-native` as they are in the `dom`, see here – https://reactnative.dev/docs/transforms 

So to solve your problem, i'd probably just do this as it's the easiest way – https://codesandbox.io/s/react-spring-with-ract-native-forked-tx83z?file=/src/App.js

**Comment by joker-777** [comment]
@joshuaellis I get the same error when using `useTransition`. The style object has a transform field with a `_SpringValue`. It raises an error because it isn't an array.

![Screenshot_20231211_002658](https://github.com/pmndrs/react-spring/assets/378859/569227f3-4ce6-4017-84f9-506f9ca59bb7)

It raises a different error when I make it an error like this `<animated.View style={{transform: [style.transform]}}>`.

![Screenshot_20231211_003228](https://github.com/pmndrs/react-spring/assets/378859/a44cf979-c94e-491e-a08d-a0deda8d4011)
