### ISSUE TITLE
CSS Filter Grayscale Bugs

### ISSUE THREAD

**Issue by amadeus** [pmndrs/react-spring#1452]
## 🐛 Bug Report
Found a few bugs related to react-spring and animating css filters. I've built a small codesandbox that shows the issue.

## To Reproduce
* Mount a component with an animated CSS filter for grayscale, but start it at `100%`
* Both `useSpring` and the `Spring` component will initialize with no grayscale filter (the item should be fully greyscale at a value of `100%`)
* If you perform an animation to have it animate that property a couple additional things will happen, depending on whether you are using `useSpring` or `Spring`.
  * `useSpring` will not animate the prop at all - it will just toggle to the final value around when the animation should finish
  * `Spring` will be slightly glitched on the first animation since it ends up trying to start from `100%`, but after that first animation it should work fine

## Expected behavior
Animating `grayscale` should both animate and initialize at the proper value on both `useSpring` and `Spring`

## Link to repro (highly encouraged)
https://codesandbox.io/s/xenodochial-water-3otuy?file=/src/App.tsx

## Environment

- `react-spring` v9.1.1
- `react` v17

**Comment by joshuaellis** [comment]
Yeah, it looks like the filter is being changed to something odd, if you do:

```js
const { filter } = useSpring({
    config: SPRING_CONFIG,
    filter: `grayscale(${100 - value * 100}%)`,
    backgroundColor: value === 0 ? "red" : "blue"
  })

console.log(filter.get())
```
you see `rgba(128, 128, 128, 1)scale(100%)`... If you're after a quick fix, I encourage you too look at creating a PR.
