### ISSUE TITLE
Facing memory leak on the server when using React Spring's useSpring hook

### ISSUE THREAD

**Issue by thebedroomprogrammer** [pmndrs/react-spring#1456]
## 🐛 Bug Report

React Spring's useSpring is leaking memory when used on server. For every request that renders a react page that uses useSpring hook I can see Array, Controller and AnimatedValue objects increasing in memory size upto a point where the whole server crashes in the stress test. I am attaching the heap dump and it's screen shot below.

## To Reproduce

Go to the root folder of the project and install all the deps
run `yarn build:local` in a terminal window
run `yarn serve:local` in a terminal window

use `ab -n 2000 -c 2  http://localhost:3000/`

to send huge traffic to the server.

Either take the heap dump or see the memory memory status printed in the console.

## Expected behavior

I expect the memory to be reclaimed by the GC to restore normal operations of the server

## Link to repro (highly encouraged)

https://github.com/thebedroomprogrammer/react-spring-debug

## Environment

- `react-spring` v8.0.27
- `react` v17.0.2 

![image](https://user-images.githubusercontent.com/20200740/115951878-b62e4200-a500-11eb-87ba-7baab609dd04.png)

[Heap dump](https://drive.google.com/file/d/1WoKqli-zQwgtzQLZ1gaVnQaP7gwvD4ln/view?usp=sharing)

**Comment by joshuaellis** [comment]
Unfortunately, development efforts on v8 have been frozen. There are 2 ways to proceed: 
1. There is a v8 branch, you're welcome to submit a PR that resolves the issue and we can release it assuming the fix can be verified.
2. Update to v9 because AFAIK this issue has been resolved, or at least in projects I've used it in with SSR there hasn't been a memory leak...

**Comment by thebedroomprogrammer** [comment]
Cool, let me move to v9 and check if the issue is gone. Would happily switch to v9 to save myself from production crashes 😛 . Thanks mate.

**Comment by joshuaellis** [comment]
Lets close this, if it becomes an issue in v9, we can reopen with a new bug report 😄
