### ISSUE TITLE
Memory leak in react-spring v9 when used with SSR

### ISSUE THREAD

**Issue by thebedroomprogrammer** [pmndrs/react-spring#1457]
## 🐛 Bug Report

React Spring's useSpring is leaking memory when used on server. For every request that renders a react page that uses useSpring hook I can see an approximate increase in 10000 lines of compile code, string and array getting increased in the same proportion.

## To Reproduce

Go to the root folder of the project and install all the deps
run `yarn build:local` in a terminal window
run `yarn serve:local` in a terminal window

use `ab -n 10000 -c 2  http://localhost:3000/`

to send huge traffic to the server.

Either take the heap dump or see the memory memory status printed in the console.

## Expected behavior

I expect the memory to be reclaimed by the GC to restore normal operations of the server

## Link to repro (highly encouraged)

https://github.com/thebedroomprogrammer/react-spring-debug

## Environment

- `react-spring` v9.1.2
- `react` v17.0.2 

![Screenshot 2021-04-24 at 4 57 01 PM](https://user-images.githubusercontent.com/20200740/115957101-3616d500-a51e-11eb-983a-22898a9abf7c.png)

**Comment by joshuaellis** [comment]
Hm this is a cause for concern, I will admit this is a bit out of my depth. I can see the memory increasing, I can see that between snapshots 10000 of xyz are created, should I not be able to see them?

Basically I'm not sure how to debug & solve this. What's your thoughts? If you're happy to take a look at it yourself, I'll support you however I can. Alternatively, lets keep talking about it.

**Comment by thebedroomprogrammer** [comment]
Truthfully this is my first time seeing something like this in production. I don't have in depth knowledge about the internals and how things are working under the hood, but seeing memory increase when benchmarking caught my attention and so I reported the bug. 

I would surely look into it but any help with someone with experience with handling these things would be of great help.

**Comment by joshuaellis** [comment]
I guess we'll just have to hope someone comes along and helps 😅

**Comment by thebedroomprogrammer** [comment]
Important update: I think I have found the issue and it is with node. The issue was present when I was using Node v10.16.0, but the issue was gone when I started using Node v12.16.2. I think I should update my Node servers version and close the issue.

**Comment by joshuaellis** [comment]
Oh that's fantastic. Please do if it's solved.

**Comment by thebedroomprogrammer** [comment]
Reopening the issue because it is still there I ran multiple tests again and the issue persists with node v12 too

**Comment by joshuaellis** [comment]
The demo you provided is v8, moving to v9 drastically improves the memory usage server-side. And it only really seems to go up by 3mb for 10000 requests. So this isn't as bad as I originally thought and I don't really think it's a development priority... thoughts?

**Comment by thebedroomprogrammer** [comment]
Yes, but long running servers might face performance degradation overtime due to the memory bloat.

**Comment by joshuaellis** [comment]
> Yes, but long running servers might face performance degradation overtime due to the memory bloat.

You're right, they might, but unfortunately I a. don't have the knowledge, and b. the time to fix an issue like this right now, it'll have to sit on the back burner.

**Comment by joshuaellis** [comment]
> I'm also facing this issue in **Next.js v10** using **React Spring v9.1.2** on **Node v15**
> 
> ![Image 2021-05-11 at 3 12 20 PM](https://user-images.githubusercontent.com/6914518/117891219-61622980-b26b-11eb-82bc-13efd4928b9b.jpg)

Please provide a codesandbox for us to look at, screenshots can't be debugged 😄

**Comment by drmzio** [comment]
@joshuaellis I was following [this docs example](https://react-spring.io/hooks/use-transition#toggle-between-components), but React Spring tries calling the `onReset` callback when the component has already been unmounted (user navigates away from the Next.js page).

Demo: https://codesandbox.io/embed/magical-field-k7vg9?fontsize=14&hidenavigation=1&theme=dark
(Navigate between the Next.js pages)

I found a quick workaround for this by using a ref instead of state:
```jsx
const toggle = useRef(false);
...
onReset: () => { toggle.current = !toggle.current }
```

**Comment by chrissantamaria** [comment]
Did a bit of digging into @thebedroomprogrammer's example, ended up finding similar results to @joshuaellis. Bumping to react-spring v9 (specifically 9.2.3) dramatically helped so I did all of my testing with that.

My benchmark procedure was:

1. Start the server (`yarn serve:local`), should already run with `--inspect`
2. Open Chrome DevTools (`chrome://inspect`), select the Node process and navigate to Memory for heap snapshotting
2. Remove the `setInterval` logger in `src/index.tsx` (no longer needed)
3. Restart the server and monitor the total memory usage. Seems like there's some upfront garbage collecting going on so I waited for that to plateau before taking my first snapshot
4. Run a stress test (`ab -n 10000 -c 2 http://localhost:3000/`), take a snapshot immediately after
5. Wait 1 minute for garbage collecting to do some cleanup, then take a final snapshot

All testing was done on Node v14.17.0. These were my results:

| State           | Usage  | Diff    |
| --------------- | ------ | ------- |
| Start           | 8.5 MB |         |
| Post stress     | 9.8 MB | +1.3 MB |
| Post stress +1m | 9.4 MB | +0.9 MB |

This already seems negligible, but I was curious how much of this was actually react-spring related. I removed any react-spring references (swapped out `animated.div` for a vanilla `div`) and got these results:

| State           | Usage  | Diff    |
| --------------- | ------ | ------- |
| Start           | 5.4 MB |         |
| Post stress     | 6.4 MB | +1.0 MB |
| Post stress +1m | 6.1 MB | +0.7 MB |

Given that, I'd say this isn't worth investigating unless there's a larger scale example repo that exaggerates the problem.

**Comment by joshuaellis** [comment]
Thanks for the investigation!! No one else has really raised an issue, so I am going to close this. But we can always reopen and take another look if needs be.

**Comment by jackhkmatthewsBB** [comment]
> @joshuaellis I was following [this docs example](https://react-spring.io/hooks/use-transition#toggle-between-components), but React Spring tries calling the `onReset` callback when the component has already been unmounted (user navigates away from the Next.js page).
> 
> Demo: https://codesandbox.io/embed/magical-field-k7vg9?fontsize=14&hidenavigation=1&theme=dark (Navigate between the Next.js pages)
> 
> I found a quick workaround for this by using a ref instead of state:
> 
> ```js
> const toggle = useRef(false);
> ...
> onReset: () => { toggle.current = !toggle.current }
> ```

Thanks @joshuaellis , I had the same issue, `onRest: () => setState()` being called after a component was unmounted. I ended up using a ref to track if the component was mounted or not:

```ts
  const [foo, setFoo] = useState(false)
  const mounted = useRef(true)
  const styles = useSpring({
    onRest: () => {
      if (mounted.current) setFoo(true)
    }
  })

  useEffect(() => {
    return () => {
      mounted.current = false
    }
  }, [mounted.current])
```
