### ISSUE TITLE
[chore] Recrawl doesn't run on Windows

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/react-spring#1459]
## 🚀 Feature Proposal

The [`recrawl`](https://github.com/aleclarson/recrawl) library doesn't actually run on windows, and that's not good for potential maintainers who use windows as they can't build or run tests.

To counteract this, I propose we move to [`fdir`](https://github.com/thecodrr/fdir) which AFAIK supports windows and Unix machines.

**Comment by CodyJasonBennett** [comment]
Although recrawl has [promised Windows support with v2.0.1](https://github.com/aleclarson/recrawl/releases/tag/v2.0.1), it still doesn't parse paths right (same issue on latest). It's not sanitizing Windows' path separator (backslash) for its regex.

I think we go with your proposal, and I'll report this issue to recrawl in case we don't have to migrate.

**Comment by joshuaellis** [comment]
@CodyJasonBennett if it doesn't parse paths, does that mean it doesn *actually* work on windows? 😅

**Comment by CodyJasonBennett** [comment]
Yes. Maybe support means thoughts and prayers more than whether it works.

**Comment by CodyJasonBennett** [comment]
It looks like [build-if-changed](https://npmjs.com/build-if-changed) also uses recrawl, with the same issues.

I think we'll have to wait until Windows is better supported.

**Comment by joshuaellis** [comment]
We were looking at getting rid of `bic` and `lerna` and replacing with `preconstruct` over on #1379 🤔 might be time to push some effort that way....

**Comment by joshuaellis** [comment]
@CodyJasonBennett if you try and use `beta` hopefully you should be able to run everything on windows. Would you be able to test and confirm?

**Comment by CodyJasonBennett** [comment]
@joshuaellis, looking over this now. I'll have to check out some stuff on my end, as I'm immediately getting: `EPERM: operation not permitted, symlink` ([full stack-trace](https://cdn.discordapp.com/attachments/525294361391398932/836704625267965972/trace.PNG)).

I'll have to ensure that everything is fine as far as my filesystem and permissions before looking much further.

**Comment by joshuaellis** [comment]
Have you seen this? https://github.com/preconstruct/preconstruct/issues/381#issuecomment-793134511

If this fixes, would you be able to add a small section to the contributing doc about this?

**Comment by CodyJasonBennett** [comment]
@joshuaellis, I'm rolling back my changes now, and it seems that is all is needed to get this running.

I'll add a note about this.
