### ISSUE TITLE
`velocity` value in `config` behaves very strangely after updating to v9.1.2

### ISSUE THREAD

**Issue by swashata** [pmndrs/react-spring#1470]
## 🐛 Bug Report

With version 8, I had fiddled with the value of `velocity` in `config` with expected results. However, after I upgraded to v9 it become really weird. It is better if I show it, rather than trying to explain. So please follow me along.

## To Reproduce

- Add `velocity` to any of the preset `config`.

## Expected behavior

- Should behave same as v8.

## Link to repro (highly encouraged)

- Go to https://codesandbox.io/s/zen-fog-sb0v8?file=/src/TransitionToggle.js
- Have Show Weirdness checked.
- Toggle the component by pressing the "TOGGLE VISIBILITY" button and see the weirdness.

Now see the same behavior in v8 here https://codesandbox.io/s/clever-antonelli-r8hx4?file=/src/TransitionToggle.js

## Environment

- `react-spring` v9.1.2
- `react` v17.0.2

**Comment by joshuaellis** [comment]
It shouldn't work as v8, thats why this is v9.

However, I do agree it should probably be documented. I think this is an issue [here](https://github.com/pmndrs/react-spring.io/issues/62). It's a relatively straight forward amend to make to the documentation, just no one has come forward to do it whilst I havent found the time yet.

If you want to amend the documentation that'd be great!
