### ISSUE TITLE
[tests] E2E tests for Parallax

### ISSUE THREAD

**Issue by joshuaellis** [pmndrs/react-spring#1474]
## 🚀 Feature Proposal

As part as our going endeavour to be confident in our updates to `react-spring`, we're missing tests for our Parallax package. I don't think `jest` will suffice on this, although i'm happy to be told i'm wrong, I was thinking E2E tests with `cypress` namely using `@testing-library/cypress` because I like the principals of `testing-library`.

## Motivation

We need more confidence when making changes to the `parallax` package.

**Comment by kindoflew** [comment]
I think you're right about `jest` not cutting it. As far as I can tell, you can't really test scrolling in `jsdom`. `cypress` seems like a good way to go and you get the nice little GUI to figure out what happened when we break stuff. I'll look into it more this week.

**Comment by kindoflew** [comment]
@joshuaellis, quick question: should I make a new demo app for testing purposes or just use the sandbox demos? I figured a new one would be good for future-proofing as we could more easily alter it for new tests, but I wanted to check first.

**Comment by joshuaellis** [comment]
Happy to take your lead on it! I think you're right having something dedicated is probably the best thing to do!
