### ISSUE TITLE
className doesnt work on useTransition

### ISSUE THREAD

**Issue by mohammadjavad948** [pmndrs/react-spring#1477]
## 🐛 Bug Report

i use css modules and used transition hook but none of the elements inside `a.div` gets class in browser

## Expected behavior

add classes to elemnt

## Environment

- `react-spring` v9.1.2
- `react` v17

**Comment by joshuaellis** [comment]
You haven't followed the bug report template, please add a reproduction of this bug otherwise it will be closed without investigation.

**Comment by mohammadjavad948** [comment]
[repo link](https://github.com/mohammadjavad948/tic-tac-toe/blob/main/web/src/RoomSelection.tsx)

from line 96 
i used animated and then added class to it but in the browser the classes doesnt appear
so i used style right now

**Comment by joshuaellis** [comment]
This isn't a problem with `react-spring` you haven't use `@material/ui` correctly to apply the classes – https://material-ui.com/api/card/

**Comment by mohammadjavad948** [comment]
thanks !
