### ISSUE TITLE
Incorrect license under /packages/*

### ISSUE THREAD

**Issue by alexandernanberg** [pmndrs/react-spring#1479]
## 🐛 Bug Report

I don't think the license should be to Facebook right? Maybe the LICENSE could be symlinked to the root LICENSE
https://github.com/pmndrs/react-spring/blob/beta/packages/react-spring/LICENSE

**Comment by joshuaellis** [comment]
Woops, you're right. Thanks!

**Comment by joshuaellis** [comment]
This will be released in the next beta // version
