### ISSUE TITLE
className doesnt work for animated.div

### ISSUE THREAD

**Issue by mohammadjavad948** [pmndrs/react-spring#1486]
## 🐛 Bug Report

So im using transition hook to animate a list. i created a css module and import it to react component then assign it to className of the `animated.div` and in the browser nothing happens and there is no class on the element

also it works perfectly for other elements but for the animated ones it doesnt work

## Expected behavior

add class to the element

## Link to repro

 [Repo link](https://github.com/mohammadjavad948/tic-tac-toe/blob/main/web/src/Game.tsx) 

line 102

## Environment

- `react-spring` v9.1.2
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Hi there, would you be able to recreate this in a codesandbox? It's much quicker and easier for someone to investigate this and give you a solution as opposed to having the clone a whole repo. It also reduces the noise we have to sift through.

**Comment by mohammadjavad948** [comment]
Hi. yeah i will do it

**Comment by mohammadjavad948** [comment]
so i find out whats going on

my component was getting a prop called style and i had a variable that imported the stylesheet also called style
and they made this bug LOL
so i renamed it and it works fine
