### ISSUE TITLE
easing behaves differently between v8.0.27 and v9.1.2 for useTrail

### ISSUE THREAD

**Issue by wangbigmountain** [pmndrs/react-spring#1489]
## 🐛 Bug Report

I am using useTrail to animation an array of content. After I upgraded to v9.1.2, the animation with easing looks different.

## To Reproduce
I listed two links of sandbox to demonstrate it.
v8.0.27: https://codesandbox.io/s/hungry-mcnulty-tq4f9?file=/src/App.tsx
v9.1.2:    https://codesandbox.io/s/falling-http-vptc2?file=/src/App.tsx

## Expected behavior

I would like to keep the animation in v8.0.27

## Link to repro (highly encouraged)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v9.1.2
- `react` v17.0.1

**Comment by joshuaellis** [comment]
v9 is breaking changes, I don't think you can argue this is a bug. You will have to change the spring settings in accordance with the v9 set up, if you find a bug doing say, please feel free to reach out.

**Comment by wangbigmountain** [comment]
Hi @joshuaellis , is there any proper guide for upgrading useTrail with easing to V9?

**Comment by joshuaellis** [comment]
We haven't specifically released upgrade guides. However the documentation does try to highlight certain areas where v9 is very different from v8. You should check it out and if you think you can add to it, feel free to make a PR
