### ISSUE TITLE
React 17 support in peer deps with beta version

### ISSUE THREAD

**Issue by Dataxelio** [pmndrs/react-spring#1502]
## 🐛 Bug Report

Hello,
I'm encountering the same issue as this one #1478 but the v9.2.0-beta.3 doesn't fix it for me.
I'm using React 17.0.2.
I have below error message when run `npm install react-spring@9.2.0-beta.3`.

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^16.9.0 || ^17" from @next/react-dev-overlay@10.2.0
npm ERR!   node_modules/@next/react-dev-overlay
npm ERR!     @next/react-dev-overlay@"10.2.0" from next@10.2.0
npm ERR!     node_modules/next
npm ERR!       next@"latest" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0-rc.1" from @react-aria/breadcrumbs@3.1.4
npm ERR!   node_modules/@react-aria/breadcrumbs
npm ERR!     @react-aria/breadcrumbs@"^3.1.4" from react-aria@3.6.0
npm ERR!     node_modules/react-aria
npm ERR!       react-aria@"^3.6.0" from the root project
npm ERR!   73 more (@react-aria/button, @react-aria/checkbox, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-reconciler@0.20.4
npm ERR! node_modules/react-zdog/node_modules/react-reconciler
npm ERR!   react-reconciler@"^0.20.4" from react-zdog@1.0.11
npm ERR!   node_modules/react-zdog
npm ERR!     peer react-zdog@">=1.0" from @react-spring/zdog@9.2.0-beta.5
npm ERR!     node_modules/@react-spring/zdog
npm ERR!       @react-spring/zdog@"~9.2.0-beta.0" from react-spring@9.2.0-beta.3
npm ERR!       node_modules/react-spring
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

## Environment

- `react-spring` v9.2.0-beta.3
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Can you share your complete pkg.json please

**Comment by joshuaellis** [comment]
Oh I see, i understand the error you're having then, `react-spring` has all our targets in `konva, web, zdog` etc. What i'd advise you to do install a specific target, looking at your set up probably `@react-spring/web`?

**Comment by Dataxelio** [comment]
yep it works 👍 
I'm targeting web so I pick @react-spring/web.
Tks

**Comment by joshuaellis** [comment]
Glad to have helped!
