### ISSUE TITLE
Cannot install react-spring with npm.

### ISSUE THREAD

**Issue by kasperaamodt** [pmndrs/react-spring#1511]
Hi,

I'm trying to install react-spring in a Frontity project, and it does not work. I can install any other npm package, but not react spring. If i run "npm i react-spring" it just stops on idealTree, and does not continue, but it does not throw any error either. If i run it with "npm i react-spring --loglevel verbose" it looks like it it running the same timing idealtree forever. I tried to let it run to see if it finished, bud i got tired after 20 minutes. 

I have node 16.1.0 and npm 7.11.2.

Here is a link to the repo: https://github.com/aamodtgroup/aamodtgroup

**Comment by jhrtn** [comment]
I had the same issue just now. Downgrading to npm 6 worked for me if that possible for you 

https://github.com/pmndrs/react-spring/issues/1373

**Comment by joshuaellis** [comment]
I've heard this happen loads with npm7. It's because it expects you to have all the deps installed. This is why we have dedicated targets. E.g it I'm doing a web project I install @react-spring/web
