### ISSUE TITLE
`ParallaxLayer` doesn't inherit `horizontal` value

### ISSUE THREAD

**Issue by pikilon** [pmndrs/react-spring#1516]
## 🐛 Bug Report

The [documentation](https://react-spring.io/components/parallax#parallaxlayer) about the props of `ParallaxLayer`

horizontal? | boolean:  Defaults to the horizontal value of `Parallax`

## To Reproduce

Go to the example in the codesandobox

https://codesandbox.io/s/github/pmndrs/react-spring/tree/master/demo/src/sandboxes/parallax

## Expected behavior

Horizontal scroll instead of mixed

## Link to working codesandbox

https://codesandbox.io/s/upbeat-thunder-ntceu

## Environment

Code Sandbox

**Comment by joshuaellis** [comment]
This is resolved in our latest beta
