### ISSUE TITLE
 `Parallax.scrollTo` only scrolls to initial position

### ISSUE THREAD

**Issue by pikilon** [pmndrs/react-spring#1517]
## 🐛 Bug Report

It is not possible to Scroll using the parallax.scrollTo

## To Reproduce
1. open the spring documentation official example
https://codesandbox.io/s/github/pmndrs/react-spring/tree/master/demo/src/sandboxes/parallax-vert

2. click on the Server image inside the output
3. It does nothing

## Expected behavior

Scrolls to the second `offset` page with a bash terminal image inside
## Environment

"@react-spring/parallax": 9.1.2

**Comment by joshuaellis** [comment]
With all due respect, these bug reports are really unclear.

Can you try and thoroughly explain your bug, *why* you think it's a bug and *why* you think the expected behaviour is what you've written.

**Comment by pikilon** [comment]
I have update it

**Comment by kindoflew** [comment]
It seems like the most recent changes that fix both this and #1516 didn't make it into 9.1.2 (at least according to codesandbox?). If you update the version in the sandboxes to 9.2.0 everything should work.

**Comment by joshuaellis** [comment]
To add to that, there are a fair few fixes in our `beta` which is what @kindoflew is referring to.

**Comment by joshuaellis** [comment]
Although these sandboxes use the most up to date version of the library (9.2.0-beta.6?) and the issue is there 😞

**Comment by pikilon** [comment]
I think the sandboxes are in the latest stable version, which is 9.1.2.
Every user installing this package will have these issues.

**Comment by joshuaellis** [comment]
Ah my bad, yep updating them to our beta works as intended – https://codesandbox.io/s/lively-resonance-wp5fj?file=/src/App.tsx
