### ISSUE TITLE
useSprings does not properly clear controllers when length changes in React.StrictMode

### ISSUE THREAD

**Issue by tarngerine** [pmndrs/react-spring#1532]
## 🐛 Bug Report
When changing the length provided to useSprings in combination with a propsFn, the internal SpringRef does not properly dispose of the old refs when the array changes.

## To Reproduce

See CSB

## Expected behavior

See CSB, while the springs are correctly oscillating between lengths of 8 and 9, the api.current controllers always increase.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1629901/120428435-4306bf80-c339-11eb-97b0-935112f1c67d.png">

## Link to repro (highly encouraged)

https://codesandbox.io/s/elastic-hofstadter-m48zc?file=/src/UserTiles.jsx

## Environment

- `react-spring` v9.2.1
- `react` v17.0.2

**Comment by joshuaellis** [comment]
This looks like it was brought about in this commit – https://github.com/pmndrs/react-spring/commit/9176c5a87a4eb3f1e184dec0b68b789aca50f542 Might have been when I used `useRef` to assign the `Controllers`.

This fix _shouldn't_ be too hard, if youre interested in giving it a go and contributing! ⭐

**Comment by tarngerine** [comment]
might have some time this week, thanks!

**Comment by tarngerine** [comment]
hm, i added some tests to useSprings.test.tsx but it seems to be passing locally. any thoughts on this?

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1629901/120511488-15009a00-c390-11eb-8917-eb49a9769028.png">

**Comment by tarngerine** [comment]
oh hm, if im reading it correctly, these tests create a new useSpring hook instance every time `update` is called?

**Comment by joshuaellis** [comment]
No it doesn't because you don't destroy the spring when you update the props because of internal state etc.

**Comment by tarngerine** [comment]
ah, i see...

so without making any changes to the useSprings hook, i downloaded the CSB as a zip and added it to the demo page and it works fine
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/1629901/120516472-036dc100-c395-11eb-9c8d-e3ffc3fca962.png">

i did have to change the package import to `@react-spring/web` 

any clues on how this difference in behavior on prod 9.2.1 vs local monorepo might happen?

**Comment by joshuaellis** [comment]
It's `StrictMode`. Add it to `ReactDOM.render` and the bug is there.

**Comment by joshuaellis** [comment]
Might be something to do with this – https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects specifically:

> Strict mode can’t automatically detect side effects for you, but it can help you spot them by making them a little more deterministic. This is done by intentionally double-invoking the following functions:
> * Class component constructor, render, and shouldComponentUpdate methods
> * Class component static getDerivedStateFromProps method
> * Function component bodies
> * State updater functions (the first argument to setState)
> * Functions passed to useState, useMemo, or useReducer

**Comment by tarngerine** [comment]
interesting re: removing strictmode fixing the bug in CSB. i can dig into that too

however, my original point that i cannot repro in the cloned react-spring monorepo still stands — i had strictmode on there, too, and it works "fine". i added the CSB source code to `/demo`

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1629901/120584253-3a73bf00-c3f5-11eb-8f6e-6c2ca742d8a9.png">

ideally we could test for this so i'm just trying to get a local repro, bc i have no idea how i can fix this in the CSB environment as it's referencing an npm package

**Comment by joshuaellis** [comment]
I think I built the package and changed the web alias from `src/index` to `dist/NAME.esm.js`. This would emulate the `npm` package afaik...

**Comment by tarngerine** [comment]
sorry i dropped off, life happend!

so to make sure i undersatnd — you built this repo locally and moved the dist JS files into the CSB (or a cloned CSB locally). i havent done much aliasing before — how does that work? do you just change the import statement to be `import X from 'dist/NAME.esm.js'`?

**Comment by joshuaellis** [comment]
in `/demo` there's `vite.config.js`, it looks like this:

```js
import path from 'path'
import { defineConfig } from 'vite'
import reactRefresh from '@vitejs/plugin-react-refresh'

export default defineConfig({
  resolve: {
    alias: {
      '@react-spring/web': path.resolve('../targets/web/src/index.ts'),
      '@react-spring/parallax': path.resolve(
        '../packages/parallax/src/index.tsx'
      ),
      '@react-spring/three': path.resolve('../targets/three/src/index.ts'),
    },
  },
  plugins: [reactRefresh()],
})
```

This is where we alias the packages to the src code. Running `yarn dev` then lets you edit the src code and see those updates in the demos. But you could run `yarn build` and change that alias to the `dist` path of `web` for example.

**Comment by tarngerine** [comment]
got a few hours to dig into this

# Proper repro steps
- Add <React.StrictMode> to `/demos/index.tsx` — I was adding StrictMode to the wrong place
- Relinking / building is not necessary!
- Run `yarn dev` any time you update the hooks to see changes

# Findings
When in StrictMode, the "Cleanup any unused controllers" step does not run because `oldCtrls` is always empty inside the useLayoutEffect
<img width="498" alt="image" src="https://user-images.githubusercontent.com/1629901/122689123-0dd9e880-d1e6-11eb-8122-bae9711f8347.png">
<img width="669" alt="image" src="https://user-images.githubusercontent.com/1629901/122689465-4084e080-d1e8-11eb-857f-1abfb2b1437a.png">

I can't quite figure out why oldCtrls is being effected non-deterministically due to the double invoking useLayoutEffect, but ctrls is not.

I've even tried to replace the `oldCtrls` definition with:
- a useRef, and updating it inside the `[length]` useMemo
<img width="558" alt="image" src="https://user-images.githubusercontent.com/1629901/122689436-1fbc8b00-d1e8-11eb-864c-0556b6d73818.png">

- `state.ctrls.slice(length, prevLength)`
<img width="473" alt="image" src="https://user-images.githubusercontent.com/1629901/122689451-2ea33d80-d1e8-11eb-99ba-2f2decbc7e52.png">

the oldCtrls inside useLayoutEffect is always empty

# Potential fix
The one way I could fix this issue was to move the entire "Cleanup any used controllers" function into the length useMemo, but this seems like dangerously moving logic that may have other effects. The tests are passing, though.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/1629901/122689498-83df4f00-d1e8-11eb-9155-f86e24539465.png">

Any guidance you have here would be great — if I should move ahead with this potential fix or look elsewhere.

**Comment by joshuaellis** [comment]
Maybe make a PR? It's easier to review that way and our CI will start building some sandboxes for us at the same time so we can review a bit better.

**Comment by tarngerine** [comment]
@joshuaellis done! https://github.com/pmndrs/react-spring/pull/1597/files#diff-e1288b0efcce202f0575295aec86c6f33c5d81adac9751131dc5d2b08e40e73aR136
