### ISSUE TITLE
Fails at installation

### ISSUE THREAD

**Issue by jensrodi** [pmndrs/react-spring#1535]
## 🐛 Bug Report

Version 9.x fails with "Cannot read property 'sourceReference' of null" error. I've downgrade to React 16 as other posts suggest that react-spring isn't compatible with React 17 (?)

## To Reproduce

In an empty folder:
npm install react@16.14.0 
npm install react-spring

## Expected behavior

Expect to install without errors

## Environment

- `react` v16.0.
- `react-spring` v9.2.1
- `npm` 7.15.1
- `Windows 7 / 64bit`

**Comment by joshuaellis** [comment]
not a bug, see #1413 (comment)

**Comment by jensrodi** [comment]
Well, it may not be a bug but the behavior is not easy to understand. I assumed that 'react-spring' would install like any other npm package. After going through #1413 as you suggested I tried installing "@react-spring/web" which succeeded. I would suggest a note on this on the react-spring.io under installation :-)

Thanks for the help

**Comment by joshuaellis** [comment]
But it is in the docs? https://react-spring.io/#platforms

However, if you have an opinion to improve it, feel free to submit a PR over on [react-spring.io](https://github.com/pmndrs/react-spring.io)

**Comment by jensrodi** [comment]
I did read the documentation [https://react-spring.io/#installation] I assumed that I needed to install the entire library and that `yarn` could be replaced with `npm` (at least in my experience that works).

I only suggest that the documentation actually reflects the fact that npm will not be able to install the entire library but only the individual platforms. Just my opinion :-)

**Comment by joshuaellis** [comment]
Well NPM @ 6 will install it, but @ 7 you need to include all the deps, so in the case of `react-spring` you need zdog, konva etc....

**Comment by MForMarlon** [comment]
@joshuaellis I'm encountering the same "sourceReference of null" error when trying `npm install react-spring` on npm v7 and react v17, and am confused about the solution. If I try `npm install @react-spring/web` and then try `import { useSpring, animated } from 'react-spring'`, VSCode tells me that the module can't be found.

**Comment by joshuaellis** [comment]
@MForMarlon, you haven't installed `react-spring` you've installed `@react-spring/web` so you need to import from `@react-spring/web` 😄

**Comment by MForMarlon** [comment]
@joshuaellis Whoops, thanks for the catch 😅

**Comment by amhunt** [comment]
@joshuaellis we ended up converting our project to `yarn`. 😂 

At least this was a good forcing function!
