### ISSUE TITLE
TypeError a.add is not a function 

### ISSUE THREAD

**Issue by melissafzhang** [pmndrs/react-spring#1537]
## 🐛 Bug Report

I'm seeing this error being thrown to my ErrorBoundary 
```
TypeError a.add is not a function
    _N_E/node_modules/@react-spring/core/index.js:1482:33 

```

## To Reproduce

I'm unable to reproduce

## Expected behavior

No error is thrown

## Environment

- `react-spring` v9.1.2
- `react` v17.0.1

**Comment by joshuaellis** [comment]
> I'm unable to reproduce

Please create a reproduction of the error in a codesandbox so we can reopen the issue.
