### ISSUE TITLE
Invalid interpolated color values

### ISSUE THREAD

**Issue by jasonlong** [pmndrs/react-spring#1569]
## 🐛 Bug Report

In trying to animate between two colors (and depending on which colors), it appears that some rgb values go out of range during the animation. In r3f, these colors turn black temporarily. Note the values < 0 and > 255:

```
THREE.Color: Unknown color rgba(256, 256, -1, 1) 
THREE.Color: Unknown color rgba(267, 279, -12, 1) 
THREE.Color: Unknown color rgba(264, 272, -9, 1) 
THREE.Color: Unknown color rgba(261, 266, -6, 1) 
THREE.Color: Unknown color rgba(258, 260, -3, 1) 
THREE.Color: Unknown color rgba(256, 256, -1, 1) 
```

## To Reproduce

Set up a spring to animate between `yellow` and `purple` with a `wobbly` config.

## Expected behavior

Values of interpolated colors should be valid throughout animation.

## Link to repro (highly encouraged)

https://codesandbox.io/s/invalid-react-spring-colors-sehjn?file=/src/App.js

## Environment

- `react-spring` v9.2.2
-  `react-three-fiber` v6.2.3
- `react` v17.0.2

**Comment by joshuaellis** [comment]
How would you envisage a wobbly config work with a color? Wobbly overshoots and comes back in an elastic way, so by nature the values have to go past the limitations you'd expect i.e 0-1 it would go to something like 1.2 to give the elastic feel.

**Comment by jasonlong** [comment]
Sure, I get that from an implementation standpoint. As a user of the library, I wouldn't expect invalid colors to be generated during the animation though. 

For my purposes, I supposed I could use different springs for the motion and color attributes.

**Comment by joshuaellis** [comment]
If invalid colours didn't show, how would you know it wasn't working 😅 lol, well thank you for the feedback. I'm not sure it should limit the colour, maybe a warning could help?

**Comment by jasonlong** [comment]
Yeah, it's a tricky problem. I guess I'd propose clamping the rgb values to `0..255`. This wouldn't be mathematically correct, but if a wrong color is going to be shown it would be better to show one that's close rather than one that doesn't exist.

Anyhow, thank you for the discussion. Feel free to close this out if it doesn't seem worth addressing.

**Comment by joshuaellis** [comment]
with no community contribution i'm going to close this for now. We can revisit later if someone feels strong enough 👍🏼
