### ISSUE TITLE
IE11 stuck in the `from` state

### ISSUE THREAD

**Issue by nkalinov** [pmndrs/react-spring#1580]
## 🐛 Bug Report

Thanks for the library. I know that IE11 is not officially supported but since it used to work just fine (after transpilation) in 9.0.0-rc.3 I thought the regression might be obvious for an active contributor.

## To Reproduce
In webpack config, enable transpilation of `react-spring` then try to run one of the basic examples in IE11.

```
function Text() {
  const [flip, set] = useState(false)
  const props = useSpring({
    to: { opacity: 1 },
    from: { opacity: 0 },
    reset: true,
    reverse: flip,
    delay: 200,
    config: config.molasses,
    onRest: () => set(!flip),
  })

  return <animated.h1 style={props}>hello</animated.h1>
}
```

## Expected behavior

Opacity should animate.

## Actual behavior

The h1 is stuck at the initial state: `<h1 style="opacity: 0;">hello</h1>` and doesn't animate.

## Environment

- `react-spring` v9.2.3
- `react` v16.13.1

**Comment by joshuaellis** [comment]
There was a very large rewrite from `rc3` to `stable` since it's not animating I would assume that the render loop is not working, which is part of our `rafz` package so you could take a look there. However, you're right, we don't support IE11 so this won't be something i'll be taking forward.
