### ISSUE TITLE
The `immediate` property no longer works with `useTransition` hook

### ISSUE THREAD

**Issue by wyze** [pmndrs/react-spring#1581]
## 🐛 Bug Report

The `immediate` property no longer works with `useTransition` hook.

## To Reproduce

See CodeSandbox. Use the `useTransition` hook with `immediate: true` passed in as a property.

## Expected behavior

No animations, transitions happen immediately.

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-usetransition-immediate-bug-4vtob?file=/src/App.tsx

If you change the version to `9.0.0-rc.3` you will see that the transitions are immediate.

## Environment

- `react-spring` v9.x (non-rc)
- `react` v17.0.2

**Comment by joshuaellis** [comment]
👋🏼 would you please be able to provide a super minimal reproduction of the code, nothing fancy getting making noise etc?

**Comment by wyze** [comment]
@joshuaellis Is this one better? https://codesandbox.io/s/simple-transition-d95n7?file=/src/App.tsx

I tried looking into this myself to submit a PR, but I couldn't get demos to run locally. Really strange issue that I explained in the react-spring channel in the Discord.

**Comment by joshuaellis** [comment]
Sorry i didnt get back to you on there, i'm catching up on a lot of things. I've just fixed the demos, they should run now. You'll need to merge upstream. Let me know if you have any issues.

**Comment by wyze** [comment]
No problem, I can understand being busy. I pulled latest master and demos are working now. So going to poke around for a bit and see if I can find the fix.

**Comment by joshuaellis** [comment]
If you wanna chat about it, feel free to @ me or submit a draft PR etc and we can go from there!

**Comment by wyze** [comment]
I've tracked it down to this commit: [`ee6166e` (#1330)](https://github.com/pmndrs/react-spring/pull/1330/commits/ee6166e474d0a2a0e33dc726f59797f416d81149)

Reading the comment around defaultProps, I tried setting `default: { immediate: true }` and then the transitions were immediate. The code is likely correct, maybe the change here would be to update the types to make `useTransition({ immediate: true })` an error.

**Comment by joshuaellis** [comment]
But passing the prop immediate should work though, I'm on mobile and cant read the commit well (bad app). But it would be weird if it didn't work on only one hook...?

**Comment by wyze** [comment]
> But it would be weird if it didn't work on only one hook...?

Yeah you are right. I'll keep digging into the changes in that commit to try and isolate the exact change(s) that broke the functionality.

**Comment by hualu00** [comment]
@wyze , Thanks for the fix. However it seems `immediate` still not work with multi-stage transitions.  
Demo:  https://codesandbox.io/s/simple-transition-forked-jqy20?file=/src/App.tsx

**Comment by hipstersmoothie** [comment]
Seeing this as well. @aleclarson Could you re-open this issue?
