### ISSUE TITLE
TypeError: Cannot create property 'Symbol(AnimatedComponent)

### ISSUE THREAD

**Issue by Vazgen7788** [pmndrs/react-spring#1582]
## 🐛 Bug Report

In case `Array.prototype` has a key which value type is `boolean` react spring throws an error. 

```
react-spring-animated.cjs.dev.js:367 Uncaught TypeError: Cannot create property 'Symbol(AnimatedComponent)' on boolean 'true'
```

## To Reproduce

- `Array.prototype['prop'] = true`
- Boot react application

## Expected behavior

React spring should not use all properties in `Array.prototype`

## Environment

- `react-spring` ^9.2.3
- `react` v17.0.2

**Comment by Vazgen7788** [comment]
https://codesandbox.io/s/sad-driscoll-xtotq?file=/public/index.html

### Commenting line 27 will fix issue. 
<img width="546" alt="Screen Shot 2021-06-23 at 18 08 57" src="https://user-images.githubusercontent.com/8538941/123111589-159bc600-d44e-11eb-8a4c-5554fb8ccf9f.png">

**Comment by joshuaellis** [comment]
I'm gonna be honest, this is a really weird issue that i've not seen before, we're not using `Array.prototype` in that file, we do however use `Array.from`, but if you want this "bug" fixing then I think you'd have to do some investigation yourself...

It would be helpful if you could explain some context as to why you want to use `Array.prototype`?

**Comment by Vazgen7788** [comment]
Honestly, I don't want to use `Array.prototype`. 
We use react in Ember application. Ember mutates `Array.prototype`, and react app stops working. 
Will explore to find solution.

**Comment by joshuaellis** [comment]
I wonder if it's the use of `Symbol`, i've never used it personally.
