### ISSUE TITLE
jest.fakeTimers and jest.advanceTimersByTime do not trigger onRest callback.

### ISSUE THREAD

**Issue by DamianPereira** [pmndrs/react-spring#1583]
## 🐛 Bug Report

I'm trying to test a react component with react-testing-library, the component has an animation and runs a callback from the props  when the animation ends with `onRest` option on `api.start()`

## To Reproduce

1. Create a component with a simple animation and a callback called in onRest
2. Create a test using jest.fakeTimers and jest.advanceTimersByTime
3. The callback won't be called

If using react testing library's waitFor, the callback is correctly called.

## Expected behavior

All animations should happen when timers are advanced, including frame by frame onChange calls, and all that would happen normally without fake timers.

## Link to repro (highly encouraged)

[This](https://codesandbox.io/s/react-spring-fake-timers-rlc47?file=/src/App.spec.js) is the code sandbox, but for some reason it does not work on codesandbox (some jest timer bug unrelated to this issue). To reproduce please download as zip, and run `npm install` and `npm run test`.

## Environment

- `react-spring` v9.2.3
- `react` v17.0.2

**Comment by joshuaellis** [comment]
Thanks for the report, fakeTimers is always a bit tricky, have you taken a look at how we're testing our springs? There may be something you could use there to help you out?

**Comment by DamianPereira** [comment]
I tried finding the tests in this repo, but I could not find them, could you please point me to a test file for react spring animations?

**Comment by joshuaellis** [comment]
They're inline with the code they're testing. A good package with plenty of tests is the core package.

**Comment by DamianPereira** [comment]
Thank you! I'll check them out.

**Comment by joshuaellis** [comment]
There's a dedicated section of the docs for this – https://react-spring.io/guides/testing

If you need anymore help we can revisit / reopen.
