### ISSUE TITLE
useSpring does not orchestrate animations if one is using config w/o duration, when others do

### ISSUE THREAD

**Issue by ShiiRochi** [pmndrs/react-spring#1584]
## 🐛 Bug Report

I am trying to chain two animations so they should work in sequence, however, they're happening at the same time. The first animation is using animation configuration, while another - only duration.

## To Reproduce

1. create some UI stuff...for example expanding box and elements appearing inside
2. create useSpring
3. create useTransition
4. use config.stiff or any other in useSpring
5. use duration in config for useTransition
6. make refs for both animations
7. chain animations like so: isVisible ? [springRef, transitionRef] : [transitionRef, springRef]

## Expected behavior

useChain successfully orchestrates useSpring and useTransition and knows how to handle animations with different configurations, i.e. when useSpring ens, useTransition starts and vice versa.

## Link to repro (highly encouraged)

[CodeSandbox demo](https://codesandbox.io/s/exciting-tereshkova-40e5b?file=/src/App.tsx).

Here bug is visible when toggling reverse animation...when a box is hiding its content.

## Environment

- `react-spring` v9.2.3
- `react` v17.0.1

**Comment by ShiiRochi** [comment]
Update: bug describes above is happening even if I would remove `config` property from `useTransition`.

**Comment by joshuaellis** [comment]
I think this is probably related to #1512

**Comment by ShiiRochi** [comment]
Agree, there is also #1492 issue, related to the same thing as I did here.

**Comment by joshuaellis** [comment]
Hello!

I've pushed a fix as `9.2.6-beta.0` please let me know if this resolves your issue 😄

**Comment by arteforme** [comment]
Preliminary testing shows that it's been fixed.  I'll continue testing and let you know if I find anything.

**Comment by joshuaellis** [comment]
released in v9.2.6
