### ISSUE TITLE
onRest gets called before onScroll callback gets fired.

### ISSUE THREAD

**Issue by DamianPereira** [pmndrs/react-spring#1595]
## 🐛 Bug Report

When using onRest together with changing scroll position, the onRest callback gets called before all events fired are handled.  I'm not sure if this is a bug or intended behavior.

## To Reproduce

```javascript
export default function App() {
  const divRef = useRef(null);
  const [animating, setAnimating] = useState(false);
  const _ = useSpring(() => ({
    from: { page: 0 },
    to: { page: 1 },
    onStart: () => {
      setAnimating(true);
    },
    onChange: (_this, ctrl) => {
      divRef.current.scrollTop = ctrl.get().page * divRef.current.clientHeight;
    },
    onRest: () => {
      setAnimating(false);
      console.log("animation finished");
    }
  }));

  const handleScroll = () => {
    if (animating) {
      console.log("scroll because of animation");
    } else {
      console.log("user has scrolled");
    }
  };

  return (
    <div ref={divRef} className="container" onScroll={handleScroll}>
      {[...Array(20)].map((_, i) => (
        <h1 key={i}>{i}</h1>
      ))}
    </div>
  );
}
```

The idea of this code is to animate the scrolling of the div. But to differentiate in the handler if the div was scrolled by the animation, or manually. All scroll events end up on the "animation has scrolled" branch, except the last one, which ends up happening after the onRest callback.

## Expected behavior

I need the last onScroll callback to be called before onRest, so I can differentiate if the animation is doing the scrolling or if the user is scrolling. If there is another way of checking this like imperatevely, asking react-spring if the animation is running (like some api.status() method?).

## Link to repro (highly encouraged)

[Codesandbox link](https://codesandbox.io/s/react-spring-onrest-and-onscroll-3q4rk?file=/src/App.js:108-917)

## Environment

- `react-spring` v9.2.3
- `react` v17.0.1

**Comment by joshuaellis** [comment]
You'd probably need to call `get` on the controller of the spring but then when you have your springs you can use the `is` method, documented [here](https://react-spring.io/classes/spring-value#isphase-string-void)

But this is a pretty strange way of using springs. I'm going to move this to a discussion.
