### ISSUE TITLE
useChain runs each item concurrently, not in sequence

### ISSUE THREAD

**Issue by jmagaram** [pmndrs/react-spring#1605]
## 🐛 Bug Report

I'm trying to do animation X and then when that finishes, do animation Y. I'm using the useChain feature but it seems to run everything in parallel.

## To Reproduce

[code sandbox super simple repro](https://codesandbox.io/s/tryingsequentialanimation-74tpn?file=/src/Shaker.tsx)

## Expected behavior

The div animates horizontally and then vertically.

## Link to repro (highly encouraged)

[code sandbox super simple repro](https://codesandbox.io/s/tryingsequentialanimation-74tpn?file=/src/Shaker.tsx)

## Environment

- `react-spring` ^9.2.3
- `react` 17.0.2

**Comment by joshuaellis** [comment]
Duplicate

**Comment by jmagaram** [comment]
Of what? I searched and saw other reports about it not working if Duration was specified or something like that. Did not see any general "useChain is broken".

**Comment by FRMR1** [comment]
Also haven't found a fix of this. Just saying "Duplicate" doesn't help anyone.
