### ISSUE TITLE
No autocompletion in IDEs

### ISSUE THREAD

**Issue by kosciolek** [pmndrs/react-spring#1633]
## 🐛 Bug Report

VS Code does **not** provide autocompletion for this package, as far as I'm concerned

WebStorm provides autocompletion (unless Yarn 2 is used, then even WebStorm dies).

I don't know why it could be though, maybe because there's no `types` field in `package.json`?

## Environment

```
"react-spring": "^9.2.4",
"typescript": "^4.3.5"
```

**Comment by joshuaellis** [comment]
Please provide a reproduction of the issue you're facing.
