### ISSUE TITLE
[Regression in 9.2.2] conflict between @react-spring/web and @react-spring/three animated component

### ISSUE THREAD

**Issue by dbismut** [pmndrs/react-spring#1683]
## 🐛 Bug Report

Starting from 9.2.2, there seems to be a conflict between @react-spring/web and @react-spring/three `animated` component. Importing `{ animated } from "@react-spring/three` breaks all dom animations.

## Link to repro (highly encouraged)

Clicking on the title is supposed to make the title move 100px on the right. Nothing happens here.
Commenting the import from @react-spring/three on line 3 fixes it. This problem seems to appear in 9.2.2.

https://codesandbox.io/s/adoring-worker-iptsw?file=/src/App.js

## Environment

- `react-spring` v9.2.4
- `react` v17.0.2

**Comment by joshuaellis** [comment]
I believe this is a duplicate of #1586

The issue being is they use the same `rafz` instance to run the animations, but `three` is supposed to be ran by `r3f` otherwise VR won't work correctly.

**Comment by dbismut** [comment]
Hmm I see... any workarounds or this is a no fix?

**Comment by joshuaellis** [comment]
see this comment – https://github.com/pmndrs/react-spring/issues/1586#issuecomment-870778191

**Comment by dbismut** [comment]
Oh right thanks Josh. Closing as duplicate then!
