### ISSUE TITLE
AnimationFrame load CPU after component unmounted

### ISSUE THREAD

**Issue by Luchanso** [pmndrs/react-spring#1732]
## 🐛 Bug Report

AnimationFrame continue calling after component destroyed. `stop()` not helped.

![image](https://user-images.githubusercontent.com/2098777/139920706-8a01827b-6e7a-4691-891d-4c9ad115fb6a.png)

![image](https://user-images.githubusercontent.com/2098777/139921498-78f26979-5c09-4c8f-a378-8aec1499d516.png)

## To Reproduce

https://codesandbox.io/s/exciting-shape-rqdk4?file=/src/App.js

## Expected behavior

AnimationFrame stop calling after component 
![image](https://user-images.githubusercontent.com/2098777/139921185-f39f617b-22c9-4582-acd0-5069784043a4.png)

## Link to repro (highly encouraged)

https://codesandbox.io/s/exciting-shape-rqdk4?file=/src/App.js

## Environment

- `react-spring` v9.3.0
- `react` v17.02

**Comment by artman** [comment]
We're experiencing this same issue in production. Also happens on v9.2.4 where we upgrade from. After any single one react-spring animation has completed, animation frames are still being requested and CPU is at 2.5% even though no re-rendering is happening.

**Comment by joshuaellis** [comment]
I haven't really looked into this yet, but off the top of my head, RAF is probably still being called after unmount, which would indicate its in the global scope or something similar

**Comment by artman** [comment]
Just tested and this seems to be an issue with all 9.x.x versions.

**Comment by joshuaellis** [comment]
> Just tested and this seems to be an issue with all 9.x.x versions.

This would make sense since v9 was a major re-write of most things incl. introducing `@react-spring/rafz`

**Comment by srubin** [comment]
Would rafz be interested in a PR that stops the RAF loop if there are no scheduled timeouts or updates?

**Comment by joshuaellis** [comment]
I'd be very interested in seeing it 🥳 sounds great!

**Comment by joshuaellis** [comment]
this has been released on `v9.4.0-beta.3`
