### ISSUE TITLE
Unexpected token (

### ISSUE THREAD

**Issue by 244686710** [pmndrs/react-spring#1741]
## 🐛 Bug Report
In the browser kernel Chrome53. 0.2785.116 runtime error: react-spring-core.esm.js:811 Uncaugeht SyntaxError: Unexpected token (

## Expected behavior
After the react-spring-core.esm.js file is compiled with babel.forceAllTransforms, the error can be eliminated

## Link to repro (highly encouraged)
![image](https://user-images.githubusercontent.com/20982796/141036096-172366f8-9662-4684-a463-e4c4fedb51c4.png)

![image](https://user-images.githubusercontent.com/20982796/141036071-ccbb2a98-5158-4c4c-a4ad-cd6ac5672b6e.png)

(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment

- `react-spring` v9.3.0
- `react` v17.0.5
-  "@babel/core": "^7.14.0",
    "@babel/preset-env": "^7.14.1",
    "@babel/preset-react": "^7.13.13",
    "@babel/polyfill": "^7.12.1",

**Comment by 244686710** [comment]
## Bug Report
 react-spring-core.esm.js:811 Uncaught SyntaxError: Unexpected token (
![image](https://user-images.githubusercontent.com/20982796/140858125-0f37e6ea-8c03-4bca-a20b-a8f826d34bcf.png)
![image](https://user-images.githubusercontent.com/20982796/140858155-fff80e90-10fc-4d45-9192-8b96350f84e8.png)
## Environment
----
react-spring v9.3.0
react 17.0.2

**Comment by joshuaellis** [comment]
please correctly fill out the issue template and we can actually investigate the issue.

**Comment by Aaron674092290** [comment]
> please correctly fill out the issue template and we can actually investigate the issue.

I have the same problem, please take a look at my demo @joshuaellis 
`https://github.com/Aaron674092290/react-antd-mobile-demo`
