### ISSUE TITLE
Golden Sponsor Logo not showing in README.md

### ISSUE THREAD

**Issue by kabilanvennila** [pmndrs/react-spring#1747]
## 🐛 Bug Report
Golden Sponsor Logo not showing in README.md

## To Reproduce
1 . Visit https://github.com/pmndrs/react-spring/blob/master/README.md
2.  Slide down to gloden sponsor section
3.  The Logo doesnt show 

## Expected behavior
The image should be rendered properly

**Comment by kabilanvennila** [comment]
I'd Like to fix this

**Comment by joshuaellis** [comment]
Go right ahead and fix :)

**Comment by joshuaellis** [comment]
resolved by #1748
