### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by cedricdelpoux** [pmndrs/react-spring#1751]
## 🐛 Bug Report

When installing `react-spring`, there are few unmet peer dependency warnings in the terminal

```
warning "react-spring > @react-spring/konva@9.3.0" has unmet peer dependency "konva@>=2.6".
warning "react-spring > @react-spring/konva@9.3.0" has unmet peer dependency "react-konva@^16.8.0  || ^17.0.0".
warning "react-spring > @react-spring/native@9.3.0" has unmet peer dependency "react-native@>=0.58".
warning "react-spring > @react-spring/three@9.3.0" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "react-spring > @react-spring/three@9.3.0" has unmet peer dependency "three@>=0.126".
warning "react-spring > @react-spring/zdog@9.3.0" has unmet peer dependency "react-zdog@>=1.0".
warning "react-spring > @react-spring/zdog@9.3.0" has unmet peer dependency "zdog@>=1.0".
```

## To Reproduce

`yarn add react-spring`

## Expected behavior

No warnings

## Environment

- `react-spring` v9.3.0
- `react` v17.0.2

**Comment by joshuaellis** [comment]
This isn't a bug. If you don't want the errors I would advise you installing a specific target e.g '@react-spring/web'

**Comment by cedricdelpoux** [comment]
Thanks for this but I did not found anything in the docs about this on https://react-spring.io/.
I think I'm not the only one using `react-spring` instead of `@react-spring/web`

**Comment by joshuaellis** [comment]
Thanks, but it's actually on the [homepage](https://react-spring.io/#platforms), if you think you can improve the docs, please feel free to make a contribution

**Comment by cedricdelpoux** [comment]
Good catch, thanks!
