### ISSUE TITLE
npmjs is missing the README

### ISSUE THREAD

**Issue by OnkelTem** [pmndrs/react-spring#1756]
please fix

![image](https://user-images.githubusercontent.com/114060/142154570-e8a3d633-84a9-47b2-b646-f441c30e78bc.png)

**Comment by ljharb** [comment]
Why was this closed? There's still no readme on npm. Perhaps your bazel rule failed to copy it to the publish directory?

**Comment by joshuaellis** [comment]
There's one in the package & it's included in the `files` part of the `package.json` why it's not deploying i'm not sure. 

If anyone wants to create a PR for this I'll check it out. Else, it's not really on the agenda...

**Comment by ljharb** [comment]
@joshuaellis no, it is not in the package - https://unpkg.com/browse/react-spring@9.3.0/ - so it's almost certainly an issue on your end, altho i suppose it could be npm's. Either way it results in your package lacking a readme on the most important place, npm, so why wouldn't that be considered an open issue?

**Comment by joshuaellis** [comment]
Like I said, you're welcome to create a PR for this

**Comment by ljharb** [comment]
I'm very astonished that a package maintainer wouldn't be urgently releasing a patch release to fix something like this. If this is how you're comfortable with your package representing itself, I think that red flag should remain. Good luck!

**Comment by joshuaellis** [comment]
Since you felt so passionate about it, it's now been updated. For future though, minor bugs like this, I'm sure the community can help out with this.

**Comment by ljharb** [comment]
713fea0328c7d9a7b89142dcde26c0a00596b12f, for reference.
