### ISSUE TITLE
PR template references a file that doesn't seem to exist

### ISSUE THREAD

**Issue by millsoper** [pmndrs/react-spring#1762]
## 🐛 Bug Report
A comment in the [PR template](https://github.com/pmndrs/react-spring/blob/master/.github/PULL_REQUEST_TEMPLATE.md) (visible while creating a new PR) instructs contributors to read `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md`. `CONTRIBUTING.md` is at the root of the project, but `CODE_OF_CONDUCT.md` appears to be absent from the repository.

Either a Code of Conduct should be added to the project, or the reference should be removed from the PR template. Input from maintainers as to which direction to take would be much appreciated.

## To Reproduce

1. Fork the repo.
2. Clone a copy of your fork.
3. Create a new branch and commit a trivial change.
4. Open a PR for your branch.
5. Observe the comment at the top of the PR description body. It should look like this: 
![Screen Shot 2021-11-18 at 6 19 58 PM](https://user-images.githubusercontent.com/11150372/142553850-d856793e-43bc-49e4-80a7-bce39b2e254a.png)

6. Search the repository for a file called `CODE_OF_CONDUCT.md`

## Expected behavior

There should be a Code of Conduct discoverable in the repo (or there should be no instruction to read one.) 

## Link to repro (highly encouraged)

n/a
(Please provide either a [CodeSandbox demo](https://codesandbox.io) or an example GitHub repo.)

## Environment
n/a
- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by joshuaellis** [comment]
Remove code of conduct from the template 😄
