### ISSUE TITLE
Example "You can transition arrays" from Docs does not work

### ISSUE THREAD

**Issue by unegare** [pmndrs/react-spring#1765]
## 🐛 Bug Report

There is an extra move to the right which accumulates in time. The first one takes place with the third iteration of transition

## To Reproduce

Just run the code

## Expected behavior

Just translate in and out of the frame on the *same* place.

## Link to repro (highly encouraged)

https://codesandbox.io/embed/distracted-carlos-6r5c7

## Environment

- `react-spring` v9.3.1
- `react` v17.0.2

**Comment by MateCon** [comment]
Hi, this is my first time contributing in github, can I help with this?

**Comment by joshuaellis** [comment]
Sure thing @MateCon!

**Comment by MateCon** [comment]
I think the problem is that some of the previous instances of the nodes are not being removed, moving the new ones to the right. This only happens with the timeout in useEffect, if it is removed everything works fine, except that the exit animation doesn’t appear.

**Comment by joshuaellis** [comment]
When you're ready, just make a PR with the solution and we can discuss in better detail there :)

**Comment by joshuaellis** [comment]
We removed this example from the docs site.
