### ISSUE TITLE
Issue with rerender when using the Parallax enabled property

### ISSUE THREAD

**Issue by Lucasdsk** [pmndrs/react-spring#1766]
## 🐛 Bug Report

I'm trying to enable and disable the Parallax scroll dynamically through the **`enabled`** property.

Doc.: https://react-spring.io/components/parallax#parallax-1

The issue is that I'm getting the error:

![image](https://user-images.githubusercontent.com/7729844/143083000-3dd2ed60-3e3b-497b-9f68-ea6eebaf49c1.png)

This is breaking the whole page behavior, the scroll stops working normally. 

## To Reproduce

Change the **`enabled`** property dynamically.

## Expected behavior

Enable and disable the scroll normally.

## Link to repro (highly encouraged)

I've created this example that's pretty similar to what I have in my project.
https://codesandbox.io/s/react-spring-parallax-7bt5t?file=/src/App.tsx

## Environment

- `react-spring` v8.0.27
- `react` v17.0.1
- `@react-spring/parallax`: "^9.3.0",

**Comment by joshuaellis** [comment]
resolved by #1767
