### ISSUE TITLE
rafz.cancel() has no effect on onFrame, onStart and onFinish callbacks

### ISSUE THREAD

**Issue by clementroche** [pmndrs/react-spring#1776]
## 🐛 Bug Report

rafz.cancel() has no effect on onFrame, onStart and onFinish callbacks

## To Reproduce

https://codesandbox.io/s/rafz-cancel-raf-nc344

## Expected behavior

rafz.cancel(loop) should stop loops created using onFrame, onStart or onFinish

## Link to repro (highly encouraged)

https://codesandbox.io/s/rafz-cancel-raf-nc344

## Environment

- `react-spring` v9.3.1
- `react` v17.0.2

**Comment by joshuaellis** [comment]
This has been released in v9.4.0-beta.2

**Comment by clementroche** [comment]
🙏
