### ISSUE TITLE
Concurrent Mode + Strict Mode cause useTransition to not unmount component after leave

### ISSUE THREAD

**Issue by mnoop** [pmndrs/react-spring#1790]
## 🐛 Bug Report

It seems that when Concurrent Mode and Strict Mode are both enabled, useTransition does not automatically unmount a component after it leaves. Also, it seems that the enter animation does not occur. It could just be that I'm doing something wrong.

## To Reproduce

1. Enable Concurrent Mode and Strict Mode
2. Create a useTransition hook for a single item (in this case a number)
3. Change the number (causing the old number to leave and the new number to enter)
4. The previous number does its leave animation, but is not automatically unmounted once the transitions finish
5. Disabling either Concurrent Mode or Strict Mode seems to fix it

## Expected behavior

According to the docs, the default behavior is:

> By default, unmounting is postponed until the next render or until all transitions are resting.

## Link to repro (highly encouraged)

https://codesandbox.io/s/white-silence-9ek60

(The intended animation is that the old number leaves upward and the new number enters from the bottom. It would be surrounded with a fixed height container with the overflow hidden, but is not so you can see the unmounted component)

## Environment

- `react-spring` v9.3.2
- `react` v18.0.0-rc.0

**Comment by joshuaellis** [comment]
Please provide a reproduction of the issue in its simplest form.

**Comment by joshuaellis** [comment]
This has been resolved by our latest version `v9.4.5`
