### ISSUE TITLE
[bug]: ReferenceError: Cannot access 't' before initialization

### ISSUE THREAD

**Issue by RandomToni** [pmndrs/react-spring#1811]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.1

### What's Wrong?

Getting error: "ReferenceError: Cannot access 't' before initialization at Object.applyAnimatedValues " whenever a component with animated styles gets mounted.

While developing, there is no issue, once the project is built and deployed on the hosting, the bug appears.

code:
```js
import { observer } from 'mobx-react';
import { FunctionComponent, CSSProperties, useEffect } from 'react';
import { useStores } from '@models/root-store';
import { useSpring, animated } from 'react-spring'

const USERMENUBASICSTYLE: CSSProperties = {...}

export const UserAnimatedMenu: FunctionComponent = observer(props => {

  const { showMenu } = props
  const { userStore } = useStores()
  const [animatedStyles, api] = useSpring(() => ({
    height: 0,
    paddingBottom: 0,
    paddingTop: 0
  }))

  useEffect(() => {
    api.start({
      height: showMenu ? 100 : 0,
      paddingBottom: showMenu ? 20 : 0,
      paddingTop: showMenu ? 20 : 0,
      config: { duration: 300 }
    })
    return () => {
        api.stop()
    }
  }, [showMenu])

  return (
    <animated.div style={{...USERMENUBASICSTYLE, ...animatedStyles}}>
      <p>{userStore.getUsername}</p>
    </animated.div> 
  )
})
```

### To Reproduce

After the component mounts, browser crashes (tested in chrome, safari)

### Expected Behaviour

Browser does not crash and animation gets triggered after 'showMenu' variable is 

### Link to repo

https://codesandbox.io/s/currying-cache-nue7i?file=/src/menu.jsx

**Comment by joshuaellis** [comment]
Thanks for the report, looking at the sandbox nothing happens. Do you have a link to where it's hosted?

Also does it happen when the component is not wrapped in `observer`?

**Comment by RandomToni** [comment]
Ok, so I tried removing the observer but nothing changed. I started debugging the .esm file and surprisingly found that I could make it work if I commented out the content of the applyAnimatedValues function passed to the createHost method. To be a little more specific, the error appears when "dangerousStyleValue" is being called, at the time of the component rendering. The styles that are being animated are height, paddingBottom and paddingTop.

I could not make this work, maybe you can give me a tip where to look deeper?

**Comment by joshuaellis** [comment]
>I could not make this work, maybe you can give me a tip where to look deeper?

I can't without seeing a reproduction of the bug unfortunately, this is most unusual and your debugging journey so far would indicate this is a deep breaking bug and the lack of anyone else reporting makes me suspicious.

Have you tried running the app in `incognito`?

Else if you can point me to it breaking in a PROD env or the source code I can take a better look.

**Comment by RandomToni** [comment]
Hello,

I uploaded the code here https://hybeans.com/react-spring

**Comment by joshuaellis** [comment]
Looks like it's the transpiling of your code. e.g. Babel plugins malforming. Can I see the actual source? or a reproduction of the bug in situ

**Comment by RandomToni** [comment]
Hello, we'll be checking the projects configuration and will be back to you with an update on this. Thanks you!

**Comment by RandomToni** [comment]
Hello,

We finally were able to make it work. After your tip, we checked the example files in the repo where and tried to copy the configuration. We found that we where using old modules and targets in the tsconfig.json file (ES2015) and we updated that to ESNext as the examples showed. 
Thanks!!

**Comment by joshuaellis** [comment]
Great to hear, glad I could help you out!
