### ISSUE TITLE
[bug]: Rotate Loop Speeding up on Android

### ISSUE THREAD

**Issue by samronning** [pmndrs/react-spring#1844]
Edit: Added Repo, fixed link to video
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.4.2

### What's Wrong?

On Android Chrome, I noticed the rotate looping seems to continually speed up and eventually become really unstable. It appears to be fine on pc.

Here is a video of the behavior

https://drive.google.com/file/d/14FfjJz-5a__V2L2bARhBO__ROcmqzUS_/view?usp=sharing

### To Reproduce

visit https://codesandbox.io/s/clever-bose-7pk2b5?file=/src/App.js with android chrome app (version 98.0.4758.101).

### Expected Behaviour

The rotation to not speed up over time.

### Link to repo

https://codesandbox.io/s/clever-bose-7pk2b5?file=/src/App.js

**Comment by joshuaellis** [comment]
Hi there, can you please provide a sandbox that demonstrates the bug not on a visual level but also a logging level so we can accurately look at it? 

Also the video you've supplied doesn't seem to work.

**Comment by samronning** [comment]
Added the repo and fixed the video

**Comment by joshuaellis** [comment]
Actually, it's this:
https://github.com/pmndrs/react-spring/blob/3365ceaad119460425971324c8ed1c97b476b4b1/packages/rafz/src/index.ts#L167
