### ISSUE TITLE
[bug]: beta versions of @react-spring/*** packages getting installed in the latest stable release

### ISSUE THREAD

**Issue by tim-soft** [pmndrs/react-spring#1855]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.4.2

### What's Wrong?

the latest `@react-spring/web` package appears to depend on unreleased beta packages

from my `yarn.lock`
![Screenshot 2022-03-07 111051](https://user-images.githubusercontent.com/10257939/157093570-808b96a7-1520-41bd-b0b0-70d682023b16.png)

### To Reproduce

install this version of react-spring: `@react-spring/web": "^9.4.2",`

### Expected Behaviour

I would expect only stable `@react-spring/***` dependencies in the stable releases

### Link to repo

https://github.com/tim-soft/react-spring-lightbox/pull/42/files

**Comment by joshuaellis** [comment]
Thank you for raising this @tim-soft! looks like there was a small issue in the `changesets` config, now resolved. `9.4.4` has the correctly set deps.

**Comment by tim-soft** [comment]
@joshuaellis thank you!
