### ISSUE TITLE
[bug]: useTransition v9 transitioning between nested routes

### ISSUE THREAD

**Issue by narkai** [pmndrs/react-spring#1899]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

Transitioning between routes with react-router and react-spring :

It almost works but after upgrading to 9.4.5, useTransition() misses a parameter that we used.

This parameter allowed to apply one type of transition on first level routes, so nested routes could use another transition type.

You can see the [working version here](https://iiode.live/) that used react-spring 8, clicking on arrows navigates nested routes while clicking on tags navigates main routes.

I don't know how to reproduce this with the new useTransition api, tried to use useSpringRef... but didn't find the secret recipe.

### To Reproduce

The old version that worked, based on [this](https://codesandbox.io/s/jp1wr1867w) :

```
const TopLevelTransition = props => {
  const {location} = useRouter();
  const routes = props.children;

  const transitions = useTransition(
    location,
    location => {
      // Apply only if the 2 first url's segments changes
      let segments = location.pathname.split('/');
      segments.splice(3, segments.length - 3);
      segments = segments.join('/');
      return segments;
    },
    {
      from: {opacity: 0, transform: 'translate3d(0,100%,0) scale(0.5)'},
      enter: {opacity: 1, transform: 'translate3d(0,0%,0) scale(1)'},
      leave: {opacity: 0, transform: 'translate3d(0,-50%,0) scale(0.5)'},
    }
  );

  return transitions.map(({item, props, key}) => (
    <animated.div key={key} className="width height absolute hidden" style={props}>
      <Switch location={item}>{routes}</Switch>
    </animated.div>
  ));
};
```

### Expected Behaviour

We would like the top level transition to trigger only on the top pages but not for nested routes.

See the Sandbox to visualize the problem and how top-level transition applies also to sub-pages.

This is the new version for which we don't know how to restrict the animation to top level routes (because useTransition is only has 2 parameters now) :

```
const TopLevelTransition = props => {
  const location = useLocation();
  const routes = props.children;

  const transition = useTransition(location, {
    from: {opacity: 0, y: '100%', scale: 0.5},
    enter: {opacity: 1, y: '0%', scale: 1},
    leave: {opacity: 0, y: '-50%', scale: 0.5},
    config: config.slow,
  });

  return transition((style, item) => (
    <a.div key={item.key} className="width height absolute hidden will-change" style={style}>
      <Switch location={item}>{routes}</Switch>
    </a.div>
  ));
};
```

### Link to repo

https://codesandbox.io/s/react-spring-9-transitioning-between-nested-routes-eins5e?file=/src/index.js

**Comment by narkai** [comment]
It's not a bug though, maybe it's more a feature request to add the third parameter.

**Comment by narkai** [comment]
Bottom line is :

With the new api, how can we tell useTransition() to "listen" only a portion of the router "location" ?

**Comment by narkai** [comment]
Just solved it !

With useTransition() key and ref api 😀 

[Nested routes CodeSandbox](useTransition) updated !

**Comment by joshuaellis** [comment]
Seems like the issue is resolved then? We can reopen if there's an issue. But I wouldn't read that documentation too much as i'm not actively updating that version. I would refer to `react-spring.io`

**Comment by narkai** [comment]
Thanks @joshuaellis, yes the issue is resolved.

 Glad to see my old project working on the new version, I'll refer to the official website from now on.
