### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by wkylin** [pmndrs/react-spring#1904]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### To Reproduce

import { Parallax, ParallaxLayer } from '@react-spring/web'

 <Parallax pages={2} style={{ top: '0', left: '0' }}>
    <ParallaxLayer offset={1} speed={2} style={{ backgroundColor: '#ff6d6d' }} />
 </Parallax>

### Expected Behaviour

no error 

### Link to repo

https://wkylin.github.io/promotion-web/#/parallax

**Comment by wkylin** [comment]
To Reproduce:
import { Parallax, ParallaxLayer } from '@react-spring/web'
 <Parallax pages={2} style={{ top: '0', left: '0' }}>
    <ParallaxLayer offset={1} speed={2} style={{ backgroundColor: '#ff6d6d' }} />
  </Parallax>

**Comment by joshuaellis** [comment]
`ParallaxLayer` requires a child
