### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by wkylin** [pmndrs/react-spring#1905]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.5

### What's Wrong?

import { Parallax, ParallaxLayer } from '@react-spring/web'

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### To Reproduce

import { Parallax, ParallaxLayer } from '@react-spring/web'

### Expected Behaviour

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

### Link to repo

https://wkylin.github.io/promotion-web/#/parallax

**Comment by joshuaellis** [comment]
The repro you've supplied is a bit odd and doesn't fully illustrate the issue in a clear way, you've also omitted the title which is also confusing.

Would you be able to supply a codesandbox version please?
