### ISSUE TITLE
[typo]: Small typo in Controller docs

### ISSUE THREAD

**Issue by superFortress** [pmndrs/react-spring#1960]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

v9.5.2

### What's Wrong?

The Controller docs refer to _contoller_ rather than _controller_ (missing an **r**) on nine separate occasions. For example, one of the suggested lines of code reads: `contoller.pause()`

### To Reproduce

You can find the docs here: https://react-spring.dev/classes/controller

### Expected Behaviour

Add the **r** to save any dyslexic developer from a frustrating afternoon.

### Link to repo

https://react-spring.dev/classes/controller

**Comment by joshuaellis** [comment]
These docs are no longer being maintained and will be replaced with our new beta docs – [beta.react-spring.dev/docs](https://beta.react-spring.dev/docs)
