### ISSUE TITLE
[bug]: useTrail docs has broken link

### ISSUE THREAD

**Issue by MonliH** [pmndrs/react-spring#1968]
### What version of react-spring are you using?

n/a

### What's Wrong?

The `shared-api` link on the `useTrail` docs page in the latest docs is broken; it seems to redirect me to a 404 page.

### To Reproduce

Go to [https://react-spring.dev/hooks/use-trail#properties](https://react-spring.dev/hooks/use-trail#properties), then press on the `shared-api` link.

### Expected Behaviour

The link should probably(?) redirect to [https://react-spring.dev/common/props#props](https://react-spring.dev/common/props#props).

### Link to repo

n/a

**Comment by joshuaellis** [comment]
This is invalid now, thanks for reporting.
