### ISSUE TITLE
[bug]: The initial style is not applied

### ISSUE THREAD

**Issue by cangSDARM** [pmndrs/react-spring#1973]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.4.4

### What's Wrong?

The initial style is not applied, causing the style to flicker. In the reproduce, I want to initialize the height to 0 and then expand; however the action is acting like the shrunk

two main problems:
![image](https://user-images.githubusercontent.com/20441896/188808499-c3a24600-86fb-4d7c-ba42-61a2ef5f9f93.png)
![image](https://user-images.githubusercontent.com/20441896/188808446-608c1643-b130-417a-a7ff-9796eb961bf1.png)

### To Reproduce

see reproduce link

### Expected Behaviour

apply the initial style, make the initial expansion animation smooth

### Link to repo

https://codesandbox.io/s/magical-panka-ewpv16

**Comment by joshuaellis** [comment]
This isn't a bug you incorrectly wrote your `useSpring` hook, you wrote: 

```ts
  const [animeStyles, api] = useSpring<AnimatedStyle>(() => {
    height: 0;
  });
```

it should have been:

```ts
  const [animeStyles, api] = useSpring<AnimatedStyle>(() => ({
    height: 0
  }));
```

In short, you werent returning an object from the function so `height` didn't exist as a `SpringValue`.

see this codesandbox – https://codesandbox.io/s/laughing-carson-kr6t0r?file=/src/Expandale.tsx
