### ISSUE TITLE
[bug]: Konva peer dependancy in `package.json`

### ISSUE THREAD

**Issue by slavokozar** [pmndrs/react-spring#1981]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [X] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

v9.5.4

### What's Wrong?

There is defined peerDependency `react-konva` in package.json:
```
 "react-konva": "^18.0.0-0",
 ```
 
 However in targets/konva there is another package.json which says:
```
 "react-konva": "^16.8.0 || ^17.0.0"
```

### To Reproduce

```
npm install react-spring
npm install @react-spring\konva
```

### Expected Behaviour

I see that konva v18 was added only few hours ago, so you maybe forgot to add it also to targets/konva. 
Set ` "react-konva": "^18.0.0-0",` as the peerDependency in  the file /targets/konva/package.json

### Link to repo

https://github.com/pmndrs/react-spring/blob/master/targets/konva/package.json

**Comment by joshuaellis** [comment]
closing in favour of #1861
