### ISSUE TITLE
[bug]: Not compatible with nextjs v13

### ISSUE THREAD

**Issue by Daavidaviid** [pmndrs/react-spring#2029]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.5.5

### What's Wrong?

Seems like it's not compatible with latest version of nextjs
<img width="1038" alt="Screenshot 2022-11-24 at 14 18 50" src="https://user-images.githubusercontent.com/32457364/203838898-f0f31468-1cff-42b9-b715-a7abb064c731.png">

### To Reproduce

Try with a nextjs13 app

### Expected Behaviour

for it to work

### Link to repo

Oops sorry don't have one yet

**Comment by joshuaellis** [comment]
I'm closing this as a low effort bug report.

**Comment by akomm** [comment]
You tried to run it on the server. You need to run it on the client.

Take the part that is animated, move it into a separate file and add "use client" at the top of the file.

Import the animated extracted component on the server.
