### ISSUE TITLE
[bug]: `useScroll` doesn't observe on its subsequent usage to the same container 

### ISSUE THREAD

**Issue by ajitid** [pmndrs/react-spring#2046]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.6.0

### What's Wrong?

If I use `useScroll` multiple times targeting the same container (say window), it only observes and reports values in its first use and not in its subsequent usage for that container. 

### To Reproduce

In the sandbox linked below, try moving the `log` prop between the components and scrolling each time after making the change. You would notice the values are only logged when `log` prop is assigned to the very first `<Component />`.

### Expected Behaviour

I expect the logs to appear each time, irrespective on which `<Component />` I've passed the prop to. 

### Link to repo

https://codesandbox.io/s/react-spring-onscroll-observe-callback-issue-jq31ek?file=/src/App.tsx

**Comment by joshuaellis** [comment]
resolved by b1be9d30
