### ISSUE TITLE
[bug]: <g> attribute transform:

### ISSUE THREAD

**Issue by furkananter** [pmndrs/react-spring#2063]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.6.1

### What's Wrong?

Error: <g> attribute transform: Expected ')', "…950353950163e-18translate(, ), 1…".
Hi, 
I always getting that error on my console.  How can i fix that?

I downloaded the react spring web version too but, still i am getting that error.

### To Reproduce

It started with using React Pro Sidebar.

### Expected Behaviour

I want to fix that error.

### Link to repo

https://github.com/pmndrs/react-spring

**Comment by joshuaellis** [comment]
Follow the template please and provide a reproduction of the issue.

**Comment by joesatriani10** [comment]
Im having the same issue when resizing the web app, im also using React Pro Sidebar, probably im gonna start from there.

**Comment by joshuaellis** [comment]
@joesatriani10 if you think you've found a bug, please open a new issue :)
