### ISSUE TITLE
[bug]: The website is completely unusable on security based chromium browsers

### ISSUE THREAD

**Issue by danny-does-stuff** [pmndrs/react-spring#2064]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

The Website

### What's Wrong?

The website has a serious error in the Chromium browsers "Arc Browser" and "Brave Browser". It is completely unusable

![image](https://user-images.githubusercontent.com/11875246/214719902-29553481-0314-4335-9611-9509005fe761.png)

### To Reproduce

Just open react-spring.dev in "Brave Browser" or "Arc Browser"

### Expected Behaviour

The site works

### Link to repo

N/A

**Comment by joshuaellis** [comment]
You're welcome to submit a PR to resolve this, unfortunately I don't think I will get round to this for some time.

**Comment by joshuaellis** [comment]
I don't have this issue on Arc. It could be something else you have installed e.g. an extension.

**Comment by chris-av** [comment]
@joshuaellis I have this issue as well. I have disabled the shield on my Brave Browser. The styled content actually flashes but reverts back to skeleton HTML. No errors on the console.

I checked the network tab on my browser and it is clear of any errors or failed requests.

The site looks good on Chrome.

**Comment by joshuaellis** [comment]
Hey @chris-av, thanks for the details. If you have ideas on what the problem could be, I'd encourage you to look at opening a PR to fix it! 😊
