### ISSUE TITLE
[feat]: Add multilingual support

### ISSUE THREAD

**Issue by Chuck-Ray** [pmndrs/react-spring#2065]
### A clear and concise description of what the feature is

Adding multilingual support can significantly increase influence and reduce the difficulty of use. Various translations can be increased through community contributions

### Why should this feature be included?

multilingual support，like chinese

### Please provide an example for how this would work

https://github.com/ant-design/ant-design-mobile

**Comment by joshuaellis** [comment]
This would 100% need someone to do the work for this because I don't speak any other language 😅

But totally open to it ✌🏼

**Comment by joshuaellis** [comment]
Closing this. It's been a year and no one has taken this up to work on multiple languages.
