### ISSUE TITLE
config object not working for useSprings

### ISSUE THREAD

**Issue by davy440** [pmndrs/react-spring#2090]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

8.11.0

### What's Wrong?

I am using useSprings to render a list of items and animate them. I am trying to create a basic background change animation on selecting the list item.

```
const question = () => {
const data = {
        q1: {
            question: "What kind of games do you have in your phone?",
            answer: {
                'a': ['Action Games (PUBG, Fortnite)', 'H'],
                'b': ['Racing games (Car Racing, Mario Kart)', 'S'],
                'c': ['Brain Teasers / Puzzles (Su-do-Ku, Jigsaw)', 'R'],
                'd': ['No games, I prefer playing outdoor sports', 'G']
            }
        }
    }

    const qaList = data[q1]
    const ansKeys = Object.keys(qaList.answer)

   const selectAnim = useSprings(ansKeys.length, ansKeys.map((item) => ({
        ref: api,
        from: {
            background: 'transparent',
            color: 'white'
        },
        config: {
            tension: 350,
            friction: 10
        }
    })))

   const selectAnswer = (e, i) => {

        api.start((index) => (
            index === i
            ? { background: 'rgba(255,255,255,0.7)', color: 'black' }
            : { background: 'transparent', color: 'white' })
        )

        const { house } = e.target.dataset
    }

   return (
        <div className='harry__qa p-8 bg-black/40 rounded-3xl backdrop-blur-sm'>
            <h2 className='harry__question text-4xl'>{question}</h2>
            <div className='harry__answer text-xl'>
                <ul className='harry__options mb-8'>
                    {
                        selectAnim.map((animation, index ) => {
                            const [ ans, house ] = Object.values(qaList.answer)[index]
                            return (
                                <animated.li
                                className={`flex relative before:content-[url(./assets/marker.svg)] before:h-full before:mr-2 before:relative leading-0 align-center cursor-pointer rounded-full p-4 border-2 border-white my-4 last:mb-0 mt-0 ${select === house ? "selected" : ""}`}
                                data-house={house}
                                style={animation}
                                onClick={(e) => selectAnswer(e, index)}
                                key={house}>{ans}</animated.li>
                            )
                        })
                    }
                </ul>
            </div>
        </div>
    )
}
```

This is the relevant code. Here, I've used useSprings to render a list of items from an object. I'm trying to animate the clicked item. It's working but the config object in the configuration argument is being ignored. I cannot modify the animations from there. However, when I specify the config object in api.start(), it seems to detect there. 
Referring to the [springConfig docs](https://react-spring.dev/docs/advanced/config), config object can be specified at the beginning but somehow it is not being detected. 

Is it a bug or am I doing something wrong?

### To Reproduce

You can just go to [https://github.com/davy440/harry-house-react-app/blob/master/src/question.js](https://github.com/davy440/harry-house-react-app/blob/master/src/question.js) and copy the code or open it in codesandbox.

### Expected Behaviour

When an item is selected, it should recognise the config object defined in the configuration object. Right now, it's being detected if I mention it in api.start() method but not in the configuration object.

### Link to repo

https://github.com/davy440/harry-house-react-app

**Comment by joshuaellis** [comment]
You're passing an array as the second argument to `useSprings` which is not allowed.

```js
const selectAnim = useSprings(ansKeys.length, (index) => {
	const ansKey = ansKeys[index]

	return {
        ref: api,
        from: {
            background: 'transparent',
            color: 'white'
        },
        config: {
            tension: 350,
            friction: 10
        }
    }
})
```

this would work.
If you want to change the config based on the spring key then you would do:

```js
const selectAnim = useSprings(ansKeys.length, (index) => {
	const ansKey = ansKeys[index]

	return {
        ref: api,
        from: {
            background: 'transparent',
            color: 'white'
        },
        config: key => ({
            tension: 350,
            friction: 10
        })
    }
})
```

**Comment by davy440** [comment]
Thanks!
I referred to [this](https://www.tabnine.com/code/javascript/functions/react-spring/useSprings) page. Here, array is passed as second argument. Is this code outdated?

Cheers!

**Comment by joshuaellis** [comment]
> Thanks! I referred to [this](https://www.tabnine.com/code/javascript/functions/react-spring/useSprings) page. Here, array is passed as second argument. Is this code outdated?
> 
> Cheers!

I've never seen this in my life. My advice would be don't trust everything you read on the internet, a libraries docs typically are the actual source of truth :)

**Comment by davy440** [comment]
Thanks! It worked.
Just needed to make 1 change in the code you provided. Has to destructure `useSprings` instead of using `useSpringRef` and passing the `ref` property.
