### ISSUE TITLE
[bug]: npm 9.7.0  dist files has '?.'  advanced es syntax

### ISSUE THREAD

**Issue by feix760** [pmndrs/react-spring#2096]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0 

### What's Wrong?

`?.` advanced es syntax not compiled

![bug](https://user-images.githubusercontent.com/5415656/221104127-60bb8f60-9c5f-4df5-b008-59434f0ea269.png)

### To Reproduce

set lower compiler target

### Expected Behaviour

support for es5 ? 

### Link to repo

no

**Comment by joshuaellis** [comment]
Please correctly fill out the template
