### ISSUE TITLE
[bug]: React Spring not working/breaking the app after updating to verison 9.7.0

### ISSUE THREAD

**Issue by ricardo-sendible** [pmndrs/react-spring#2098]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0

### What's Wrong?

Had to downgrade to 9.6.1 to fix the issue for now.

![image](https://user-images.githubusercontent.com/99668102/221175282-d1293c5f-fc38-4bdc-bb11-4a75abf4d3b7.png)

### To Reproduce

- Run yarn to update to latest version
- Run the application

P.s.: We are using react '17.0.2'.

### Expected Behaviour

React throws the following error:

![image](https://user-images.githubusercontent.com/99668102/221175282-d1293c5f-fc38-4bdc-bb11-4a75abf4d3b7.png)

### Link to repo

Private repo

**Comment by josegetlife** [comment]
+1
I use this library in a component library. 
It blocks me from any deployment I want to do in 3 projects.

**Comment by joshuaellis** [comment]
See – 2097
