### ISSUE TITLE
[bug]: BREAKING CHANGE: The request '@react-spring/types/interpolation' failed

### ISSUE THREAD

**Issue by Kishore180994** [pmndrs/react-spring#2102]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0

### What's Wrong?

I have updated my create-react-app (with typescript). 

Removed `node_modules` and `yarn.lock` and re-installed all the packages along with react-spring.

Previously I was using `react-spring`, recently saw the update `react-spring/web`. Updated my app and code to use the `react-spring/web`

I am getting these two errors.
```
ERROR in ./node_modules/@react-spring/core/dist/index.mjs 1596:0-45
Module not found: Error: Can't resolve '@react-spring/types/animated' in '<path_to_my_project>/node_modules/@react-spring/core/dist'
Did you mean 'animated.js'?
BREAKING CHANGE: The request '@react-spring/types/animated' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@react-spring/core/dist/index.mjs 1597:0-50
Module not found: Error: Can't resolve '@react-spring/types/interpolation' in '<path_to_my_project>/node_modules/@react-spring/core/dist'
Did you mean 'interpolation.js'?
BREAKING CHANGE: The request '@react-spring/types/interpolation' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

My package.json contains   _"@react-spring/web": "^9.7.0",_

In my code, I am just using the basic example

``` 
import { useSpring } from '@react-spring/web';

 const animProps = useSpring({
    from: { opacity: 0 },
    to: { opacity: 1 },
 });
```

### To Reproduce

- yarn add @react-spring/web
- Launch the app `yarn start`
- Observe the error.

I am not able to fix this error. Looking for pointers/some help to resolve this. It's wierd, I am not able to reproduce this issue in codesandbox. I am using CRA with typescript.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/23616209/221410201-bdbd3ca6-abef-4970-bdf0-f85bf5cbbcff.png">

### Expected Behaviour

Should run without any errors.

### Link to repo

Not able to reproduce in the codesandbox.

**Comment by Kishore180994** [comment]
Never mind, I saw another thread mentioning the same.

**Comment by joshuaellis** [comment]
Can you try the experiment release mentioned in the other issue and report back if it works for you? 😊
