### ISSUE TITLE
Must call super constructor in derived class before accessing 'this' or returning from derived constructor

### ISSUE THREAD

**Issue by nguyenhongphat0** [pmndrs/react-spring#2103]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0

### What's Wrong?

When `import { animated, config, to, useSpring } from "@react-spring/web";` with version `9.7.0`, we face the below issue 👇 

```
Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new ue2 (index.mjs:1:7199)
    at Lt2 (index.mjs:1:18262)
    at index.mjs:1:18149
    at index.mjs:1:18351
    at Array.forEach (<anonymous>)
    at Ve (index.mjs:1:676)
    at Mt (index.mjs:1:18324)
    at index.mjs:1:18139
    at Array.forEach (<anonymous>)
    at Ve (index.mjs:1:676)
```

![z4140688341107_6d87b47440c0026f4572ab2d13e1aadf](https://user-images.githubusercontent.com/29925961/221469471-705d5ee1-80f2-4185-8342-c982d3ac3f89.jpg)

It works fine with version <=9.6.1; nothing changed in the usage of react-spring.
Here is the line that caused the error:

<img width="1003" alt="Screenshot 2023-02-27 at 10 43 39" src="https://user-images.githubusercontent.com/29925961/221470162-8a8e6a8c-0f49-4e6b-842c-e18762850292.png">

### To Reproduce

`import { animated, config, to, useSpring } from "@react-spring/web";`

### Expected Behaviour

Spring animation should work as it used to in version `9.6.1` without any `Uncaught ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor`

### Link to repo

https://www.npmjs.com/package/zmp-ui/v/1.5.6

**Comment by joshuaellis** [comment]
Please provide a codesandbox reproduction of your issue :)
