### ISSUE TITLE
[bug]: 9.7.1 react-spring published ?

### ISSUE THREAD

**Issue by evamalininaa** [pmndrs/react-spring#2105]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.0

### What's Wrong?

https://github.com/pmndrs/react-spring/issues/2097#issuecomment-1446284520

Can you advice why I can't install 9.7.1
Receiving error "The latest release of react-spring is "9.7.0"."

### To Reproduce

pnpm i react-spring@9.7.1

### Expected Behaviour

0

### Link to repo

-

**Comment by joshuaellis** [comment]
<img width="798" alt="CleanShot 2023-02-27 at 16 46 09@2x" src="https://user-images.githubusercontent.com/37798644/221626303-d6136143-1afd-4e9c-84b3-406e37922b2d.png">

It's definitely there on NPM - and i've been able to install it in my packages.

**Comment by evamalininaa** [comment]
pnpm view react-spring versions

I see just this published versions
'9.7.0',
'10.0.0-alpha.0',
'10.0.0-alpha.1'
🙂

**Comment by evamalininaa** [comment]
Tried for different team members, don't see 9.7.1 in the list.
 "react-spring": "10.0.0-alpha.1" work fine

**Comment by joshuaellis** [comment]
> Tried for different team members, don't see 9.7.1 in the list. "react-spring": "10.0.0-alpha.1" work fine

I wouldn't use the 10 alpha – that's when I thought there was gonna be breaking changes for `react18` but there wasn't, however, it will not work with react18 😓

**Comment by evamalininaa** [comment]
> > Tried for different team members, don't see 9.7.1 in the list. "react-spring": "10.0.0-alpha.1" work fine
> 
> I wouldn't use the 10 alpha – that's when I thought there was gonna be breaking changes for `react18` but there wasn't, however, it will not work with react18 😓

ohh, but don't you think it's strange it shows 0 downloads for 9.7.1 on NPM still
would be great to know if other people have same issue, mb then we can kindly ask you to republish :))

**Comment by bpinto** [comment]
I've updated to `9.7.1`, but had to revert it because it causes Safari on iOS 13 to fail parsing the JS. Potentially related to https://github.com/pmndrs/react-spring/issues/2096 but I have to do more testing. Will report once I know more. But to your question, I could install it - I'm using `npm`.

**Comment by joshuaellis** [comment]
I've checked with some personal friends and they've also not had any issues – could be a number of things, but certainly nothing we can deal with unfortunately.

**Comment by fallenleavesguy** [comment]
I have downgraded to 9.6.1 work fine.
