### ISSUE TITLE
[bug]: Errors on Safari browser in iOS 12

### ISSUE THREAD

**Issue by maoxiaoke** [pmndrs/react-spring#2119]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.1

### What's Wrong?

I'm not sure if this was intentional, but to clarify: I have discovered that version 9.7.1 is causing errors on Safari browser in iOS 12. After some investigation, I found that [this PR](https://github.com/pmndrs/react-spring/pull/2082/files) has changed the original build process using tsup and set the target output to `esnext`. This may lead to compatibility issues in older browsers.

### To Reproduce

- Found it in older browsers

### Expected Behaviour

-

### Link to repo

-

**Comment by maoxiaoke** [comment]
> Are you not transpiling your app code to target the browser you want to support? 🤔
Modules in node_modules are excluded to my project's transpiling process.

**Comment by joshuaellis** [comment]
The library is not transpired so you can choose what level you want to support. E.g it would add a lot of polyfills if I set it to a browser as old as safari 12 adding weight whereas some people may only want to support modern browsers. Therefore I have chosen to take the agnostic approach. I'd recommend you transform your node modules

**Comment by simlmx** [comment]
I had a similar issue on iOS 12, on a `next.js` (version `12.2.2`) project. I tried using [`next-transpile-modules`][ntm] to force transpiling `react-spring` but it wouldn't. I'm not sure why or even if I'm doing the right thing... I ended up reverting to `react-spring@9.3.2` (the version I was using before) and it fixed the issue. 


[ntm]: https://www.npmjs.com/package/next-transpile-modules
