### ISSUE TITLE
[bug]: Optional chaining in version 9.7.1 output  file 

### ISSUE THREAD

**Issue by njleonzhang** [pmndrs/react-spring#2121]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.1/9.7.0

### What's Wrong?

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/13174059/224620585-b79d5c4c-77f6-45dc-91f5-939f7659b6db.png">

Optional chaining syntax exist in version 9.7, https://www.unpkg.com/@react-spring/shared@9.7.1/dist/index.js

### To Reproduce

https://www.unpkg.com/@react-spring/shared@9.7.1/dist/index.js

### Expected Behaviour

new version syntax should not exist in deliver js.

### Link to repo

https://www.unpkg.com/@react-spring/shared@9.7.1/dist/index.js

**Comment by joshuaellis** [comment]
Optional chaining is available in all major browsers - https://caniuse.com/?search=optional%20chaining so I don't think there's an issue here?

**Comment by njleonzhang** [comment]
I think it's definitely a breaking change, it's better to update the major version to 10, otherwise a minor version, which may cause lots of project broken.
