### ISSUE TITLE
[bug]: the docs appear broken on some browsers

### ISSUE THREAD

**Issue by juji** [pmndrs/react-spring#2131]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

i don't know

### What's Wrong?

The site looks wacked

### To Reproduce

https://www.react-spring.dev/

### Expected Behaviour

not wacked
![Screen Shot 2023-03-30 at 05 28 38](https://user-images.githubusercontent.com/493553/228682146-4ec9fa8e-586c-4e3b-8ba0-4ff8d341f998.png)

### Link to repo

https://www.react-spring.dev/

**Comment by chris-av** [comment]
I am getting the same issue as well. I am using Brave Browser. I do not have the same issue on Chrome. My network tab looks clear. I do not see any errors or failed requests.

**Comment by ziddee** [comment]
I'm getting the same issue. I'm using Chrome. These are the issues that are showing up.
![image](https://user-images.githubusercontent.com/93416061/230888050-ebf0b8ac-08b6-4241-a5c0-ba96b5243853.png)

**Comment by joshuaellis** [comment]
I'm using chrome & i've looked at brave and neither browsers are giving me issues with the docs site. This issue is also very poorly written. If someone who's experiencing issues can give more reproducible steps I can try and look at it, i'd open a new clear issue too while you're at it.

**Comment by chris-av** [comment]
Just went back to the website and it works now. I swear that not too long ago visiting the website looked like the screenshot at the top of this thread. Guess it works for me now. Not sure what happened. Wanted to post here to see if it is fixed for anyone else?

Anyway thanks for checking in on the issue!

**Comment by Finbel** [comment]
Thought it'd be worth to mention that I have the same issue in chrome (not in firefox or safari). It looks just like in the screenshot, as if the css has not loaded, all pages on react-spring.dev are affected.  The error does not persist in incognito mode.

**Comment by joshuaellis** [comment]
If it doesn't happen in incognito mode I'd look through your extensions as it's probably one of those interfering with the site.

**Comment by linkb15** [comment]
For me it is because of the [darkreader](https://darkreader.org/) chrome extension. It is fine after I ignore the site to from the darkreader.
