### ISSUE TITLE
[bug]: Undefined is not a function when animating transforms in react native.

### ISSUE THREAD

**Issue by Yahnych** [pmndrs/react-spring#2140]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [X] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.7.1

### What's Wrong?

https://github.com/pmndrs/react-spring/blob/bc3ce7604e608fee8b04feddf0011035433431f6/targets/native/src/AnimatedTransform.ts#L31
Seems like "_addToPayload" method doesnt exist.
In web version everything alright.

### To Reproduce

Animate any transforms of element.

### Expected Behaviour

No errors and animated elements.

### Link to repo

¯\_(ツ)_/¯

**Comment by Yahnych** [comment]
It was my mistake, with wrong style definition, sry.

**Comment by Eli-Nathan** [comment]
Is there a fix planned for this? Any idea which version this was introduced in so i can roll back?
