### ISSUE TITLE
[bug]: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.

### ISSUE THREAD

**Issue by Vera1128** [pmndrs/react-spring#2142]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.1

### What's Wrong?

 The code throws an error when I use react-spring in my react page on **_ipad with ios13.4.1_** 

error message 👇
`SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.`

 It works fine if I remove the code about react-spring.

### To Reproduce

none

### Expected Behaviour

expect it works  as well as other libraries

### Link to repo

none

**Comment by joshuaellis** [comment]
Can you provide a reproduction of the issue you're facing please?

**Comment by aivarasbiliunas** [comment]
It can be reproduced on Safari 13 version.

**Comment by JohnColvin** [comment]
We say this in our app, as well. It breaks for Safari 12 and 13.

**Comment by Harhao** [comment]
How to repair this question, I also reproduced this problem at Safari 13

**Comment by christianhubbard** [comment]
Also seeing the same problem on safari 13
