### ISSUE TITLE
[bug]: Images not loading in Vertical Parallax CodeSandBox

### ISSUE THREAD

**Issue by ashishsurya** [pmndrs/react-spring#2155]
### What version of react-spring are you using?

latest

### What's Wrong?

images not loading in vertical parallax codesandbox showcase.

<img width="1199" alt="image" src="https://github.com/pmndrs/react-spring/assets/72222785/43480cdf-595d-4d61-aeb8-0c848759a608">

<img width="1190" alt="image" src="https://github.com/pmndrs/react-spring/assets/72222785/bae4177f-a8a5-4d54-8545-9eb1c838a924">

### To Reproduce

change the images

### Expected Behaviour

to load images properly, in order to view the animation sample

### Link to repo

https://codesandbox.io/s/h1rrv

**Comment by MuhammadAakash** [comment]
Hi @ashishsurya . It's working fine. I checked the CodeSandbox link you provided, and the images are showing in the Preview section. Here are the results.
![Vertical-Parallax-CodeSandbox](https://github.com/pmndrs/react-spring/assets/64223049/350db20b-0107-472b-becf-c8ffb958698e)
