### ISSUE TITLE
[bug]: Scroll with Flatlist

### ISSUE THREAD

**Issue by dattv-unstatic** [pmndrs/react-spring#2162]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.2

### What's Wrong?

I am building my website using react-native-web.

**Problem**: When Flatlist is contained within a scrollable component (e.g. a div with overflow: 'scroll'), the onScroll event of the Flatlist is not triggered during scrolling.

### To Reproduce

Simplified:
 ```js
   export function App() {
    const scrollContainerRef = React.useRef<HTMLDivElement>(null!)
    const flatListRef = useRef<any>(null)
    const { scrollY } = useScroll({
        container: scrollContainerRef,
        default: {
            immediate: true,
        },
    })

    const onScroll = (event) => {
        const { y } = event.nativeEvent.contentOffset
        console.log({ y })
    }

    return (
        <>
            <div
                style={{
                    flex: 1,
                    overflowY: 'scroll',
                }}
                ref={scrollContainerRef}
            >
                <FlatList
                    ref={flatListRef}
                    data={[]}
                    renderItem={() => (
                        <></>
                    )}
                    onScroll={onScroll}
                />
            </div>
        </>
    )
}
```

### Expected Behaviour

Implement Flatlist and control scroll by react-spring.

### Link to repo

 *

**Comment by joshuaellis** [comment]
Please supply a minimal reproduction of the issue.
