### ISSUE TITLE
[bug]: Invalid hook call

### ISSUE THREAD

**Issue by OldManMeta** [pmndrs/react-spring#2166]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [X] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

^9.7.2

### What's Wrong?

The library is installed. npm ls react shows everything is fine in terms of dependencies. solution builds and runs.

I'm using the library to interpolate morph target influence values inside a component.

### To Reproduce

Create a R3F solution. Load a gltf model with morph targets. Attempt to change the influence of the morph target using the library. Watch it blow up.

### Expected Behaviour

That the value changes as required.

### Link to repo

No repo

**Comment by joshuaellis** [comment]
please provide a reproduction – issues without one are typically closed.

**Comment by OldManMeta** [comment]
@joshuaellis - thanks for the response. I'm not able to share this particular code - I just thought it very strange that this was failing. Close if you like, it's unfortunate that I will not be able to use the library in this solution currently. Shall try again on another solution in future. Cheers
