### ISSUE TITLE
[bug]: useTransition not working if called with function and deps 

### ISSUE THREAD

**Issue by samuelraub** [pmndrs/react-spring#2171]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

v9.7.1

### What's Wrong?

useTransition springs are not starting if called with a config function in `>=v9.5.2`. It works as expected and documented `<=v9.5.1`.

### To Reproduce

1. Open codesandbox
2. Click the toggle button (nothing happens)
3. Switch to v 9.5.1 
4. Click toggle button again (a div is animating in)

### Expected Behaviour

I expected useTransition to animate if the state in the dependency array changes.

### Link to repo

https://codesandbox.io/s/react-spring-cheatsheet-rht2y6?file=/src/UseTransition.tsx

**Comment by sators** [comment]
Not sure why this is closed...I am experiencing the same thing when trying to use a dependency array...

**Comment by Inviz** [comment]
Same issue
