### ISSUE TITLE
[bug]: Cannot find module '@react-spring/rafz'

### ISSUE THREAD

**Issue by everdimension** [pmndrs/react-spring#2173]
### Which react-spring target are you using?

- [X] `@react-spring/web`

### What version of react-spring are you using?

9.7.3

### What's Wrong?

I am having an issue similar to https://github.com/pmndrs/react-spring/issues/1559

I am using `parcel` to build my project. I am seeing this type warning:

> _node_modules/@react-spring/shared/dist/react-spring_shared.modern.d.ts:1:27 - error TS2307: Cannot find module '@react-spring/rafz' or its corresponding type declarations._
>
> _1 import { raf, Rafz } from '@react-spring/rafz';_

### To Reproduce

```
npm i @react-spring/web
... later in project ...
import { useSpring } from '@react-spring/web';
```

I can see that `@react-spring/rafz` is not in my node_modules, but in fact it's being used by `@react-spring/shared` package:
<img width="946" alt="image" src="https://github.com/pmndrs/react-spring/assets/5347023/227c2dc8-ad8e-4365-a78c-771dc115c3c3">

### Expected Behaviour

I think `@react-spring/rafz` is expected to be installed along with `@react-spring/web`

### Link to repo

-

**Comment by joshuaellis** [comment]
Can you share a reproduction of this please

**Comment by everdimension** [comment]
Sure!

Turns out this wasn't a parcel issue, but a `tsc` issue

Here's the reproduction repo: https://github.com/everdimension/react-spring-raf-repro

**Comment by cherishs001** [comment]
I had the same problem

**Comment by mateusvelleda** [comment]
actually it was introduced at 9.7.0

**Comment by rangaraju29139** [comment]
Hi everyone and @everdimension , I am beginner to Open-sourse Contributions and React ecosystem.
With whatever understanding that I have understood from this issue, I just want to express my point of view.

**My Observations:**
As it is mentioned in the share readmefile,  the shared library have the helper functions only to core and web libraries. I Don't think rafz has to be included with web.

**My Proposed Solution:** If we are using the "@react-spring/rafz" functionality , we have to explicitly import it.
<img width="418" alt="image" src="https://github.com/pmndrs/react-spring/assets/30431968/0367f08f-fa17-4dbc-ace7-5a9595cff95b">

[shared docs](https://github.com/pmndrs/react-spring/tree/main/packages/shared)



Thanks
rangaraju

**Comment by YassineGherbi** [comment]
> Sure!
> 
> Turns out this wasn't a parcel issue, but a `tsc` issue
> 
> Here's the reproduction repo: https://github.com/everdimension/react-spring-raf-repro

Could you explain how you determined this? Thanks!

**Comment by sarocu** [comment]
I additionally ran into this when disabling hoisting within PNPM - what was the `tsc` workaround?

**Comment by wegry** [comment]
@sarocu With Yarn 4, adding a explicit dependency in the .yarnrc.yml (I think PnP has a similar mechanism) should do the trick.

**Comment by tylerlaprade** [comment]
I also have this problem when running `tsc`. For now, I manually added `@react-spring/rafz` to my `package.json`, but ideally this dependency would be included directly in `@react-spring/web`.
