### ISSUE TITLE
[bug]: animation.div  seems to be an issue with the attributes's update

### ISSUE THREAD

**Issue by 1587315093** [pmndrs/react-spring#2174]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.6.1

### What's Wrong?

My maintenance the React componet library is ant-design-mobile. 
the component library Used a large amount useSpring

this issue in SwiperAction 

Open the browser's Debugger, dom attribute dont update (The div below  adm-swipe-action-content )

### To Reproduce

reproduce demo
https://codesandbox.io/s/confident-brown-4jfxf3?file=/src/App.tsx

1. Please click a b c ,can see List.Item's click execute

2. Please slide left on the SwiperAction component, operate on the right will appear

3. after that click edit button, click again click body, SwiperAction's right opereate disappear

4. at this time ,List.Item's click  dont execute

reason animation.div's pointer-events: none, 

code position https://github.com/ant-design/ant-design-mobile/blob/master/src/components/swipe-action/swipe-action.tsx#L249

Correctly returned 0, but the attribute of dom was not updated
### Expected Behaviour

attributes update

### Link to repo

null

**Comment by 1587315093** [comment]
https://github.com/ant-design/ant-design-mobile/issues/6184

**Comment by 1587315093** [comment]
This problem seems to be with React or react-spring
because the click has useState's setState
Insufficient priority?or react-spring no setState such as update processing

![image](https://github.com/pmndrs/react-spring/assets/77056991/6b031d0f-7cee-48e9-8c85-098fd6c53ba8)


1.  slide left on the SwiperAction, pointerEvents  is none
![image](https://github.com/pmndrs/react-spring/assets/77056991/3297c0e2-8838-47f8-a341-6e7ad0389b5a)

2. click edit button, SwiperAction back to 0, pointerEvents  is none,but dom tree attributes dont update
![image](https://github.com/pmndrs/react-spring/assets/77056991/fb7b06e4-3884-4944-ae6a-875f541430d1)
![image](https://github.com/pmndrs/react-spring/assets/77056991/4921c710-d245-41a0-9f80-ce6c846b7598)

**Comment by 1587315093** [comment]
<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=1587315093&theme=dark&layout=compact&show_icons=true">

**Comment by 1587315093** [comment]
<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=1587315093&theme=dark&layout=compact&show_icons=true">

**Comment by 1587315093** [comment]
@aleclarson @drcmda @joshuaellis 
have time to look at this question？

**Comment by joshuaellis** [comment]
You've provided an example where a lib uses `react-spring` so it's super hard to understand anything about what rs is doing, instead I would share a minimal reproduction of your issue ideally the src code of the ant library in it's most basic form that just illustrates the issue you're encountering. Until you do that, I don't think there's anything actionable with this issue unfortunately – sorry.

**Comment by 1587315093** [comment]
Here is my minimal rendition   @joshuaellis 

link: https://codesandbox.io/s/awesome-joana-t28gsz?file=/src/App.tsx

You can see that data-count is not updated correctly but x is already 0
