### ISSUE TITLE
[bug]: Missing Tweet in "Hear what our fans say" Section on React Spring Website

### ISSUE THREAD

**Issue by vinyashegde** [pmndrs/react-spring#2175]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

latest

### What's Wrong?

There is a bug in the React Spring website's 'Hear what our fans say' tweet section. Specifically, the tweet from @ryanflorence appears to be deleted or missing. This results in an inconsistency or broken display within the section.
![deleted tweet](https://github.com/pmndrs/react-spring/assets/46837876/6da40732-aff3-4680-8aa8-3ef0f50c265e)

### To Reproduce

Can i work on this issue? Can you assign me?

### Expected Behaviour

When a tweet is clicked within the "Hear what our fans say" section on the React Spring website, the corresponding tweet should open and be displayed without any missing content. Users should be able to view the complete tweet and its associated information upon clicking.

### Link to repo

https://github.com/pmndrs/react-spring

**Comment by joshuaellis** [comment]
If you want to work on the issue, just submit a pr, I don't normally assign issues 🌞

**Comment by vinyashegde** [comment]
> If you want to work on the issue, just submit a pr, I don't normally assign issues 🌞

Sure thanks for letting me know
