### ISSUE TITLE
[bug]: Some style problem in react-spring.dev

### ISSUE THREAD

**Issue by Ross249** [pmndrs/react-spring#2176]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

null

### What's Wrong?

In official website react-spring.dev, there is a style matter in it when I use my laptop. 
Here is the problem:
![problem](https://imgur.com/gallery/lLtYGCR)

### To Reproduce

use laptop to browse react-spring.dev
laptop screen: 1920*1080 scale 150%
browser: Chrome 114.0.5735.199

### Expected Behaviour

null

### Link to repo

null

**Comment by joshuaellis** [comment]
you've not attached a screenshot :)

**Comment by Ross249** [comment]
sorry about my mistake.
here is the screenshot: https://imgur.com/gallery/lLtYGCR
