### ISSUE TITLE
[bug]: @react-spring/konva + typescript

### ISSUE THREAD

**Issue by KH93b** [pmndrs/react-spring#2215]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [X] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.3

### What's Wrong?

animated.Rect -> Type instantiation is excessively deep and possibly infinite.ts(2589)

### To Reproduce

file .tsx + @react-spring/konva + animated.Rect

### Expected Behaviour

not error

### Link to repo

no repo

**Comment by joshuaellis** [comment]
This has been discussed a few times and unfortunately there's nothing I can do with the library to solve this.

**Comment by lavrton** [comment]
@joshuaellis hey. I am curious, why is it unsolvable? Are there some limitations from typescript? Or something I can do from konva/react-konva side?
It is possible to fix, but too complex?

**Comment by lavrton** [comment]
Ah, I found details here https://github.com/pmndrs/react-spring/issues/1515
