### ISSUE TITLE
[bug]: react-spring Identifier 'React' has already been declared

### ISSUE THREAD

**Issue by m-alfred** [pmndrs/react-spring#2231]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.3

### What's Wrong?

when i run webpack build it's ok。 but when i run webpack dev server， appear this error:  react-spring Identifier 'React' has already been declared。but run 。

`
ERROR in ./node_modules/@react-spring/animated/dist/react-spring_animated.modern.mjs 381:7
Module parse failed: Identifier 'React' has already been declared (381:7)
File was processed with these loaders:
 * ./node_modules/thread-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| // src/withAnimated.tsx
| import * as React from "react";
> import React, { forwardRef, useRef, useCallback, useEffect } from "react";
| import { is as is4, each as each2, raf, useForceUpdate, useOnce, addFluidObserver, removeFluidObserver, useIsomorphicLayoutEffect } from "@react-spring/shared";
| var withAnimated = function withAnimated(Component, host) {
 @ ./node_modules/@react-spring/web/dist/react-spring_web.modern.mjs 72:0-52 183:0-56 248:2-16 329:11-21
 @ ./src/containers/activity/components/business/lottery/index.tsx 63:0-76 128:20-30 566:40-52 573:19-30 666:22-32
 @ ./src/containers/activity/components/index.ts 29:0-56 29:0-56
 @ ./src/containers/activity/components/v2/index.tsx 60:0-195 346:46-54 423:46-52 434:46-56 445:46-52 462:46-51 474:46-58 487:46-54 501:46-53 514:46-50 527:46-58 556:46-51 575:46-52 583:46-57 591:46-56 603:46-61 615:46-64
 @ ./src/containers/activity/index.tsx 90:0-53 303:132-146 309:118-132 313:144-158 662:44-46
`

### To Reproduce

run webpack dev-server

### Expected Behaviour

no error appear

### Link to repo

none

**Comment by joshuaellis** [comment]
can you share a repo? I've used webpack on many projects with react-spring and not ran into any issues.

**Comment by m-alfred** [comment]
It's my babel config cause the error 。  I've fixed by removing the babel plugin:  babel-plugin-typescript-to-proptypes。

**Comment by joshuaellis** [comment]
Then it sounds like there's nothing we can do because it's your project 😊
