### ISSUE TITLE
[bug]: React-Spring.dev main website down

### ISSUE THREAD

**Issue by CindyU-beep** [pmndrs/react-spring#2233]
### Which react-spring target are you using?

- [ ] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

React Spring Website (https://www.react-spring.dev/)

### What's Wrong?

https://www.react-spring.dev/

React Spring main website appears to be down. Looks like issue with render method. 

https://github.com/pmndrs/react-spring/assets/63568702/58196357-85a0-4052-8b45-902727915d46

### To Reproduce

Visit: https://www.react-spring.dev/

Google Chrome Version 120.0.6099.72 (Official Build) (64-bit)
Safari version 17.1

### Expected Behaviour

Website should load as expected with all styling and correct formatting. 

### Link to repo

https://www.react-spring.dev/

**Comment by joshuaellis** [comment]
I'd check your extensions. I've seen other people have them interfere with the site.
