### ISSUE TITLE
[bug]: It’s the same problem. There is no CSS style when visiting the website.

### ISSUE THREAD

**Issue by rttmoa** [pmndrs/react-spring#2246]
### Which react-spring target are you using?

- [x] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

https://www.react-spring.dev/

### What's Wrong?

Website without CSS styles，Unable to view official document content and unable to search content

### To Reproduce

Website without CSS styles，Unable to view official document content and unable to search content

### Expected Behaviour

normal access

### Link to repo

https://www.react-spring.dev/

**Comment by joshuaellis** [comment]
Duplicate.
