### ISSUE TITLE
[bug]: useTransiton TS error

### ISSUE THREAD

**Issue by Mrcxt** [pmndrs/react-spring#2290]
### Which react-spring target are you using?

- [x] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

"@react-spring/web": "^9.7.3",

### What's Wrong?

useTransition cannot automatically infer types correctly

### To Reproduce

<img width="1205" alt="image" src="https://github.com/pmndrs/react-spring/assets/16064831/a4f4b6a2-8468-4e30-8d36-cef8901f4c85">

### Expected Behaviour

Hope to be able to automatically infer the type

### Link to repo

no

**Comment by joshuaellis** [comment]
it needs to be added to the `from` array.

**Comment by Mrcxt** [comment]
I don't quite understand, could you provide an example?
