### ISSUE TITLE
[bug]: `AnimatedComponent` incorrectly interprets `className` prop as `class-name` attribute

### ISSUE THREAD

**Issue by LoganDark** [pmndrs/react-spring#2291]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.3

### What's Wrong?

`<animated.div className={springValue} />` only updates `className` each React render. When the `springValue` updates, then a `class-name` attribute is updated instead of `className`.

### To Reproduce

Pass a `FluidValue` `className` to an `AnimatedComponent`.

### Expected Behaviour

`className` should be updated, not `class-name`.

### Link to repo

https://codesandbox.io/p/sandbox/dawn-platform-vclx4j

**Comment by joshuaellis** [comment]
why do you expect className to be animated value?

**Comment by LoganDark** [comment]
> why do you expect className to be animated value?

I expect when I set `className={springValue}` for the `className` prop to be animated, not a `class-name` attribute. I don't expect `className` to always be anything in particular, I just want it to work in the rare case that I do want to animate it.
