### ISSUE TITLE
[bug]: Transpiling a file that imports useSpring and then using the transpiled build in another project gives error- TypeError: (0 , _web.useSpring) is not a function

### ISSUE THREAD

**Issue by Abhinandan-Kushwaha** [pmndrs/react-spring#2309]
### Which react-spring target are you using?

- [x] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.4

### What's Wrong?

Transpiling a file that imports useSpring using Babel makes the build unusable and throws following error -
TypeError: (0 , _web.useSpring) is not a function

### To Reproduce

1. Make a react UI library that has a component say MyComponent which uses useSpring
2. Export MyComponent from the library
3. Build the library using Babel
4. Import MyComponent in another react project

### Expected Behaviour

Should not throw error

### Link to repo

https://github.com/pmndrs/react-spring

**Comment by ak-spotter** [comment]
+1 facing the same issue

**Comment by joshuaellis** [comment]
This needs a reproduction before it can be looked at.

**Comment by neehhaa06** [comment]
Hello!! @Abhinandan-Kushwaha :)

> To fix the `TypeError: (0 , _web.useSpring) is not a function` error, ensure your Babel configuration is set up correctly to handle ES modules and React hooks. Use `@babel/preset-env` with `"modules": false` and `@babel/preset-react`. Rebuild your library after clearing old builds, and make sure the `useSpring` import/export is correct in both your library and consuming project. Check that `react-spring` versions are consistent between them.
