### ISSUE TITLE
[bug]: Initial transition inconsistently "disappears"

### ISSUE THREAD

**Issue by whenmoon** [pmndrs/react-spring#2310]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.4.2

### What's Wrong?

As can be seen in the video, the first animated DOM elements inconsistently "vanish". The white flash in the video is reloading the screen in codesandbox, but the behavior was discovered in our app. If the `delay` property is removed from the config object, the problem is fixed. The workaround to fix it was to remove any `delay`, and update the values object using `setTimeout`. 

https://github.com/user-attachments/assets/00757b15-adfb-423c-b7f3-545cf1bd8279

### To Reproduce

Please see this [Codesandbox](https://codesandbox.io/p/devbox/sweet-williamson-sds9cy?file=%2Fsrc%2FApp.tsx%3A28%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz8k1hcb00073b6l37s6kz12%2522%252C%2522sizes%2522%253A%255B70.57113891383264%252C29.42886108616736%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz8k1hcb00023b6la48fpxci%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz8k1hcb00043b6liq5yxxcp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz8k1hcb00063b6lkign8raq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.358945310196916%252C45.641054689803084%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz8k1hcb00023b6la48fpxci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hca00013b6lt0df72ki%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz8k4lnu00023b6ltkpvl4tv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A28%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A28%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzb0n4pb00023b6ltq6euizi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FuseAnimation.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzb6a0pn00023b6mbe7fm3p3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A30%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz8k1hcb00023b6la48fpxci%2522%252C%2522activeTabId%2522%253A%2522clz8k4lnu00023b6ltkpvl4tv%2522%257D%252C%2522clz8k1hcb00063b6lkign8raq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hcb00053b6l0rfj2ges%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz8k1hcb00063b6lkign8raq%2522%252C%2522activeTabId%2522%253A%2522clz8k1hcb00053b6l0rfj2ges%2522%257D%252C%2522clz8k1hcb00043b6liq5yxxcp%2522%253A%257B%2522id%2522%253A%2522clz8k1hcb00043b6liq5yxxcp%2522%252C%2522activeTabId%2522%253A%2522clzb665rv02ek3b6lyhro303j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hcb00033b6llkarw6gn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clzb665rv02ek3b6lyhro303j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzb665tp00r4d9ipf1tt6fbt%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10.727799816905701%257D).

### Expected Behaviour

Elements do not disappear inconsistently. 

### Link to repo

Please see this [Codesandbox](https://codesandbox.io/p/devbox/sweet-williamson-sds9cy?file=%2Fsrc%2FApp.tsx%3A28%2C35&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clz8k1hcb00073b6l37s6kz12%2522%252C%2522sizes%2522%253A%255B70.57113891383264%252C29.42886108616736%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clz8k1hcb00023b6la48fpxci%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clz8k1hcb00043b6liq5yxxcp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clz8k1hcb00063b6lkign8raq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.358945310196916%252C45.641054689803084%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clz8k1hcb00023b6la48fpxci%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hca00013b6lt0df72ki%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clz8k4lnu00023b6ltkpvl4tv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A28%252C%2522startColumn%2522%253A35%252C%2522endLineNumber%2522%253A28%252C%2522endColumn%2522%253A35%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzb0n4pb00023b6ltq6euizi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A55%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A55%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FuseAnimation.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzb6a0pn00023b6mbe7fm3p3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A30%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A30%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clz8k1hcb00023b6la48fpxci%2522%252C%2522activeTabId%2522%253A%2522clz8k4lnu00023b6ltkpvl4tv%2522%257D%252C%2522clz8k1hcb00063b6lkign8raq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hcb00053b6l0rfj2ges%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clz8k1hcb00063b6lkign8raq%2522%252C%2522activeTabId%2522%253A%2522clz8k1hcb00053b6l0rfj2ges%2522%257D%252C%2522clz8k1hcb00043b6liq5yxxcp%2522%253A%257B%2522id%2522%253A%2522clz8k1hcb00043b6liq5yxxcp%2522%252C%2522activeTabId%2522%253A%2522clzb665rv02ek3b6lyhro303j%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clz8k1hcb00033b6llkarw6gn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clzb665rv02ek3b6lyhro303j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clzb665tp00r4d9ipf1tt6fbt%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A10.727799816905701%257D).

**Comment by joshuaellis** [comment]
Your reproduction is far too complicated to follow and understand that the issue is with the library not your code. Can you please make a minimal reproducible example? We can then re-open and re-visit. 

For some help, please see this article https://stackoverflow.com/help/minimal-reproducible-example
