### ISSUE TITLE
[bug]: EventHandler type should allow boolean types

### ISSUE THREAD

**Issue by richardaum** [pmndrs/react-spring#2324]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.4

### What's Wrong?

If we use any callback lets say for `useTransition` hook, type inference will fail if you use `boolean` as data. While investigating the root cause, I stumble upon this `EventHandler`. By reducing it to a single parameter function definition I could identify the issue with `boolean` type.

```ts
type EventHandler<Item = undefined> = 
  Item extends undefined ? 
    (item?: Item) => void : 
    (item: Item) => void;
```

### To Reproduce

If you try to assign `EventHandler` to an arrow function to see the error happening, you'll notice the issue, as pointed in [here](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogbhAdsAEgQ0QEwDYQE4A8AksBALZQC8UArlhAGYCWiEmAfFVCeVBAB6ksAZ1r1mrTFAD8UABRNSZaQC5uSgJRVOcAPZMpahUrU8yWyjv2YA3ACg7AY12JhwKAzRNsLAObwkVAwcfCJEBnwkRwg1AOR0LFxCACNdXVwMTmpjcgtOAG8oAF8oAHpSjy9sYScXNyhfNMw4oMTQ8MjEaNiEeOCkgjc8Pyz5RVztKEKS8qhhGkdotmEgA), but also below:

```ts
type EventHandler<Item = undefined> = Item extends undefined ? (item?: Item) => void : (item: Item) => void;

const failingEventHandlerInference: EventHandler<boolean> = (item) => { } // fails
const goodEventHandlerInference: EventHandler<string> = (item) => { } // succeeds
```

### Expected Behaviour

The real issue is that `Item extends undefined` that simply doesn't work with `boolean` type. Instead, as I expected both source code and who uses `EventHandler`s doesn't simply omit the `item` argument but provides a `undefined`-ish value, we could do:

```ts
type EventHandler<Item = undefined> = 
  (item: Item) => void
```

That will still allow `Item` to be inferred properly. After locally testing it by applying that change directly on my `node_modules/@react-spring/types/dist/react-spring_types.modern.d.ts`, it worked. As I simplified the `EventHandler` the actual change would be:

```ts
type EventHandler<TResult extends Readable = any, TSource = unknown, Item = undefined> = (result: AnimationResult<TResult>, ctrl: TSource, item: Item | undefined) => void;
```

[Source code](https://github.com/pmndrs/react-spring/blob/da2c12e5393ace14160d59e88b4d5f5d359fa602/packages/core/src/types/functions.ts#L81)

### Link to repo

- https://codesandbox.io/p/sandbox/react-typescript-forked-xf43l4
- https://www.typescriptlang.org/play/?#code/C4TwDgpgBAogbhAdsAEgQ0QEwDYQE4A8AksBALZQC8UArlhAGYCWiEmAfFVCeVBAB6ksAZ1r1mrTFAD8UABRNSZaQC5uSgJRVOcAPZMpahUrU8yWyjv2YA3ACg7AY12JhwKAzRNsLAObwkVAwcfCJEBnwkRwg1AOR0LFxCACNdXVwMTmpjcgtOAG8oAF8oAHpSjy9sYScXNyhfNMw4oMTQ8MjEaNiEeOCkgjc8Pyz5RVztKEKS8qhhGkdotmEgA

**Comment by joshuaellis** [comment]
Thank you for the great issue writing 💪🏼
