### ISSUE TITLE
[bug]: Typescript issue in Next.js 15

### ISSUE THREAD

**Issue by takeItIzzy** [pmndrs/react-spring#2332]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.5

### What's Wrong?

Animated tags don't support children prop.
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/35be64a0-8998-453d-b7cf-df310710e5f0">

### To Reproduce

Just use an animated tag in Next.js 15.

### Expected Behaviour

No typescript issues.

### Link to repo

No repo

**Comment by takeItIzzy** [comment]
This is likely due to React 19 - besides downgrading React to version 18, are there any other solutions?

**Comment by joshuaellis** [comment]
No, unfortunately not, we don't officially support react19 since it's not "stable" yet, obviously nextjs have decided it is against semver and that's their decision. I would do what you're doing now :)

**Comment by FISEM** [comment]
I found away to fix issue on the short term. Go to the typescript declaration and do that : 
`
// I don't know why it works like that
type Animated = {
    [Tag in keyof React.JSX.IntrinsicElements]: AnimatedComponent<Tag>;
  };

//just adding the Animated type 
declare const animated: Animated & WithAnimated;`


And you won't see typescript error anymore. But if you reinstall the package you'll be facing the same ts error.

**Comment by 1940879828** [comment]
I don't use React 19 but encountered the same bug
"next": "15.1.5",
"react": "^18.3.1",
"@react-spring/web": "^9.7.5",

**Comment by ta93imtk** [comment]
Declaring components before using them in JSX is worked for my environment.

`react 19.0.0` / `@react-spring/web 9.7.5`

```.ts
export default function App() {
  const [open, toggle] = useState(false)
  const [ref, { width }] = useMeasure()
  const props = useSpring({ width: open ? width : 0 })

  // ↓workaround
  const AnimatedDivFill = animated("div")
  const AnimatedDivContent = animated("div")
  // ↑

  return (
    <div className={styles.container}>
      <div ref={ref} className={styles.main} onClick={() => toggle(!open)}>
        <AnimatedDivFill className={styles.fill} style={props} />
        <AnimatedDivContent className={styles.content}>{props.width.to(x => x.toFixed(0))}</AnimatedDivContent>
      </div>
    </div>
  )
}
```
