### ISSUE TITLE
[bug]: animation is acting differently once deployed to vercel...

### ISSUE THREAD

**Issue by gkpo** [pmndrs/react-spring#2334]
### Which react-spring target are you using?

- [X] `@react-spring/web`
- [ ] `@react-spring/three`
- [ ] `@react-spring/native`
- [ ] `@react-spring/konva`
- [ ] `@react-spring/zdog`

### What version of react-spring are you using?

9.7.5

### What's Wrong?

I build a site locally on next js. After deploying to Vercel and opening it, the animation is slightly different, almost like my spring configuration (tension, friction, etc.) was different. Any idea what this could be due to ?

### To Reproduce

Here is my package json:

```
{
  "name": "---",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@react-spring/web": "^9.7.5",
    "lodash.debounce": "^4.0.8",
    "next": "15.0.2",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
  },
  "devDependencies": {
    "@types/lodash.debounce": "^4.0.9",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "15.0.2",
    "typescript": "^5"
  }
}
```

### Expected Behaviour

Deployed website should show the same animations as locally

### Link to repo

-

**Comment by joshuaellis** [comment]
There's not enough information to look into this, you need to provide a minimal reproduction of the issue please.
