### ISSUE TITLE
Transition not animating reordered items

### ISSUE THREAD

**Issue by 1000hz** [pmndrs/react-spring#296]
Hey Paul,

Thanks for the amazing work you've done on this library! 

I think I've come across a bug with Transition. It doesn't seem to be animating elements that have been reordered. I'd expect them to move to their new position according to the spring config, but they just appear in their new order.

Here's a CodeSandbox showing this behavior: 
https://codesandbox.io/s/k0kl78zw55

**Comment by drcmda** [comment]
Transition doesn't do that for the simple reason that it's just a stack that can retain dead elements. Similar to ReactTransitionGroup. What you want needs a bit of magic and i would have to override your styles and create wrappers, using translate3d and stuff, which would mess up your grids or whatever you put into there.


What you want can still be done with a single transition, take a look at this for instance and shuffle it: https://codesandbox.io/embed/0582jolnl

https://github.com/drcmda/mauerwerk/blob/master/src/index.js#L178-L189

**Comment by drcmda** [comment]
Here's a list that does re-ordering for you, also takes care of incoming and outgoing items. If you want it to animate height as well uncomment it in List.js:

https://codesandbox.io/embed/ql86k29zk9
