### ISSUE TITLE
Hooks documentation doesn’t make it clear that it’s a completely diffent entry point

### ISSUE THREAD

**Issue by yuchi** [pmndrs/react-spring#384]
~~Either I’m doing something wrong, or `useTransition` is not updating the values: https://codesandbox.io/s/5vk3p0qzxn~~

Please add in the [Hooks documentation](http://react-spring.surge.sh/hooks) something along these lines:

> [……] Hooks in react-spring are in a separate export in order to not interfere with the stable releases. As of version 7 this export is officially part of the npm package.
>
> Therefore you’ll need to access the `react-spring/hooks` entrypoint instead:
>
> ```js
> import { animated, useSpring } from 'react-spring/hooks';
> ```

**Comment by drcmda** [comment]
just wanted to answer ... yet, that's it. It's basically a separate react-spring export. would you be open to make a PR? my english is always so crippled when it comes to this :-)
