### ISSUE TITLE
springs without 'from' have no initial values until start() is called

### ISSUE THREAD

**Issue by stuartkeith** [pmndrs/react-spring#598]
Hi, I've been playing around with react-spring recently and it's great fun. I did run into an issue that stumped me for a little bit. I figured out a solution, but I thought I'd raise it as an issue because I don't think it's an obvious fix.

I started with a normal spring:

```
const example = useSpring({
   foo: bar ? 3 : 2
});
```

Works fine. Then I decided I'd like to put it in a chain with another spring. I looked up the docs and saw I had to add a ref:

```
const exampleRef = useRef();

const example = useSpring({
  ref: exampleRef,
  foo: bar ? 3 : 2
});
```

Now I encounter what seems to be a bug - `useSpring` is returning an empty object. No sign of the `foo` property.

Here's a codepen - it's just the chain example from the docs with the `from` object commented out: https://codesandbox.io/s/lyvzvmvkv7

I dug into the code and figured out a fix - manually adding a `from` property:

```
const exampleRef = useRef();

const example = useSpring({
  ref: exampleRef,
  from: {
    foo: bar ? 3 : 2
  },
  foo: bar ? 3 : 2
});
```

Now the spring returns the property. But from the docs, I had the impression `from` was optional and the spring would otherwise start from the first `to` value passed in. It took me a while to figure out that was causing the issue - my spring was working fine before the `ref`.

Looking at the code, the `to` property is taken out of the props in `Controller.update` using a spread (https://github.com/react-spring/react-spring/blob/master/src/animated/Controller.ts#L56).

The remaining `props` object (without `to`) is then passed to `Controller.diff`. This function would usually iterate `this.merged` to update `this.animations`, but `this.merged` is an empty object, as the `to` has been removed. If `from` was passed in, this would be included in `this.merged`, and that's why `this.animations` is updated properly in that case.

The reason `useSprings` works without a `ref` and without a `from` is because it calls `Controller.start`, which processes the queue and merges in the values. But `useSprings` skips the `Controller.start` call if a `ref` is present. That's why the `animated/Controller.test.ts` tests pass - they call `start()` before checking values. Removing the `start` call before checking the initial value causes the tests to fail.

I've fixed this in a local repo by having `Controller.update` copy `to` into `props.from` (if it's undefined), but I haven't made a PR as I'm not 100% sure whether that's a good solution - I haven't been using the library for long and don't know the codebase. If I can help any further please let me know.

Thanks!

**Comment by drcmda** [comment]
That is expected. And documented here: https://www.react-spring.io/docs/hooks/use-spring (under async chain).

If you're using delays or refs the springs are executed async. In other words, the view doesn't get any properties. Even if you start animating later on, nothing's connected.

From is the official way to prep async springs, by using it you make sure the view gets animated-props. Later on you can start or update them and the view will respond.

**Comment by drcmda** [comment]
Sadly, it looks like this isn't even mentioned in the useChain docs page. I'll add this when i find the time.

**Comment by joshuaellis** [comment]
This is very outdated. Please open a new issue following the template if you feel the issue persists.
