### ISSUE TITLE
Conditionally firing an update effect in useTransition

### ISSUE THREAD

**Issue by Nizarius** [pmndrs/react-spring#640]
## 🚀 Feature Proposal
React's useEffect hook allows to conditionally firing an effect by passing array of values that the effect depends on:
https://reactjs.org/docs/hooks-reference.html#useeffect
```
useEffect(
  () => {
    const subscription = props.source.subscribe();
    return () => {
      subscription.unsubscribe();
    };
  },
  [props.source],
);
```
I suggest to implement that in useTransition.

## Motivation
Now useTransition calls update's cycle on every new props which can break animation execution if you have more than one prop in functional component. 
We can change it in 2 ways:
1) By default call update's cycle only on changing items props (as in #635). And if we want to add extraProps, we pass them explicitly.
2) By default call update's cycle on every new props and if we want to override this behaviour, we add extraProps array.

I think 2 way would be ideal as it won't break any of the current examples in docs (https://www.react-spring.io/docs/hooks/use-transition) and also would be more customisable. But it's up to you. If you agree, I can implement that feature in a short time in any way (as we already use it in our fork).

## Example
`useTransition(items, keyExtractor, [...extraProps])`

**Comment by aleclarson** [comment]
It's not clear to me how `extraProps` affects a `useTransition` call. Can you give a better example?

**Comment by Nizarius** [comment]
@aleclarson it's easier for me to show suggested code changes.

Can you please look at https://github.com/react-spring/react-spring/pull/652 ? It's just a few lines of code but clearly shows what I want (and this code we also use in our project).

It's easier to show such changes in useSprings as it has more simple logic than useTransition. I just want to have an ability to manage which props should trigger useEffect which is under the hood of all react-spring's hooks. 

P.S. Sorry if i'm bothering you with all my little PRs and issues. We're just making difficult UI with your library and need to move fast. We're supporting our fork but really want to move on original react-spring with all these features.

**Comment by aleclarson** [comment]
#652 looks good, so I manually rebased it into the `v9` branch for you. 👍 

Maybe `useTransition` should have an `updateDeps` prop which prevents the `update` prop from being applied when nothing in the `updateDeps` array has changed. Or maybe `useTransition` having 4 arguments isn't so bad? 

Thoughts on this, @drcmda?
