### ISSUE TITLE
Using percentages on width transition in multistage useTransition throws type error

### ISSUE THREAD

**Issue by meisterpeeps** [pmndrs/react-spring#643]
## 🐛 Bug Report

Using percentages on width transition in multistage hook useTransition throws type error
`TypeError: entry.interpolation.calc is not a function`
>   1249 | if (reset || hasNewGoal && currentValueDiffersFromGoal || hasNewConfig) {
>   1250 |   // Convert regular values into animated values, ALWAYS re-use if possible
>   1251 |   if (isNumber || isString) parent = interpolation$$1 = entry.parent || new AnimatedValue(fromValue);else if (isArray) parent = interpolation$$1 = entry.parent || new AnimatedValueArray(fromValue);else if (isInterpolation) {
> > `1252 |     var prev = entry.interpolation && entry.interpolation.calc(entry.parent.value);`
>        | ^  1253 |     prev = prev !== void 0 && !reset ? prev : fromValue;
>   1254 | 
>   1255 |     if (entry.parent) {

## To Reproduce

Use a string percentage in a multi-stage useTransition hook width.
`enter: {width: '20%', opacity: 1}` works
`enter: [{width: '20%'}, {opacity: 1}]` throws error

## Environment

- `react-spring` v8.0.19
- `react` v16.8.2

I also just checked the behavior on the 9 beta version.  The problem still exists, but instead of a type error I get a  

> Warning: `NaN` is an invalid value for the `width` css style property.

-- and the width doesn't render.   On 9 the screen does in fact render though, just with broken css.  On 8 I get a red screen.

**Comment by aleclarson** [comment]
Could you provide a CodeSandbox using `react-spring@next`?

**Comment by meisterpeeps** [comment]
Sure;  Let me hook one up.

**Comment by meisterpeeps** [comment]
Not the most interesting example... but it still works, yah?
https://codesandbox.io/s/yk59609241
The problem occurs also with height.  I just forked one of the examples and updated it to next, and changed the height to a string percentage.

**Comment by aleclarson** [comment]
Using `"0%"` in place of `0` for `height` fixes that example. It seems that interpolating from a number to a percentage is not yet supported.

**Comment by meisterpeeps** [comment]
Awesome.   Since I can go from a percentage to a percentage in my particular use case this actually fixed my problem 😛.   I appreciate the very quick feedback.

**Comment by aleclarson** [comment]
No problem! Let's keep this open as a feature request for number-to-percentage animations (and vice versa).
