### ISSUE TITLE
Not working on Firefox if `privacy.resistFingerprinting` is set to true

### ISSUE THREAD

**Issue by danilowoz** [pmndrs/react-spring#664]
## 🐛 Bug Report

When this feature is true, the package doesn't work. You can find more details about what `resistFingerprinting` does here: https://wiki.mozilla.org/Security/Fingerprinting 

## To Reproduce

Open Firefox and set the `privacy.resistFingerprinting` as true in `about:config` and just open an example of React Spring

## Expected behavior

Works fine

## Link to repro (highly encouraged)

Even React-spring website doesn't work 

## Environment

- `react-spring` v8.x.x
- `react` v16.8.x (or `react-native` v0.58.x)

**Comment by MaximeCheramy** [comment]
I'd also like to add that the website https://www.react-spring.io/ isn't working properly with Firefox with that option on: the menus can't be open.

**Comment by aleclarson** [comment]
I haven't looked into this much yet, but I suspect the following points to be part of the issue:
> - The performance API is mostly disabled
> - Time Precision is reduced to 100ms, with up to 100ms of jitter
The best bet might be to disable animation entirely:
```ts
import { Globals } from 'react-spring'

Globals.assign({
  skipAnimation: privacy.resistFingerprinting,
})
```

**Comment by amertak** [comment]
To detect that fingerprinting is enabled something like

```
import { Globals } from 'react-spring'

if (performance.mark && performance.getEntries) {
	performance.mark('dummy_check')
	const entries = performance.getEntries()
	
        Globals.assign({
		skipAnimation: entries && entries.length === 0,
	})
}
```

can be used.

Also check for FF can be added using the `navigator.appCodeName`

**Comment by tomjn** [comment]
In `about:config` the jitter can be turned on/off and the precision changed. I set jitter to `false` and increased precision from `1000` to `1` with no resolution.

**Comment by visualcookie** [comment]
Any update on this, as this is buggering me right now?

**Comment by MonliH** [comment]
Yeah, seems this is still an issue.

**Comment by amassarwi** [comment]
I just upgraded to `v9rc3` and the issue seems to be fixed!

**Comment by joshuaellis** [comment]
Issue seems to be fixed as of v9rc3
