### ISSUE TITLE
Remove Parallax.Layer in favor of named export in the next major release

### ISSUE THREAD

**Issue by TrySound** [pmndrs/react-spring#72]
https://github.com/drcmda/react-spring/commit/f2d0137b36215d8e67d14a184f2ee912e49288b2#diff-11538ab7c7691ae187abb1e9124a1c6fR131

**Comment by TrySound** [comment]
@drcmda I think it will be a breaking change. I kept it for 5, but skipped it.

**Comment by drcmda** [comment]
I had it in the back of my mind but forgot to include it 😱next one it'll be in.
