### ISSUE TITLE
useSprings only puts animation into first ref

### ISSUE THREAD

**Issue by Vidlec** [pmndrs/react-spring#756]
## 🐛 Bug Report

When passing `ref` to each spring in `useSprings`, only the first `ref` gets the animation.
This breaks `useChain` 

## To Reproduce

See repro below 👀

## Expected behavior

Each ref has its animations and `useChain` correctly chains them

## Link to repro (highly encouraged)

[CodeSandbox](https://codesandbox.io/s/priceless-chaplygin-rdbj2?fontsize=14)

## Environment

only tested in
- `react-spring` `v8.0.25` and `9.0.0-beta.31`
- `react` v16.8.1 and v16.9.0

I suspect it happens in all versions

**Comment by Pytal** [comment]
Have you solved it?

**Comment by joshuaellis** [comment]
closing in favour of #1367
