### ISSUE TITLE
Support my volunteer work on react-spring v9

### ISSUE THREAD

**Issue by aleclarson** [pmndrs/react-spring#832]
With your financial support, we can make react-spring a sustainable OSS project. I've spent hundreds of hours on react-spring v9, and we would all benefit if I was compensated for my efforts. Of course, this isn't to make anyone feel guilty, but we all have a part to play in keeping the OSS ecosystem as healthy as possible. :)

Become a patron today: https://patreon.com/aleclarson  
Become a sponsor today: https://github.com/sponsors/aleclarson

**Comment by kaneki666** [comment]
Do you guys need anyone to translate the documention in  Bengali language?!
