### ISSUE TITLE
Jumpy scrollTo after mouse scroll on Parallax

### ISSUE THREAD

**Issue by jason-crowley** [pmndrs/react-spring#888]
## 🐛 Bug Report

After using the mouse to scroll a Parallax component, calling the Parallax's scrollTo method causes a jumpy transition instead of smoothly scrolling to the given offset.

I already posted a comment in #607, but since that issue is closed and abandoned, I decided to open a new issue.

## To Reproduce

1. Navigate to the sandbox for the [Parallax demo](https://codesandbox.io/s/nwq4j1j6lm?from-embed) on the React Spring page.
2. After loading the page, click the screen (at offset 0) to scroll to the second page (offset 1).
3. Use mouse to scroll back up to the top of the page (offset 0).
4. Click the first screen (offset 0) again to scroll to the second page (offset 1) again.

## Expected behavior

**Expected:** Clicking the first screen (offset 0) for the second time should smoothly scroll to the second page (offset 1) as it did for the first click.
**Actual:** For the second click, the screen jumps up suddenly and the "bash" image of the second page also seems to appear out of nowhere very quickly.

Also it should be noted that the transition from page 1 -> page 2 remains smooth as long as you click through all three screens to get back to the first page (i.e. don't scroll in between).

## Link to repro (highly encouraged)

 [Updated CodeSandbox demo](https://codesandbox.io/s/lingering-voice-0ewl9) (This is just the original demo sandbox with all dependencies updated to their latest versions to show that the problem persists)

## Environment

- `react-spring` v8.0.27
- `react` v16.12.0

**Comment by joshuaellis** [comment]
Thanks for reporting the bug, unfortunately, due to resourcing & maintainer change overs there’s no one able to work on v8 so we’re freezing development on it. However, you’re welcome to supply a fix on the v8 branch if you’d like. If the issue remains in v9 then please reopen a new issue, but bare in mind it might be quicker still to provide your own fix and contribute.
