### ISSUE TITLE
Error while updating property 'transform' of a view managed by: RCTView

### ISSUE THREAD

**Issue by aakashsigdel** [pmndrs/react-spring#900]
## 🐛 Bug Report

I am get following error using the `v9.0.0-beta.34` on react-native to transform a view:
```
Error while updating property 'transform' of a view managed by: RCTView
java.lang.String cannot be cast to com.facebook.react.bridge.ReadableArray
```

## To Reproduce
This is the minimal code to reproduce the error:
```js
import React from 'react';
import { View, Text } from 'react-native';
import { animated } from 'react-spring';

const AnimatedView = animated(View);

const App = () => (
  <AnimatedView
    style={{
      width: 300,
      height: 100,
      backgroundColor: 'red',
      transform: [{scaleY: 100}],
    }}
  />
);
```

## Expected behavior

The app should run without crashing

## Environment

- `react-spring` v9.0.0-beta.34
- `react-native` v0.61.5

**Comment by aleclarson** [comment]
Does it work with v8?

**Comment by aakashsigdel** [comment]
@aleclarson  it does

**Comment by MrCreeper1008** [comment]
It does not work for me on v8?

**Comment by aleclarson** [comment]
I've been using v9 with react-native (eg: animating `transform` prop) without issue.

Can someone provide a git repository that reproduces the crash?

**Comment by MrCreeper1008** [comment]
OK, my bad. If I hardcode the transform value it will work, but if I pass the prop given by useTransitions then the error will appear. I'll make a repo later.

**Comment by creativiii** [comment]
Also experiencing this. 

**react-spring** `v9.0.0-beta.34`
**react-native** `v0.61.4`

**Comment by MrCreeper1008** [comment]
Weird. I’m experiencing this bug on `^8.0.27` as well.

**Comment by creativiii** [comment]
I'm also on Android, but currently running my app through Expo. That might be what's making the difference.

Will try to build asap and see if it still happens.

**Comment by MrCreeper1008** [comment]
yea my project is vanilla react native project. will try with expo later to see if it makes any difference.

**Comment by pinchez254** [comment]
also experiencing the same on android. 
am passing an animated value from keyboard listeners
//
const keyboardHeight = new Animated.Value(0);
 const keyboardDidShow = e => {
    let toVaue = -e.endCoordinates.height;
    Animated.timing(keyboardHeight, {
      toVaue: toVaue,
      duration: 250,
      easing: Easing.linear,
      useNativeDriver: true,
    }).start();
  };

**Comment by jackyleehong** [comment]
having the same problem as well in android.

**Comment by Jlexyc** [comment]
The same issue I have:
`<Animated.View style={{ transform: [ {rotateZ: `${rotateAnimation}deg`} ]  }}>`
If I use rotateAnimation as
`const rotateAnimation = useRef(new Animated.Value(0)).current`

with animation:
```
Animated.timing(
      rotateAnimation,
      {
        toValue: 3600 * Math.PI / 180,
        duration: 15000,
        useNativeDriver: true,
        easing: Easing.linear
      })
```


But if set static value instead of rotateAnimation, everything goes well, except no animation :)

**Comment by joshuaellis** [comment]
I recently helped someone with an issue regarding RN & react-spring with `transform` and I didn't see any errors. If this is still a problem, lets open a new issue with a fresh bug report.
