### ISSUE TITLE
Parallax is not working anymore

### ISSUE THREAD

**Issue by MBach** [pmndrs/react-spring#929]
## 🐛 Bug Report

Parallax is not working anymore

## To Reproduce

Update     
`"@react-spring/parallax": "9.0.0-canary.808.11.4be2ac3"`
to
`"@react-spring/parallax": "9.0.0-canary.808.17.55c5691"`

With
```
<Parallax ref={parallax} pages={2} enabled={false}>
...
</Parallax>
```

## Expected behavior

Layer should change when one is dragging the DIV.

## Link to repro (highly encouraged)

https://codesandbox.io/s/react-spring-parallax-qt4tr

## Environment

- `react-spring` c9.0.0-canary.808.17.55c5691
- `@react-spring/parallax` v9.0.0-canary.808.17.55c5691
- `react` v16.12.0

**Comment by aleclarson** [comment]
Please try with v9.0.0-rc.2 #985

If the bug persists, please give a step-by-step list on what to do in your repro. 👍
