### ISSUE TITLE
useChain for the same transition

### ISSUE THREAD

**Issue by vladaxinte** [pmndrs/react-spring#932]
Is there any way to use useChain for the same transition when transitioning between routes? I'm trying to avoid overlapping the same animations.

https://codesandbox.io/s/modest-chaplygin-cff39?fontsize=14&hidenavigation=1&theme=dark

**Comment by vladaxinte** [comment]
I changed the leave translate to move downwards so they don't overlap, but the curiosity remains: how can chain the same transition without using delays? (I like the spring based concept a lot)

**Comment by aleclarson** [comment]
In v9, `useTransition` ref doesn't work with `useChain` currently

In v8, `useTransition` has no `ref` prop
