### ISSUE TITLE
Animations not working on inline svg v9

### ISSUE THREAD

**Issue by loren-jiang** [pmndrs/react-spring#937]
## 🐛 Bug Report

Animations not working on inline svg components in v9. Works in v8.

## Link to repro (highly encouraged)

[ demo](https://codesandbox.io/s/react-spring-inline-svg-grokm)

## Environment

- `react-spring` v9.0.0-beta.34

**Comment by aleclarson** [comment]
Please try with [the latest canary](https://spectrum.chat/react-spring/general/try-the-new-v9-canary~c5cad1eb-c6ff-4b40-9a10-76d368c3e404). 👍
