### ISSUE TITLE
Enter animation works, but leave animation duration doesn't

### ISSUE THREAD

**Issue by fandy** [pmndrs/react-spring#943]
When using a transition, the enter animation has the correct animation durations, but the leave animation does not. This is on both web and iOS, and I'm not doing anything extraordinary from the docs.

It makes me wonder if it's a bug, or if it's simply not well documented?

Here is a reproducible Modal component: https://gist.github.com/fandy/782aa895af859a9a1a7a77da43dc53fc

**Comment by aleclarson** [comment]
Please try with `9.0.0-rc.2` (#985) 👍

**Comment by aleclarson** [comment]
Please try with `9.0.0-rc.3` (#985) 👍
